#include <cyc_include.h>
extern int Cyc_nrules;
extern int Cyc_nsyms;
extern int Cyc_ntokens;
extern int Cyc_nvars;
extern struct _fat_ptr Cyc_ritem;
extern struct _fat_ptr Cyc_rrhs;
extern int Cyc_start_symbol;
extern struct _fat_ptr Cyc_derives;
void Cyc_set_fderives();
void Cyc_set_firsts();
extern void Cyc_RTC(struct _fat_ptr,int);
struct _fat_ptr Cyc_itemset;
struct _fat_ptr Cyc_itemsetend;
static struct _fat_ptr Cyc_ruleset;
static struct _fat_ptr Cyc_fderives;
static struct _fat_ptr Cyc_firsts;
static int Cyc_rulesetsize;
static int Cyc_varsetsize;
void Cyc_initialize_closure(int n) {
  struct _fat_ptr _T0;
  int _T1;
  short * _T2;
  unsigned int _T3;
  unsigned int _T4;
  int _T5;
  int _T6;
  int _T7;
  struct _fat_ptr _T8;
  int _T9;
  unsigned int * _TA;
  unsigned int _TB;
  unsigned int _TC;
  _T1 = n;
  { unsigned int _TD = (unsigned int)_T1;
    _T3 = _check_times(_TD,sizeof(short));
    { short * _TE = _cycalloc_atomic(_T3);
      { unsigned int _TF = _TD;
	unsigned int _new2_cyclone;
	_new2_cyclone = 0;
	_TL3: if (_new2_cyclone < _TF) { goto _TL1;
	}else { goto _TL2;
	}
	_TL1: _T4 = _new2_cyclone;
	_TE[_T4] = 0;
	_new2_cyclone = _new2_cyclone + 1;
	goto _TL3;
	_TL2: ;
      }_T2 = (short *)_TE;
    }_T0 = _tag_fat(_T2,sizeof(short),_TD);
  }Cyc_itemset = _T0;
  _T5 = Cyc_nrules + 1;
  _T6 = _T5 + 32;
  _T7 = _T6 - 1;
  Cyc_rulesetsize = _T7 / 32;
  _T9 = Cyc_rulesetsize;
  { unsigned int _TD = (unsigned int)_T9;
    _TB = _check_times(_TD,sizeof(unsigned int));
    { unsigned int * _TE = _cycalloc_atomic(_TB);
      { unsigned int _TF = _TD;
	unsigned int _new2_cyclone;
	_new2_cyclone = 0;
	_TL7: if (_new2_cyclone < _TF) { goto _TL5;
	}else { goto _TL6;
	}
	_TL5: _TC = _new2_cyclone;
	_TE[_TC] = 0U;
	_new2_cyclone = _new2_cyclone + 1;
	goto _TL7;
	_TL6: ;
      }_TA = (unsigned int *)_TE;
    }_T8 = _tag_fat(_TA,sizeof(unsigned int),_TD);
  }Cyc_ruleset = _T8;
  Cyc_set_fderives();
}
void Cyc_set_fderives() {
  struct _fat_ptr _T0;
  int _T1;
  unsigned int * _T2;
  unsigned int _T3;
  unsigned int _T4;
  struct _fat_ptr _T5;
  int _T6;
  int _T7;
  struct _fat_ptr _T8;
  int _T9;
  struct _fat_ptr _TA;
  int _TB;
  int _TC;
  int _TD;
  struct _fat_ptr * _TE;
  struct _fat_ptr _TF;
  unsigned char * _T10;
  unsigned int * _T11;
  unsigned int _T12;
  unsigned int _T13;
  unsigned int _T14;
  int _T15;
  struct _fat_ptr _T16;
  int _T17;
  unsigned char * _T18;
  struct _fat_ptr * _T19;
  struct _fat_ptr * _T1A;
  struct _fat_ptr _T1B;
  unsigned char * _T1C;
  short * _T1D;
  short _T1E;
  int _T1F;
  struct _fat_ptr _T20;
  int _T21;
  unsigned char * _T22;
  unsigned int * _T23;
  int _T24;
  unsigned int _T25;
  int _T26;
  int _T27;
  struct _fat_ptr * _T28;
  struct _fat_ptr _T29;
  unsigned char * _T2A;
  unsigned int * _T2B;
  struct _fat_ptr * _T2C;
  int _T2D;
  struct _fat_ptr rrow;
  struct _fat_ptr vrow;
  register int j;
  register unsigned int cword;
  struct _fat_ptr rp;
  register int b;
  int ruleno;
  int i;
  _T1 = Cyc_nvars * Cyc_rulesetsize;
  { unsigned int _T2E = (unsigned int)_T1;
    _T3 = _check_times(_T2E,sizeof(unsigned int));
    { unsigned int * _T2F = _cycalloc_atomic(_T3);
      { unsigned int _T30 = _T2E;
	unsigned int _new2_cyclone;
	_new2_cyclone = 0;
	_TLB: if (_new2_cyclone < _T30) { goto _TL9;
	}else { goto _TLA;
	}
	_TL9: _T4 = _new2_cyclone;
	_T2F[_T4] = 0U;
	_new2_cyclone = _new2_cyclone + 1;
	goto _TLB;
	_TLA: ;
      }_T2 = (unsigned int *)_T2F;
    }_T0 = _tag_fat(_T2,sizeof(unsigned int),_T2E);
  }_T5 = _T0;
  _T6 = Cyc_ntokens * Cyc_rulesetsize;
  _T7 = - _T6;
  Cyc_fderives = _fat_ptr_plus(_T5,sizeof(unsigned int),_T7);
  Cyc_set_firsts();
  _T8 = Cyc_fderives;
  _T9 = Cyc_ntokens * Cyc_rulesetsize;
  rrow = _fat_ptr_plus(_T8,sizeof(unsigned int),_T9);
  i = Cyc_ntokens;
  _TLF: if (i < Cyc_nsyms) { goto _TLD;
  }else { goto _TLE;
  }
  _TLD: _TA = Cyc_firsts;
  _TB = i - Cyc_ntokens;
  _TC = Cyc_varsetsize;
  _TD = _TB * _TC;
  vrow = _fat_ptr_plus(_TA,sizeof(unsigned int),_TD);
  _TE = &vrow;
  _TF = _fat_ptr_inplace_plus_post(_TE,sizeof(unsigned int),1);
  _T10 = _check_fat_subscript(_TF,sizeof(unsigned int),0U);
  _T11 = (unsigned int *)_T10;
  cword = *_T11;
  b = 0;
  j = Cyc_ntokens;
  _TL13: if (j < Cyc_nsyms) { goto _TL11;
  }else { goto _TL12;
  }
  _TL11: _T12 = cword;
  _T13 = 1U << b;
  _T14 = _T12 & _T13;
  _T15 = (int)_T14;
  if (! _T15) { goto _TL14;
  }
  _T16 = Cyc_derives;
  _T17 = j;
  _T18 = _check_fat_subscript(_T16,sizeof(struct _fat_ptr),_T17);
  _T19 = (struct _fat_ptr *)_T18;
  rp = *_T19;
  _TL16: _T1A = &rp;
  _T1B = _fat_ptr_inplace_plus_post(_T1A,sizeof(short),1);
  _T1C = _check_fat_subscript(_T1B,sizeof(short),0U);
  _T1D = (short *)_T1C;
  _T1E = *_T1D;
  ruleno = (int)_T1E;
  _T1F = ruleno;
  if (_T1F > 0) { goto _TL17;
  }else { goto _TL18;
  }
  _TL17: _T20 = rrow;
  _T21 = ruleno / 32;
  _T22 = _check_fat_subscript(_T20,sizeof(unsigned int),_T21);
  _T23 = (unsigned int *)_T22;
  _T24 = ruleno % 32;
  _T25 = 1U << _T24;
  *_T23 = *_T23 | _T25;
  goto _TL16;
  _TL18: goto _TL15;
  _TL14: _TL15: b = b + 1;
  if (b < 32) { goto _TL19;
  }
  _T26 = j + 1;
  _T27 = Cyc_nsyms;
  if (_T26 >= _T27) { goto _TL19;
  }
  _T28 = &vrow;
  _T29 = _fat_ptr_inplace_plus_post(_T28,sizeof(unsigned int),1);
  _T2A = _T29.curr;
  _T2B = (unsigned int *)_T2A;
  cword = *_T2B;
  b = 0;
  goto _TL1A;
  _TL19: _TL1A: j = j + 1;
  goto _TL13;
  _TL12: _T2C = &rrow;
  _T2D = Cyc_rulesetsize;
  _fat_ptr_inplace_plus(_T2C,sizeof(unsigned int),_T2D);
  i = i + 1;
  goto _TLF;
  _TLE: Cyc_firsts = _tag_fat(0,0,0);
}
void Cyc_set_firsts() {
  int _T0;
  int _T1;
  struct _fat_ptr _T2;
  int _T3;
  unsigned int * _T4;
  unsigned int _T5;
  unsigned int _T6;
  struct _fat_ptr _T7;
  int _T8;
  unsigned char * _T9;
  struct _fat_ptr * _TA;
  struct _fat_ptr _TB;
  unsigned char * _TC;
  short * _TD;
  short _TE;
  int _TF;
  struct _fat_ptr _T10;
  struct _fat_ptr _T11;
  struct _fat_ptr * _T12;
  struct _fat_ptr _T13;
  unsigned char * _T14;
  short * _T15;
  short _T16;
  int _T17;
  unsigned char * _T18;
  short * _T19;
  short _T1A;
  int _T1B;
  unsigned char * _T1C;
  short * _T1D;
  short _T1E;
  int _T1F;
  struct _fat_ptr _T20;
  int _T21;
  unsigned char * _T22;
  unsigned int * _T23;
  int _T24;
  unsigned int _T25;
  struct _fat_ptr * _T26;
  int _T27;
  struct _fat_ptr row;
  register int symbol;
  struct _fat_ptr sp;
  register int rowsize;
  int i;
  _T0 = Cyc_nvars + 32;
  _T1 = _T0 - 1;
  rowsize = _T1 / 32;
  Cyc_varsetsize = rowsize;
  _T3 = Cyc_nvars * rowsize;
  { unsigned int _T28 = (unsigned int)_T3;
    _T5 = _check_times(_T28,sizeof(unsigned int));
    { unsigned int * _T29 = _cycalloc_atomic(_T5);
      { unsigned int _T2A = _T28;
	unsigned int _new2_cyclone;
	_new2_cyclone = 0;
	_TL1E: if (_new2_cyclone < _T2A) { goto _TL1C;
	}else { goto _TL1D;
	}
	_TL1C: _T6 = _new2_cyclone;
	_T29[_T6] = 0U;
	_new2_cyclone = _new2_cyclone + 1;
	goto _TL1E;
	_TL1D: ;
      }_T4 = (unsigned int *)_T29;
    }_T2 = _tag_fat(_T4,sizeof(unsigned int),_T28);
  }Cyc_firsts = _T2;
  row = Cyc_firsts;
  i = Cyc_ntokens;
  _TL22: if (i < Cyc_nsyms) { goto _TL20;
  }else { goto _TL21;
  }
  _TL20: _T7 = Cyc_derives;
  _T8 = i;
  _T9 = _check_fat_subscript(_T7,sizeof(struct _fat_ptr),_T8);
  _TA = (struct _fat_ptr *)_T9;
  sp = *_TA;
  _TL23: _TB = sp;
  _TC = _check_fat_subscript(_TB,sizeof(short),0U);
  _TD = (short *)_TC;
  _TE = *_TD;
  _TF = (int)_TE;
  if (_TF >= 0) { goto _TL24;
  }else { goto _TL25;
  }
  _TL24: _T10 = Cyc_ritem;
  _T11 = Cyc_rrhs;
  _T12 = &sp;
  _T13 = _fat_ptr_inplace_plus_post(_T12,sizeof(short),1);
  _T14 = _T13.curr;
  _T15 = (short *)_T14;
  _T16 = *_T15;
  _T17 = (int)_T16;
  _T18 = _check_fat_subscript(_T11,sizeof(short),_T17);
  _T19 = (short *)_T18;
  _T1A = *_T19;
  _T1B = (int)_T1A;
  _T1C = _check_fat_subscript(_T10,sizeof(short),_T1B);
  _T1D = (short *)_T1C;
  _T1E = *_T1D;
  symbol = (int)_T1E;
  if (symbol < Cyc_ntokens) { goto _TL26;
  }
  _T1F = Cyc_ntokens;
  symbol = symbol - _T1F;
  _T20 = row;
  _T21 = symbol / 32;
  _T22 = _check_fat_subscript(_T20,sizeof(unsigned int),_T21);
  _T23 = (unsigned int *)_T22;
  _T24 = symbol % 32;
  _T25 = 1U << _T24;
  *_T23 = *_T23 | _T25;
  goto _TL27;
  _TL26: _TL27: goto _TL23;
  _TL25: _T26 = &row;
  _T27 = rowsize;
  _fat_ptr_inplace_plus(_T26,sizeof(unsigned int),_T27);
  i = i + 1;
  goto _TL22;
  _TL21: Cyc_RTC(Cyc_firsts,Cyc_nvars);
}
void Cyc_closure(struct _fat_ptr corex,int n) {
  struct _fat_ptr _T0;
  int _T1;
  struct _fat_ptr _T2;
  int _T3;
  struct _fat_ptr _T4;
  int _T5;
  struct _fat_ptr _T6;
  unsigned char * _T7;
  unsigned int * _T8;
  struct _fat_ptr _T9;
  unsigned char * _TA;
  unsigned int * _TB;
  struct _fat_ptr * _TC;
  struct _fat_ptr _TD;
  unsigned char * _TE;
  unsigned int * _TF;
  struct _fat_ptr * _T10;
  struct _fat_ptr _T11;
  unsigned char * _T12;
  unsigned int * _T13;
  struct _fat_ptr _T14;
  unsigned char * _T15;
  unsigned int * _T16;
  struct _fat_ptr _T17;
  unsigned char * _T18;
  unsigned int * _T19;
  struct _fat_ptr * _T1A;
  struct _fat_ptr _T1B;
  unsigned char * _T1C;
  unsigned int * _T1D;
  struct _fat_ptr _T1E;
  unsigned char * _T1F;
  short * _T20;
  struct _fat_ptr _T21;
  unsigned char * _T22;
  short * _T23;
  struct _fat_ptr _T24;
  struct _fat_ptr * _T25;
  struct _fat_ptr _T26;
  unsigned char * _T27;
  short * _T28;
  short _T29;
  int _T2A;
  unsigned char * _T2B;
  short * _T2C;
  short _T2D;
  struct _fat_ptr _T2E;
  int _T2F;
  struct _fat_ptr _T30;
  unsigned char * _T31;
  unsigned int * _T32;
  struct _fat_ptr _T33;
  unsigned char * _T34;
  unsigned int * _T35;
  struct _fat_ptr * _T36;
  struct _fat_ptr _T37;
  unsigned char * _T38;
  unsigned int * _T39;
  struct _fat_ptr * _T3A;
  struct _fat_ptr _T3B;
  unsigned char * _T3C;
  unsigned int * _T3D;
  unsigned int _T3E;
  struct _fat_ptr _T3F;
  unsigned char * _T40;
  unsigned int * _T41;
  struct _fat_ptr _T42;
  unsigned char * _T43;
  unsigned int * _T44;
  struct _fat_ptr * _T45;
  struct _fat_ptr _T46;
  unsigned char * _T47;
  unsigned int * _T48;
  unsigned int _T49;
  unsigned int _T4A;
  unsigned int _T4B;
  int _T4C;
  struct _fat_ptr _T4D;
  int _T4E;
  unsigned char * _T4F;
  short * _T50;
  short _T51;
  struct _fat_ptr _T52;
  unsigned char * _T53;
  short * _T54;
  struct _fat_ptr _T55;
  unsigned char * _T56;
  short * _T57;
  struct _fat_ptr _T58;
  unsigned char * _T59;
  short * _T5A;
  short _T5B;
  int _T5C;
  int _T5D;
  struct _fat_ptr * _T5E;
  struct _fat_ptr _T5F;
  unsigned char * _T60;
  short * _T61;
  struct _fat_ptr * _T62;
  struct _fat_ptr _T63;
  unsigned char * _T64;
  short * _T65;
  struct _fat_ptr * _T66;
  struct _fat_ptr _T67;
  unsigned char * _T68;
  short * _T69;
  int _T6A;
  struct _fat_ptr _T6B;
  unsigned char * _T6C;
  short * _T6D;
  struct _fat_ptr _T6E;
  unsigned char * _T6F;
  short * _T70;
  struct _fat_ptr * _T71;
  struct _fat_ptr _T72;
  unsigned char * _T73;
  short * _T74;
  struct _fat_ptr * _T75;
  struct _fat_ptr _T76;
  unsigned char * _T77;
  short * _T78;
  register int ruleno;
  register unsigned int word;
  struct _fat_ptr csp;
  struct _fat_ptr dsp;
  struct _fat_ptr rsp;
  struct _fat_ptr csend;
  struct _fat_ptr rsend;
  int symbol;
  int itemno;
  rsp = Cyc_ruleset;
  _T0 = Cyc_ruleset;
  _T1 = Cyc_rulesetsize;
  rsend = _fat_ptr_plus(_T0,sizeof(unsigned int),_T1);
  _T2 = corex;
  _T3 = n;
  csend = _fat_ptr_plus(_T2,sizeof(short),_T3);
  if (n != 0) { goto _TL28;
  }
  _T4 = Cyc_fderives;
  _T5 = Cyc_start_symbol * Cyc_rulesetsize;
  dsp = _fat_ptr_plus(_T4,sizeof(unsigned int),_T5);
  _TL2A: _T6 = rsp;
  _T7 = _T6.curr;
  _T8 = (unsigned int *)_T7;
  _T9 = rsend;
  _TA = _T9.curr;
  _TB = (unsigned int *)_TA;
  if (_T8 < _TB) { goto _TL2B;
  }else { goto _TL2C;
  }
  _TL2B: _TC = &rsp;
  _TD = _fat_ptr_inplace_plus_post(_TC,sizeof(unsigned int),1);
  _TE = _check_fat_subscript(_TD,sizeof(unsigned int),0U);
  _TF = (unsigned int *)_TE;
  _T10 = &dsp;
  _T11 = _fat_ptr_inplace_plus_post(_T10,sizeof(unsigned int),1);
  _T12 = _check_fat_subscript(_T11,sizeof(unsigned int),0U);
  _T13 = (unsigned int *)_T12;
  *_TF = *_T13;
  goto _TL2A;
  _TL2C: goto _TL29;
  _TL28: _TL2D: _T14 = rsp;
  _T15 = _T14.curr;
  _T16 = (unsigned int *)_T15;
  _T17 = rsend;
  _T18 = _T17.curr;
  _T19 = (unsigned int *)_T18;
  if (_T16 < _T19) { goto _TL2E;
  }else { goto _TL2F;
  }
  _TL2E: _T1A = &rsp;
  _T1B = _fat_ptr_inplace_plus_post(_T1A,sizeof(unsigned int),1);
  _T1C = _check_fat_subscript(_T1B,sizeof(unsigned int),0U);
  _T1D = (unsigned int *)_T1C;
  *_T1D = 0U;
  goto _TL2D;
  _TL2F: csp = corex;
  _TL30: _T1E = csp;
  _T1F = _T1E.curr;
  _T20 = (short *)_T1F;
  _T21 = csend;
  _T22 = _T21.curr;
  _T23 = (short *)_T22;
  if (_T20 < _T23) { goto _TL31;
  }else { goto _TL32;
  }
  _TL31: _T24 = Cyc_ritem;
  _T25 = &csp;
  _T26 = _fat_ptr_inplace_plus_post(_T25,sizeof(short),1);
  _T27 = _check_fat_subscript(_T26,sizeof(short),0U);
  _T28 = (short *)_T27;
  _T29 = *_T28;
  _T2A = (int)_T29;
  _T2B = _check_fat_subscript(_T24,sizeof(short),_T2A);
  _T2C = (short *)_T2B;
  _T2D = *_T2C;
  symbol = (int)_T2D;
  if (symbol < Cyc_ntokens) { goto _TL33;
  }
  _T2E = Cyc_fderives;
  _T2F = symbol * Cyc_rulesetsize;
  dsp = _fat_ptr_plus(_T2E,sizeof(unsigned int),_T2F);
  rsp = Cyc_ruleset;
  _TL35: _T30 = rsp;
  _T31 = _T30.curr;
  _T32 = (unsigned int *)_T31;
  _T33 = rsend;
  _T34 = _T33.curr;
  _T35 = (unsigned int *)_T34;
  if (_T32 < _T35) { goto _TL36;
  }else { goto _TL37;
  }
  _TL36: _T36 = &rsp;
  _T37 = _fat_ptr_inplace_plus_post(_T36,sizeof(unsigned int),1);
  _T38 = _check_fat_subscript(_T37,sizeof(unsigned int),0U);
  _T39 = (unsigned int *)_T38;
  _T3A = &dsp;
  _T3B = _fat_ptr_inplace_plus_post(_T3A,sizeof(unsigned int),1);
  _T3C = _check_fat_subscript(_T3B,sizeof(unsigned int),0U);
  _T3D = (unsigned int *)_T3C;
  _T3E = *_T3D;
  *_T39 = *_T39 | _T3E;
  goto _TL35;
  _TL37: goto _TL34;
  _TL33: _TL34: goto _TL30;
  _TL32: _TL29: ruleno = 0;
  Cyc_itemsetend = Cyc_itemset;
  csp = corex;
  rsp = Cyc_ruleset;
  _TL38: _T3F = rsp;
  _T40 = _T3F.curr;
  _T41 = (unsigned int *)_T40;
  _T42 = rsend;
  _T43 = _T42.curr;
  _T44 = (unsigned int *)_T43;
  if (_T41 < _T44) { goto _TL39;
  }else { goto _TL3A;
  }
  _TL39: _T45 = &rsp;
  _T46 = _fat_ptr_inplace_plus_post(_T45,sizeof(unsigned int),1);
  _T47 = _check_fat_subscript(_T46,sizeof(unsigned int),0U);
  _T48 = (unsigned int *)_T47;
  word = *_T48;
  if (word != 0U) { goto _TL3B;
  }
  ruleno = ruleno + 32;
  goto _TL3C;
  _TL3B: { register int b;
    b = 0;
    _TL40: if (b < 32) { goto _TL3E;
    }else { goto _TL3F;
    }
    _TL3E: _T49 = word;
    _T4A = 1U << b;
    _T4B = _T49 & _T4A;
    _T4C = (int)_T4B;
    if (! _T4C) { goto _TL41;
    }
    _T4D = Cyc_rrhs;
    _T4E = ruleno;
    _T4F = _check_fat_subscript(_T4D,sizeof(short),_T4E);
    _T50 = (short *)_T4F;
    _T51 = *_T50;
    itemno = (int)_T51;
    _TL43: _T52 = csp;
    _T53 = _T52.curr;
    _T54 = (short *)_T53;
    _T55 = csend;
    _T56 = _T55.curr;
    _T57 = (short *)_T56;
    if (_T54 < _T57) { goto _TL46;
    }else { goto _TL45;
    }
    _TL46: _T58 = csp;
    _T59 = _check_fat_subscript(_T58,sizeof(short),0U);
    _T5A = (short *)_T59;
    _T5B = *_T5A;
    _T5C = (int)_T5B;
    _T5D = itemno;
    if (_T5C < _T5D) { goto _TL44;
    }else { goto _TL45;
    }
    _TL44: _T5E = &Cyc_itemsetend;
    _T5F = _fat_ptr_inplace_plus_post(_T5E,sizeof(short),1);
    _T60 = _check_fat_subscript(_T5F,sizeof(short),0U);
    _T61 = (short *)_T60;
    _T62 = &csp;
    _T63 = _fat_ptr_inplace_plus_post(_T62,sizeof(short),1);
    _T64 = _T63.curr;
    _T65 = (short *)_T64;
    *_T61 = *_T65;
    goto _TL43;
    _TL45: _T66 = &Cyc_itemsetend;
    _T67 = _fat_ptr_inplace_plus_post(_T66,sizeof(short),1);
    _T68 = _check_fat_subscript(_T67,sizeof(short),0U);
    _T69 = (short *)_T68;
    _T6A = itemno;
    *_T69 = (short)_T6A;
    goto _TL42;
    _TL41: _TL42: ruleno = ruleno + 1;
    b = b + 1;
    goto _TL40;
    _TL3F: ;
  }_TL3C: goto _TL38;
  _TL3A: _TL47: _T6B = csp;
  _T6C = _T6B.curr;
  _T6D = (short *)_T6C;
  _T6E = csend;
  _T6F = _T6E.curr;
  _T70 = (short *)_T6F;
  if (_T6D < _T70) { goto _TL48;
  }else { goto _TL49;
  }
  _TL48: _T71 = &Cyc_itemsetend;
  _T72 = _fat_ptr_inplace_plus_post(_T71,sizeof(short),1);
  _T73 = _check_fat_subscript(_T72,sizeof(short),0U);
  _T74 = (short *)_T73;
  _T75 = &csp;
  _T76 = _fat_ptr_inplace_plus_post(_T75,sizeof(short),1);
  _T77 = _check_fat_subscript(_T76,sizeof(short),0U);
  _T78 = (short *)_T77;
  *_T74 = *_T78;
  goto _TL47;
  _TL49: ;
}
void Cyc_finalize_closure() {
  struct _fat_ptr _T0;
  int _T1;
  Cyc_itemset = _tag_fat(0,0,0);
  Cyc_ruleset = _tag_fat(0,0,0);
  _T0 = Cyc_fderives;
  _T1 = Cyc_ntokens * Cyc_rulesetsize;
  Cyc_fderives = _fat_ptr_plus(_T0,sizeof(unsigned int),_T1);
  Cyc_fderives = _tag_fat(0,0,0);
}
