#include <cyc_include.h>
struct Cyc___cycFILE;
extern struct Cyc___cycFILE * Cyc_stderr;
 struct Cyc_String_pa_PrintArg_struct {
  int tag;
  struct _fat_ptr f1;
};
 struct Cyc_Int_pa_PrintArg_struct {
  int tag;
  unsigned long f1;
};
extern int Cyc_fprintf(struct Cyc___cycFILE *,struct _fat_ptr,struct _fat_ptr);
extern int Cyc_putc(int,struct Cyc___cycFILE *);
struct Cyc___cycFILE;
extern struct Cyc___cycFILE * Cyc_stderr;
extern int Cyc_fprintf(struct Cyc___cycFILE *,struct _fat_ptr,struct _fat_ptr);
extern int Cyc_putc(int,struct Cyc___cycFILE *);
extern struct Cyc___cycFILE * Cyc_foutput;
extern struct _fat_ptr Cyc_infile;
extern int Cyc_ntokens;
extern struct _fat_ptr Cyc_rlhs;
extern struct _fat_ptr Cyc_rprec;
extern struct _fat_ptr Cyc_sprec;
extern struct _fat_ptr Cyc_sassoc;
extern int Cyc_error_token_number;
 struct Cyc_shifts_tag {
  struct Cyc_shifts_tag * next;
  short number;
  short nshifts;
  struct _fat_ptr shifts;
};
 struct Cyc_errs_tag {
  short nerrs;
  struct _fat_ptr errs;
};
extern int Cyc_nstates;
extern struct _fat_ptr Cyc_tags;
extern int Cyc_tokensetsize;
extern struct _fat_ptr Cyc_consistent;
extern struct _fat_ptr Cyc_accessing_symbol;
extern struct _fat_ptr Cyc_shift_table;
extern struct _fat_ptr Cyc_LA;
extern struct _fat_ptr Cyc_LAruleno;
extern struct _fat_ptr Cyc_lookaheads;
extern int Cyc_verboseflag;
extern int Cyc_fixed_outfiles;
void Cyc_set_conflicts(int);
void Cyc_resolve_sr_conflict(int,int);
void Cyc_flush_shift(int,int);
void Cyc_log_resolution(int,int,int,struct _fat_ptr);
void Cyc_total_conflicts();
void Cyc_count_sr_conflicts(int);
void Cyc_count_rr_conflicts(int);
char Cyc_any_conflicts;
struct _fat_ptr Cyc_conflicts;
struct _fat_ptr Cyc_err_table;
int Cyc_expected_conflicts;
int Cyc_expected_rr_conflicts;
static struct _fat_ptr Cyc_shiftset;
static struct _fat_ptr Cyc_lookaheadset;
static int Cyc_src_total;
static int Cyc_rrc_total;
static int Cyc_src_count;
static int Cyc_rrc_count;
void Cyc_initialize_conflicts() {
  struct _fat_ptr _T0;
  int _T1;
  unsigned int _T2;
  char * _T3;
  unsigned int _T4;
  unsigned int _T5;
  struct _fat_ptr _T6;
  int _T7;
  unsigned int * _T8;
  unsigned int _T9;
  unsigned int _TA;
  struct _fat_ptr _TB;
  int _TC;
  unsigned int * _TD;
  unsigned int _TE;
  unsigned int _TF;
  struct _fat_ptr _T10;
  int _T11;
  struct Cyc_errs_tag * * _T12;
  unsigned int _T13;
  unsigned int _T14;
  register int i;
  _T1 = Cyc_nstates;
  _T2 = (unsigned int)_T1;
  { unsigned int _T15 = _T2 + 1U;
    _T4 = _check_times(_T15,sizeof(char));
    { char * _T16 = _cycalloc_atomic(_T4);
      { unsigned int _T17 = _T15;
	unsigned int _new2_cyclone;
	_new2_cyclone = 0;
	_TL3: if (_new2_cyclone < _T17) { goto _TL1;
	}else { goto _TL2;
	}
	_TL1: _T5 = _new2_cyclone;
	_T16[_T5] = '\000';
	_new2_cyclone = _new2_cyclone + 1;
	goto _TL3;
	_TL2: _T16[_T17] = 0;
      }_T3 = (char *)_T16;
    }_T0 = _tag_fat(_T3,sizeof(char),_T15);
  }Cyc_conflicts = _T0;
  _T7 = Cyc_tokensetsize;
  { unsigned int _T15 = (unsigned int)_T7;
    _T9 = _check_times(_T15,sizeof(unsigned int));
    { unsigned int * _T16 = _cycalloc_atomic(_T9);
      { unsigned int _T17 = _T15;
	unsigned int _new2_cyclone;
	_new2_cyclone = 0;
	_TL7: if (_new2_cyclone < _T17) { goto _TL5;
	}else { goto _TL6;
	}
	_TL5: _TA = _new2_cyclone;
	_T16[_TA] = 0U;
	_new2_cyclone = _new2_cyclone + 1;
	goto _TL7;
	_TL6: ;
      }_T8 = (unsigned int *)_T16;
    }_T6 = _tag_fat(_T8,sizeof(unsigned int),_T15);
  }Cyc_shiftset = _T6;
  _TC = Cyc_tokensetsize;
  { unsigned int _T15 = (unsigned int)_TC;
    _TE = _check_times(_T15,sizeof(unsigned int));
    { unsigned int * _T16 = _cycalloc_atomic(_TE);
      { unsigned int _T17 = _T15;
	unsigned int _new2_cyclone;
	_new2_cyclone = 0;
	_TLB: if (_new2_cyclone < _T17) { goto _TL9;
	}else { goto _TLA;
	}
	_TL9: _TF = _new2_cyclone;
	_T16[_TF] = 0U;
	_new2_cyclone = _new2_cyclone + 1;
	goto _TLB;
	_TLA: ;
      }_TD = (unsigned int *)_T16;
    }_TB = _tag_fat(_TD,sizeof(unsigned int),_T15);
  }Cyc_lookaheadset = _TB;
  _T11 = Cyc_nstates;
  { unsigned int _T15 = (unsigned int)_T11;
    _T13 = _check_times(_T15,sizeof(struct Cyc_errs_tag *));
    { struct Cyc_errs_tag * * _T16 = _cycalloc(_T13);
      { unsigned int _T17 = _T15;
	unsigned int _new2p_cyclone;
	_new2p_cyclone = 0;
	_TLF: if (_new2p_cyclone < _T17) { goto _TLD;
	}else { goto _TLE;
	}
	_TLD: _T14 = _new2p_cyclone;
	_T16[_T14] = 0;
	_new2p_cyclone = _new2p_cyclone + 1;
	goto _TLF;
	_TLE: ;
      }_T12 = (struct Cyc_errs_tag * *)_T16;
    }_T10 = _tag_fat(_T12,sizeof(struct Cyc_errs_tag *),_T15);
  }Cyc_err_table = _T10;
  Cyc_any_conflicts = '\000';
  i = 0;
  _TL13: if (i < Cyc_nstates) { goto _TL11;
  }else { goto _TL12;
  }
  _TL11: Cyc_set_conflicts(i);
  i = i + 1;
  goto _TL13;
  _TL12: ;
}
void Cyc_set_conflicts(int state) {
  struct _fat_ptr _T0;
  int _T1;
  unsigned char * _T2;
  char * _T3;
  char _T4;
  int _T5;
  struct _fat_ptr _T6;
  int _T7;
  unsigned char * _T8;
  unsigned int * _T9;
  struct _fat_ptr _TA;
  int _TB;
  unsigned char * _TC;
  struct Cyc_shifts_tag * * _TD;
  struct Cyc_shifts_tag * _TE;
  unsigned int _TF;
  struct Cyc_shifts_tag * _T10;
  short _T11;
  struct _fat_ptr _T12;
  struct Cyc_shifts_tag * _T13;
  struct _fat_ptr _T14;
  int _T15;
  unsigned char * _T16;
  short * _T17;
  short _T18;
  int _T19;
  unsigned char * _T1A;
  short * _T1B;
  short _T1C;
  struct _fat_ptr _T1D;
  int _T1E;
  unsigned char * _T1F;
  unsigned int * _T20;
  int _T21;
  unsigned int _T22;
  struct _fat_ptr _T23;
  int _T24;
  unsigned char * _T25;
  short * _T26;
  short _T27;
  struct _fat_ptr _T28;
  int _T29;
  struct _fat_ptr _T2A;
  unsigned char * _T2B;
  short * _T2C;
  int _T2D;
  short _T2E;
  struct _fat_ptr _T2F;
  struct _fat_ptr _T30;
  int _T31;
  unsigned char * _T32;
  short * _T33;
  short _T34;
  int _T35;
  unsigned char * _T36;
  short * _T37;
  short _T38;
  int _T39;
  struct _fat_ptr _T3A;
  int _T3B;
  struct _fat_ptr _T3C;
  unsigned char * _T3D;
  unsigned int * _T3E;
  struct _fat_ptr _T3F;
  unsigned char * _T40;
  unsigned int * _T41;
  struct _fat_ptr * _T42;
  struct _fat_ptr _T43;
  unsigned char * _T44;
  unsigned int * _T45;
  unsigned int _T46;
  struct _fat_ptr * _T47;
  struct _fat_ptr _T48;
  unsigned char * _T49;
  unsigned int * _T4A;
  unsigned int _T4B;
  unsigned int _T4C;
  int _T4D;
  struct _fat_ptr _T4E;
  unsigned char * _T4F;
  short * _T50;
  int _T51;
  short _T52;
  struct _fat_ptr _T53;
  int _T54;
  struct _fat_ptr _T55;
  unsigned char * _T56;
  unsigned int * _T57;
  struct _fat_ptr _T58;
  unsigned char * _T59;
  unsigned int * _T5A;
  struct _fat_ptr * _T5B;
  struct _fat_ptr _T5C;
  unsigned char * _T5D;
  unsigned int * _T5E;
  unsigned int _T5F;
  struct _fat_ptr * _T60;
  struct _fat_ptr _T61;
  unsigned char * _T62;
  unsigned int * _T63;
  unsigned int _T64;
  unsigned int _T65;
  int _T66;
  struct _fat_ptr _T67;
  int _T68;
  unsigned char * _T69;
  char * _T6A;
  unsigned int _T6B;
  unsigned char * _T6C;
  char * _T6D;
  struct _fat_ptr _T6E;
  unsigned char * _T6F;
  unsigned int * _T70;
  struct _fat_ptr _T71;
  unsigned char * _T72;
  unsigned int * _T73;
  struct _fat_ptr * _T74;
  struct _fat_ptr _T75;
  unsigned char * _T76;
  unsigned int * _T77;
  struct _fat_ptr * _T78;
  struct _fat_ptr _T79;
  unsigned char * _T7A;
  unsigned int * _T7B;
  unsigned int _T7C;
  register int i;
  register int k;
  register struct Cyc_shifts_tag * shiftp;
  struct _fat_ptr fp2;
  struct _fat_ptr fp3;
  struct _fat_ptr fp4;
  struct _fat_ptr fp1;
  register int symbol;
  _T0 = Cyc_consistent;
  _T1 = state;
  _T2 = _check_fat_subscript(_T0,sizeof(char),_T1);
  _T3 = (char *)_T2;
  _T4 = *_T3;
  _T5 = (int)_T4;
  if (! _T5) { goto _TL14;
  }
  return;
  _TL14: i = 0;
  _TL19: if (i < Cyc_tokensetsize) { goto _TL17;
  }else { goto _TL18;
  }
  _TL17: _T6 = Cyc_lookaheadset;
  _T7 = i;
  _T8 = _check_fat_subscript(_T6,sizeof(unsigned int),_T7);
  _T9 = (unsigned int *)_T8;
  *_T9 = 0U;
  i = i + 1;
  goto _TL19;
  _TL18: _TA = Cyc_shift_table;
  _TB = state;
  _TC = _check_fat_subscript(_TA,sizeof(struct Cyc_shifts_tag *),_TB);
  _TD = (struct Cyc_shifts_tag * *)_TC;
  shiftp = *_TD;
  _TE = shiftp;
  _TF = (unsigned int)_TE;
  if (! _TF) { goto _TL1A;
  }
  _T10 = shiftp;
  _T11 = _T10->nshifts;
  k = (int)_T11;
  i = 0;
  _TL1F: if (i < k) { goto _TL1D;
  }else { goto _TL1E;
  }
  _TL1D: _T12 = Cyc_accessing_symbol;
  _T13 = shiftp;
  _T14 = _T13->shifts;
  _T15 = i;
  _T16 = _check_fat_subscript(_T14,sizeof(short),_T15);
  _T17 = (short *)_T16;
  _T18 = *_T17;
  _T19 = (int)_T18;
  _T1A = _check_fat_subscript(_T12,sizeof(short),_T19);
  _T1B = (short *)_T1A;
  _T1C = *_T1B;
  symbol = (int)_T1C;
  if (symbol < Cyc_ntokens) { goto _TL20;
  }
  goto _TL1E;
  _TL20: _T1D = Cyc_lookaheadset;
  _T1E = symbol / 32;
  _T1F = _check_fat_subscript(_T1D,sizeof(unsigned int),_T1E);
  _T20 = (unsigned int *)_T1F;
  _T21 = symbol % 32;
  _T22 = 1U << _T21;
  *_T20 = *_T20 | _T22;
  i = i + 1;
  goto _TL1F;
  _TL1E: goto _TL1B;
  _TL1A: _TL1B: _T23 = Cyc_lookaheads;
  _T24 = state + 1;
  _T25 = _check_fat_subscript(_T23,sizeof(short),_T24);
  _T26 = (short *)_T25;
  _T27 = *_T26;
  k = (int)_T27;
  _T28 = Cyc_lookaheadset;
  _T29 = Cyc_tokensetsize;
  fp4 = _fat_ptr_plus(_T28,sizeof(unsigned int),_T29);
  _T2A = Cyc_lookaheads;
  _T2B = _T2A.curr;
  _T2C = (short *)_T2B;
  _T2D = state;
  _T2E = _T2C[_T2D];
  i = (int)_T2E;
  _TL25: if (i < k) { goto _TL23;
  }else { goto _TL24;
  }
  _TL23: _T2F = Cyc_rprec;
  _T30 = Cyc_LAruleno;
  _T31 = i;
  _T32 = _check_fat_subscript(_T30,sizeof(short),_T31);
  _T33 = (short *)_T32;
  _T34 = *_T33;
  _T35 = (int)_T34;
  _T36 = _check_fat_subscript(_T2F,sizeof(short),_T35);
  _T37 = (short *)_T36;
  _T38 = *_T37;
  _T39 = (int)_T38;
  if (! _T39) { goto _TL26;
  }
  _T3A = Cyc_LA;
  _T3B = i * Cyc_tokensetsize;
  fp1 = _fat_ptr_plus(_T3A,sizeof(unsigned int),_T3B);
  fp2 = fp1;
  fp3 = Cyc_lookaheadset;
  _TL28: _T3C = fp3;
  _T3D = _T3C.curr;
  _T3E = (unsigned int *)_T3D;
  _T3F = fp4;
  _T40 = _T3F.curr;
  _T41 = (unsigned int *)_T40;
  if (_T3E < _T41) { goto _TL29;
  }else { goto _TL2A;
  }
  _TL29: _T42 = &fp2;
  _T43 = _fat_ptr_inplace_plus_post(_T42,sizeof(unsigned int),1);
  _T44 = _check_fat_subscript(_T43,sizeof(unsigned int),0U);
  _T45 = (unsigned int *)_T44;
  _T46 = *_T45;
  _T47 = &fp3;
  _T48 = _fat_ptr_inplace_plus_post(_T47,sizeof(unsigned int),1);
  _T49 = _check_fat_subscript(_T48,sizeof(unsigned int),0U);
  _T4A = (unsigned int *)_T49;
  _T4B = *_T4A;
  _T4C = _T46 & _T4B;
  _T4D = (int)_T4C;
  if (! _T4D) { goto _TL2B;
  }
  Cyc_resolve_sr_conflict(state,i);
  goto _TL2A;
  _TL2B: goto _TL28;
  _TL2A: goto _TL27;
  _TL26: _TL27: i = i + 1;
  goto _TL25;
  _TL24: _T4E = Cyc_lookaheads;
  _T4F = _T4E.curr;
  _T50 = (short *)_T4F;
  _T51 = state;
  _T52 = _T50[_T51];
  i = (int)_T52;
  _TL30: if (i < k) { goto _TL2E;
  }else { goto _TL2F;
  }
  _TL2E: _T53 = Cyc_LA;
  _T54 = i * Cyc_tokensetsize;
  fp1 = _fat_ptr_plus(_T53,sizeof(unsigned int),_T54);
  fp2 = fp1;
  fp3 = Cyc_lookaheadset;
  _TL31: _T55 = fp3;
  _T56 = _T55.curr;
  _T57 = (unsigned int *)_T56;
  _T58 = fp4;
  _T59 = _T58.curr;
  _T5A = (unsigned int *)_T59;
  if (_T57 < _T5A) { goto _TL32;
  }else { goto _TL33;
  }
  _TL32: _T5B = &fp2;
  _T5C = _fat_ptr_inplace_plus_post(_T5B,sizeof(unsigned int),1);
  _T5D = _check_fat_subscript(_T5C,sizeof(unsigned int),0U);
  _T5E = (unsigned int *)_T5D;
  _T5F = *_T5E;
  _T60 = &fp3;
  _T61 = _fat_ptr_inplace_plus_post(_T60,sizeof(unsigned int),1);
  _T62 = _check_fat_subscript(_T61,sizeof(unsigned int),0U);
  _T63 = (unsigned int *)_T62;
  _T64 = *_T63;
  _T65 = _T5F & _T64;
  _T66 = (int)_T65;
  if (! _T66) { goto _TL34;
  }
  _T67 = Cyc_conflicts;
  _T68 = state;
  { struct _fat_ptr _T7D = _fat_ptr_plus(_T67,sizeof(char),_T68);
    _T69 = _check_fat_subscript(_T7D,sizeof(char),0U);
    _T6A = (char *)_T69;
    { char _T7E = *_T6A;
      char _T7F = '\001';
      _T6B = _get_fat_size(_T7D,sizeof(char));
      if (_T6B != 1U) { goto _TL36;
      }
      if (_T7E != 0) { goto _TL36;
      }
      if (_T7F == 0) { goto _TL36;
      }
      _throw_arraybounds();
      goto _TL37;
      _TL36: _TL37: _T6C = _T7D.curr;
      _T6D = (char *)_T6C;
      *_T6D = _T7F;
    }
  }Cyc_any_conflicts = '\001';
  goto _TL35;
  _TL34: _TL35: goto _TL31;
  _TL33: fp2 = fp1;
  fp3 = Cyc_lookaheadset;
  _TL38: _T6E = fp3;
  _T6F = _T6E.curr;
  _T70 = (unsigned int *)_T6F;
  _T71 = fp4;
  _T72 = _T71.curr;
  _T73 = (unsigned int *)_T72;
  if (_T70 < _T73) { goto _TL39;
  }else { goto _TL3A;
  }
  _TL39: _T74 = &fp3;
  _T75 = _fat_ptr_inplace_plus_post(_T74,sizeof(unsigned int),1);
  _T76 = _check_fat_subscript(_T75,sizeof(unsigned int),0U);
  _T77 = (unsigned int *)_T76;
  _T78 = &fp2;
  _T79 = _fat_ptr_inplace_plus_post(_T78,sizeof(unsigned int),1);
  _T7A = _check_fat_subscript(_T79,sizeof(unsigned int),0U);
  _T7B = (unsigned int *)_T7A;
  _T7C = *_T7B;
  *_T77 = *_T77 | _T7C;
  goto _TL38;
  _TL3A: i = i + 1;
  goto _TL30;
  _TL2F: ;
}
void Cyc_resolve_sr_conflict(int state,int lookaheadnum) {
  struct Cyc_errs_tag * _T0;
  struct Cyc_errs_tag * _T1;
  struct Cyc_errs_tag * _T2;
  struct _fat_ptr _T3;
  int _T4;
  short * _T5;
  unsigned int _T6;
  unsigned int _T7;
  struct Cyc_errs_tag * _T8;
  struct _fat_ptr _T9;
  struct _fat_ptr _TA;
  int _TB;
  unsigned char * _TC;
  short * _TD;
  short _TE;
  int _TF;
  unsigned char * _T10;
  short * _T11;
  short _T12;
  struct _fat_ptr _T13;
  int _T14;
  unsigned int _T15;
  struct _fat_ptr _T16;
  unsigned char * _T17;
  unsigned int * _T18;
  unsigned int _T19;
  unsigned int _T1A;
  struct _fat_ptr _T1B;
  unsigned char * _T1C;
  unsigned int * _T1D;
  unsigned int _T1E;
  unsigned int _T1F;
  int _T20;
  struct _fat_ptr _T21;
  int _T22;
  unsigned char * _T23;
  short * _T24;
  short _T25;
  int _T26;
  struct _fat_ptr _T27;
  unsigned char * _T28;
  short * _T29;
  int _T2A;
  short _T2B;
  int _T2C;
  int _T2D;
  int _T2E;
  int _T2F;
  int _T30;
  int _T31;
  struct _fat_ptr _T32;
  struct _fat_ptr _T33;
  unsigned char * _T34;
  unsigned int * _T35;
  unsigned int _T36;
  struct _fat_ptr _T37;
  unsigned char * _T38;
  short * _T39;
  int _T3A;
  short _T3B;
  int _T3C;
  int _T3D;
  int _T3E;
  int _T3F;
  int _T40;
  int _T41;
  struct _fat_ptr _T42;
  struct _fat_ptr _T43;
  unsigned char * _T44;
  unsigned int * _T45;
  unsigned int _T46;
  struct _fat_ptr _T47;
  int _T48;
  unsigned char * _T49;
  short * _T4A;
  int _T4B;
  int _T4C;
  int _T4D;
  int _T4E;
  int _T4F;
  struct _fat_ptr _T50;
  int _T51;
  int _T52;
  int _T53;
  int _T54;
  struct _fat_ptr _T55;
  int _T56;
  int _T57;
  int _T58;
  int _T59;
  struct _fat_ptr _T5A;
  struct _fat_ptr _T5B;
  int _T5C;
  unsigned char * _T5D;
  short * _T5E;
  short _T5F;
  int _T60;
  struct _fat_ptr _T61;
  unsigned char * _T62;
  unsigned int * _T63;
  unsigned int _T64;
  struct _fat_ptr _T65;
  int _T66;
  unsigned char * _T67;
  short * _T68;
  short _T69;
  int _T6A;
  struct _fat_ptr _T6B;
  unsigned char * _T6C;
  unsigned int * _T6D;
  unsigned int _T6E;
  struct _fat_ptr _T6F;
  unsigned char * _T70;
  short * _T71;
  int _T72;
  short _T73;
  int _T74;
  struct _fat_ptr * _T75;
  struct _fat_ptr _T76;
  unsigned char * _T77;
  short * _T78;
  int _T79;
  struct _fat_ptr * _T7A;
  struct _fat_ptr * _T7B;
  struct Cyc_errs_tag * _T7C;
  struct _fat_ptr _T7D;
  unsigned char * _T7E;
  struct Cyc_errs_tag * _T7F;
  struct _fat_ptr _T80;
  unsigned char * _T81;
  int _T82;
  int _T83;
  struct Cyc_errs_tag * _T84;
  short _T85;
  int _T86;
  struct _fat_ptr _T87;
  struct Cyc_errs_tag * _T88;
  short _T89;
  short * _T8A;
  unsigned int _T8B;
  unsigned int _T8C;
  struct _fat_ptr _T8D;
  unsigned int _T8E;
  int _T8F;
  unsigned char * _T90;
  short * _T91;
  struct Cyc_errs_tag * _T92;
  struct _fat_ptr _T93;
  unsigned int _T94;
  int _T95;
  unsigned char * _T96;
  short * _T97;
  struct _fat_ptr _T98;
  int _T99;
  unsigned char * _T9A;
  struct Cyc_errs_tag * * _T9B;
  struct Cyc_errs_tag * _T9C;
  struct Cyc_errs_tag * _T9D;
  struct _fat_ptr _T9E;
  int _T9F;
  unsigned char * _TA0;
  struct Cyc_errs_tag * * _TA1;
  register int i;
  register unsigned int mask;
  struct _fat_ptr fp1;
  struct _fat_ptr fp2;
  register int redprec;
  struct Cyc_errs_tag * errp;
  errp = _cycalloc(sizeof(struct Cyc_errs_tag));
  _T0 = errp;
  _T0->nerrs = 0;
  _T1 = errp;
  _T1->errs = _tag_fat(0,0,0);
  _T2 = errp;
  _T4 = Cyc_ntokens + 1;
  { unsigned int _TA2 = (unsigned int)_T4;
    _T6 = _check_times(_TA2,sizeof(short));
    { short * _TA3 = _cycalloc_atomic(_T6);
      { unsigned int _TA4 = _TA2;
	unsigned int _new2_cyclone;
	_new2_cyclone = 0;
	_TL3E: if (_new2_cyclone < _TA4) { goto _TL3C;
	}else { goto _TL3D;
	}
	_TL3C: _T7 = _new2_cyclone;
	_TA3[_T7] = 0;
	_new2_cyclone = _new2_cyclone + 1;
	goto _TL3E;
	_TL3D: ;
      }_T5 = (short *)_TA3;
    }_T3 = _tag_fat(_T5,sizeof(short),_TA2);
  }_T2->errs = _T3;
  _T8 = errp;
  { struct _fat_ptr errtokens = _T8->errs;
    _T9 = Cyc_rprec;
    _TA = Cyc_LAruleno;
    _TB = lookaheadnum;
    _TC = _check_fat_subscript(_TA,sizeof(short),_TB);
    _TD = (short *)_TC;
    _TE = *_TD;
    _TF = (int)_TE;
    _T10 = _check_fat_subscript(_T9,sizeof(short),_TF);
    _T11 = (short *)_T10;
    _T12 = *_T11;
    redprec = (int)_T12;
    mask = 1U;
    _T13 = Cyc_LA;
    _T14 = lookaheadnum * Cyc_tokensetsize;
    fp1 = _fat_ptr_plus(_T13,sizeof(unsigned int),_T14);
    fp2 = Cyc_lookaheadset;
    i = 0;
    _TL42: if (i < Cyc_ntokens) { goto _TL40;
    }else { goto _TL41;
    }
    _TL40: _T15 = mask;
    _T16 = fp2;
    _T17 = _check_fat_subscript(_T16,sizeof(unsigned int),0U);
    _T18 = (unsigned int *)_T17;
    _T19 = *_T18;
    _T1A = _T15 & _T19;
    _T1B = fp1;
    _T1C = _check_fat_subscript(_T1B,sizeof(unsigned int),0U);
    _T1D = (unsigned int *)_T1C;
    _T1E = *_T1D;
    _T1F = _T1A & _T1E;
    _T20 = (int)_T1F;
    if (! _T20) { goto _TL43;
    }
    _T21 = Cyc_sprec;
    _T22 = i;
    _T23 = _check_fat_subscript(_T21,sizeof(short),_T22);
    _T24 = (short *)_T23;
    _T25 = *_T24;
    _T26 = (int)_T25;
    if (! _T26) { goto _TL43;
    }
    _T27 = Cyc_sprec;
    _T28 = _T27.curr;
    _T29 = (short *)_T28;
    _T2A = i;
    _T2B = _T29[_T2A];
    _T2C = (int)_T2B;
    _T2D = redprec;
    if (_T2C >= _T2D) { goto _TL45;
    }
    _T2E = Cyc_verboseflag;
    if (! _T2E) { goto _TL47;
    }
    _T2F = state;
    _T30 = lookaheadnum;
    _T31 = i;
    _T32 = _tag_fat("reduce",sizeof(char),7U);
    Cyc_log_resolution(_T2F,_T30,_T31,_T32);
    goto _TL48;
    _TL47: _TL48: _T33 = fp2;
    _T34 = _T33.curr;
    _T35 = (unsigned int *)_T34;
    _T36 = ~ mask;
    *_T35 = *_T35 & _T36;
    Cyc_flush_shift(state,i);
    goto _TL46;
    _TL45: _T37 = Cyc_sprec;
    _T38 = _T37.curr;
    _T39 = (short *)_T38;
    _T3A = i;
    _T3B = _T39[_T3A];
    _T3C = (int)_T3B;
    _T3D = redprec;
    if (_T3C <= _T3D) { goto _TL49;
    }
    _T3E = Cyc_verboseflag;
    if (! _T3E) { goto _TL4B;
    }
    _T3F = state;
    _T40 = lookaheadnum;
    _T41 = i;
    _T42 = _tag_fat("shift",sizeof(char),6U);
    Cyc_log_resolution(_T3F,_T40,_T41,_T42);
    goto _TL4C;
    _TL4B: _TL4C: _T43 = fp1;
    _T44 = _T43.curr;
    _T45 = (unsigned int *)_T44;
    _T46 = ~ mask;
    *_T45 = *_T45 & _T46;
    goto _TL4A;
    _TL49: _T47 = Cyc_sassoc;
    _T48 = i;
    _T49 = _check_fat_subscript(_T47,sizeof(short),_T48);
    _T4A = (short *)_T49;
    { short _TA2 = *_T4A;
      _T4B = (int)_TA2;
      switch (_T4B) {
      case 1: 
	_T4C = Cyc_verboseflag;
	if (! _T4C) { goto _TL4E;
	}
	_T4D = state;
	_T4E = lookaheadnum;
	_T4F = i;
	_T50 = _tag_fat("shift",sizeof(char),6U);
	Cyc_log_resolution(_T4D,_T4E,_T4F,_T50);
	goto _TL4F;
	_TL4E: _TL4F: goto _LL0;
      case 2: 
	_T51 = Cyc_verboseflag;
	if (! _T51) { goto _TL50;
	}
	_T52 = state;
	_T53 = lookaheadnum;
	_T54 = i;
	_T55 = _tag_fat("reduce",sizeof(char),7U);
	Cyc_log_resolution(_T52,_T53,_T54,_T55);
	goto _TL51;
	_TL50: _TL51: goto _LL0;
      case 3: 
	_T56 = Cyc_verboseflag;
	if (! _T56) { goto _TL52;
	}
	_T57 = state;
	_T58 = lookaheadnum;
	_T59 = i;
	_T5A = _tag_fat("an error",sizeof(char),9U);
	Cyc_log_resolution(_T57,_T58,_T59,_T5A);
	goto _TL53;
	_TL52: _TL53: goto _LL0;
      default: 
	goto _LL0;
      }
      _LL0: ;
    }_T5B = Cyc_sassoc;
    _T5C = i;
    _T5D = _check_fat_subscript(_T5B,sizeof(short),_T5C);
    _T5E = (short *)_T5D;
    _T5F = *_T5E;
    _T60 = (int)_T5F;
    if (_T60 == 1) { goto _TL54;
    }
    _T61 = fp2;
    _T62 = _T61.curr;
    _T63 = (unsigned int *)_T62;
    _T64 = ~ mask;
    *_T63 = *_T63 & _T64;
    Cyc_flush_shift(state,i);
    goto _TL55;
    _TL54: _TL55: _T65 = Cyc_sassoc;
    _T66 = i;
    _T67 = _check_fat_subscript(_T65,sizeof(short),_T66);
    _T68 = (short *)_T67;
    _T69 = *_T68;
    _T6A = (int)_T69;
    if (_T6A == 2) { goto _TL56;
    }
    _T6B = fp1;
    _T6C = _T6B.curr;
    _T6D = (unsigned int *)_T6C;
    _T6E = ~ mask;
    *_T6D = *_T6D & _T6E;
    goto _TL57;
    _TL56: _TL57: _T6F = Cyc_sassoc;
    _T70 = _T6F.curr;
    _T71 = (short *)_T70;
    _T72 = i;
    _T73 = _T71[_T72];
    _T74 = (int)_T73;
    if (_T74 != 3) { goto _TL58;
    }
    _T75 = &errtokens;
    _T76 = _fat_ptr_inplace_plus_post(_T75,sizeof(short),1);
    _T77 = _check_fat_subscript(_T76,sizeof(short),0U);
    _T78 = (short *)_T77;
    _T79 = i;
    *_T78 = (short)_T79;
    goto _TL59;
    _TL58: _TL59: _TL4A: _TL46: goto _TL44;
    _TL43: _TL44: mask = mask << 1U;
    if (mask != 0U) { goto _TL5A;
    }
    mask = 1U;
    _T7A = &fp2;
    _fat_ptr_inplace_plus(_T7A,sizeof(unsigned int),1);
    _T7B = &fp1;
    _fat_ptr_inplace_plus(_T7B,sizeof(unsigned int),1);
    goto _TL5B;
    _TL5A: _TL5B: i = i + 1;
    goto _TL42;
    _TL41: _T7C = errp;
    _T7D = errtokens;
    _T7E = _T7D.curr;
    _T7F = errp;
    _T80 = _T7F->errs;
    _T81 = _T80.curr;
    _T82 = _T7E - _T81;
    _T83 = _T82 / sizeof(short);
    _T7C->nerrs = (short)_T83;
    _T84 = errp;
    _T85 = _T84->nerrs;
    _T86 = (int)_T85;
    if (! _T86) { goto _TL5C;
    }
    _T88 = errp;
    _T89 = _T88->nerrs;
    { unsigned int _TA2 = (unsigned int)_T89;
      _T8B = _check_times(_TA2,sizeof(short));
      { short * _TA3 = _cycalloc_atomic(_T8B);
	{ unsigned int _TA4 = _TA2;
	  unsigned int _temp_;
	  _temp_ = 0;
	  _TL61: if (_temp_ < _TA4) { goto _TL5F;
	  }else { goto _TL60;
	  }
	  _TL5F: _T8C = _temp_;
	  _T8D = errtokens;
	  _T8E = _temp_;
	  _T8F = (int)_T8E;
	  _T90 = _check_fat_subscript(_T8D,sizeof(short),_T8F);
	  _T91 = (short *)_T90;
	  _T92 = errp;
	  _T93 = _T92->errs;
	  _T94 = _temp_;
	  _T95 = (int)_T94;
	  _T96 = _check_fat_subscript(_T93,sizeof(short),_T95);
	  _T97 = (short *)_T96;
	  *_T91 = *_T97;
	  _TA3[_T8C] = *_T91;
	  _temp_ = _temp_ + 1;
	  goto _TL61;
	  _TL60: ;
	}_T8A = (short *)_TA3;
      }_T87 = _tag_fat(_T8A,sizeof(short),_TA2);
    }errtokens = _T87;
    _T98 = Cyc_err_table;
    _T99 = state;
    _T9A = _check_fat_subscript(_T98,sizeof(struct Cyc_errs_tag *),_T99);
    _T9B = (struct Cyc_errs_tag * *)_T9A;
    { struct Cyc_errs_tag * _TA2 = _cycalloc(sizeof(struct Cyc_errs_tag));
      _T9D = errp;
      _TA2->nerrs = _T9D->nerrs;
      _TA2->errs = errtokens;
      _T9C = (struct Cyc_errs_tag *)_TA2;
    }*_T9B = _T9C;
    goto _TL5D;
    _TL5C: _T9E = Cyc_err_table;
    _T9F = state;
    _TA0 = _check_fat_subscript(_T9E,sizeof(struct Cyc_errs_tag *),_T9F);
    _TA1 = (struct Cyc_errs_tag * *)_TA0;
    *_TA1 = 0;
    _TL5D: errp = 0;
  }
}
void Cyc_flush_shift(int state,int token) {
  struct _fat_ptr _T0;
  int _T1;
  unsigned char * _T2;
  struct Cyc_shifts_tag * * _T3;
  struct Cyc_shifts_tag * _T4;
  unsigned int _T5;
  struct Cyc_shifts_tag * _T6;
  short _T7;
  struct Cyc_shifts_tag * _T8;
  struct _fat_ptr _T9;
  int _TA;
  unsigned char * _TB;
  short * _TC;
  short _TD;
  int _TE;
  int _TF;
  struct _fat_ptr _T10;
  struct Cyc_shifts_tag * _T11;
  struct _fat_ptr _T12;
  unsigned char * _T13;
  short * _T14;
  int _T15;
  short _T16;
  int _T17;
  unsigned char * _T18;
  short * _T19;
  short _T1A;
  int _T1B;
  struct Cyc_shifts_tag * _T1C;
  struct _fat_ptr _T1D;
  unsigned char * _T1E;
  short * _T1F;
  int _T20;
  register struct Cyc_shifts_tag * shiftp;
  register int k;
  register int i;
  _T0 = Cyc_shift_table;
  _T1 = state;
  _T2 = _check_fat_subscript(_T0,sizeof(struct Cyc_shifts_tag *),_T1);
  _T3 = (struct Cyc_shifts_tag * *)_T2;
  shiftp = *_T3;
  _T4 = shiftp;
  _T5 = (unsigned int)_T4;
  if (! _T5) { goto _TL62;
  }
  _T6 = shiftp;
  _T7 = _T6->nshifts;
  k = (int)_T7;
  i = 0;
  _TL67: if (i < k) { goto _TL65;
  }else { goto _TL66;
  }
  _TL65: _T8 = shiftp;
  _T9 = _T8->shifts;
  _TA = i;
  _TB = _check_fat_subscript(_T9,sizeof(short),_TA);
  _TC = (short *)_TB;
  _TD = *_TC;
  _TE = (int)_TD;
  if (! _TE) { goto _TL68;
  }
  _TF = token;
  _T10 = Cyc_accessing_symbol;
  _T11 = shiftp;
  _T12 = _T11->shifts;
  _T13 = _T12.curr;
  _T14 = (short *)_T13;
  _T15 = i;
  _T16 = _T14[_T15];
  _T17 = (int)_T16;
  _T18 = _check_fat_subscript(_T10,sizeof(short),_T17);
  _T19 = (short *)_T18;
  _T1A = *_T19;
  _T1B = (int)_T1A;
  if (_TF != _T1B) { goto _TL68;
  }
  _T1C = shiftp;
  _T1D = _T1C->shifts;
  _T1E = _T1D.curr;
  _T1F = (short *)_T1E;
  _T20 = i;
  _T1F[_T20] = 0;
  goto _TL69;
  _TL68: _TL69: i = i + 1;
  goto _TL67;
  _TL66: goto _TL63;
  _TL62: _TL63: ;
}
void Cyc_log_resolution(int state,int LAno,int token,struct _fat_ptr resolution) {
  struct Cyc_Int_pa_PrintArg_struct _T0;
  int _T1;
  struct Cyc_Int_pa_PrintArg_struct _T2;
  struct _fat_ptr _T3;
  int _T4;
  unsigned char * _T5;
  short * _T6;
  short _T7;
  int _T8;
  struct Cyc_String_pa_PrintArg_struct _T9;
  struct _fat_ptr _TA;
  int _TB;
  unsigned char * _TC;
  struct _fat_ptr * _TD;
  struct _fat_ptr _TE;
  struct Cyc_String_pa_PrintArg_struct _TF;
  struct _fat_ptr _T10;
  struct Cyc___cycFILE * _T11;
  struct _fat_ptr _T12;
  struct _fat_ptr _T13;
  { struct Cyc_Int_pa_PrintArg_struct _T14;
    _T14.tag = 1;
    _T1 = state;
    _T14.f1 = (unsigned long)_T1;
    _T0 = _T14;
  }{ struct Cyc_Int_pa_PrintArg_struct _T14 = _T0;
    { struct Cyc_Int_pa_PrintArg_struct _T15;
      _T15.tag = 1;
      _T3 = Cyc_LAruleno;
      _T4 = LAno;
      _T5 = _check_fat_subscript(_T3,sizeof(short),_T4);
      _T6 = (short *)_T5;
      _T7 = *_T6;
      _T8 = (int)_T7;
      _T15.f1 = (unsigned long)_T8;
      _T2 = _T15;
    }{ struct Cyc_Int_pa_PrintArg_struct _T15 = _T2;
      { struct Cyc_String_pa_PrintArg_struct _T16;
	_T16.tag = 0;
	_TA = Cyc_tags;
	_TB = token;
	_TC = _check_fat_subscript(_TA,sizeof(struct _fat_ptr),_TB);
	_TD = (struct _fat_ptr *)_TC;
	_TE = *_TD;
	_T16.f1 = _TE;
	_T9 = _T16;
      }{ struct Cyc_String_pa_PrintArg_struct _T16 = _T9;
	{ struct Cyc_String_pa_PrintArg_struct _T17;
	  _T17.tag = 0;
	  _T10 = resolution;
	  _T17.f1 = _T10;
	  _TF = _T17;
	}{ struct Cyc_String_pa_PrintArg_struct _T17 = _TF;
	  void * _T18[4];
	  _T18[0] = &_T14;
	  _T18[1] = &_T15;
	  _T18[2] = &_T16;
	  _T18[3] = &_T17;
	  _T11 = _check_null(Cyc_foutput);
	  _T12 = _tag_fat("Conflict in state %d between rule %d and token %s resolved as %s.\n",
			  sizeof(char),67U);
	  _T13 = _tag_fat(_T18,sizeof(void *),4);
	  Cyc_fprintf(_T11,_T12,_T13);
	}
      }
    }
  }
}
void Cyc_conflict_log() {
  struct _fat_ptr _T0;
  int _T1;
  unsigned char * _T2;
  char * _T3;
  char _T4;
  int _T5;
  int _T6;
  int _T7;
  register int i;
  Cyc_src_total = 0;
  Cyc_rrc_total = 0;
  i = 0;
  _TL6D: if (i < Cyc_nstates) { goto _TL6B;
  }else { goto _TL6C;
  }
  _TL6B: _T0 = Cyc_conflicts;
  _T1 = i;
  _T2 = _check_fat_subscript(_T0,sizeof(char),_T1);
  _T3 = (char *)_T2;
  _T4 = *_T3;
  _T5 = (int)_T4;
  if (! _T5) { goto _TL6E;
  }
  Cyc_count_sr_conflicts(i);
  Cyc_count_rr_conflicts(i);
  _T6 = Cyc_src_count;
  Cyc_src_total = Cyc_src_total + _T6;
  _T7 = Cyc_rrc_count;
  Cyc_rrc_total = Cyc_rrc_total + _T7;
  goto _TL6F;
  _TL6E: _TL6F: i = i + 1;
  goto _TL6D;
  _TL6C: Cyc_total_conflicts();
}
void Cyc_verbose_conflict_log() {
  struct _fat_ptr _T0;
  int _T1;
  unsigned char * _T2;
  char * _T3;
  char _T4;
  int _T5;
  int _T6;
  int _T7;
  struct Cyc_Int_pa_PrintArg_struct _T8;
  int _T9;
  struct Cyc___cycFILE * _TA;
  struct _fat_ptr _TB;
  struct _fat_ptr _TC;
  struct Cyc___cycFILE * _TD;
  struct _fat_ptr _TE;
  struct _fat_ptr _TF;
  struct Cyc_Int_pa_PrintArg_struct _T10;
  int _T11;
  struct Cyc___cycFILE * _T12;
  struct _fat_ptr _T13;
  struct _fat_ptr _T14;
  struct Cyc___cycFILE * _T15;
  struct _fat_ptr _T16;
  struct _fat_ptr _T17;
  struct Cyc___cycFILE * _T18;
  struct _fat_ptr _T19;
  struct _fat_ptr _T1A;
  struct Cyc_Int_pa_PrintArg_struct _T1B;
  int _T1C;
  struct Cyc___cycFILE * _T1D;
  struct _fat_ptr _T1E;
  struct _fat_ptr _T1F;
  struct Cyc___cycFILE * _T20;
  struct Cyc___cycFILE * _T21;
  register int i;
  Cyc_src_total = 0;
  Cyc_rrc_total = 0;
  i = 0;
  _TL73: if (i < Cyc_nstates) { goto _TL71;
  }else { goto _TL72;
  }
  _TL71: _T0 = Cyc_conflicts;
  _T1 = i;
  _T2 = _check_fat_subscript(_T0,sizeof(char),_T1);
  _T3 = (char *)_T2;
  _T4 = *_T3;
  _T5 = (int)_T4;
  if (! _T5) { goto _TL74;
  }
  Cyc_count_sr_conflicts(i);
  Cyc_count_rr_conflicts(i);
  _T6 = Cyc_src_count;
  Cyc_src_total = Cyc_src_total + _T6;
  _T7 = Cyc_rrc_count;
  Cyc_rrc_total = Cyc_rrc_total + _T7;
  { struct Cyc_Int_pa_PrintArg_struct _T22;
    _T22.tag = 1;
    _T9 = i;
    _T22.f1 = (unsigned long)_T9;
    _T8 = _T22;
  }{ struct Cyc_Int_pa_PrintArg_struct _T22 = _T8;
    void * _T23[1];
    _T23[0] = &_T22;
    _TA = _check_null(Cyc_foutput);
    _TB = _tag_fat("State %d contains",sizeof(char),18U);
    _TC = _tag_fat(_T23,sizeof(void *),1);
    Cyc_fprintf(_TA,_TB,_TC);
  }if (Cyc_src_count != 1) { goto _TL76;
  }
  _TD = _check_null(Cyc_foutput);
  _TE = _tag_fat(" 1 shift/reduce conflict",sizeof(char),25U);
  _TF = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_TD,_TE,_TF);
  goto _TL77;
  _TL76: if (Cyc_src_count <= 1) { goto _TL78;
  }
  { struct Cyc_Int_pa_PrintArg_struct _T22;
    _T22.tag = 1;
    _T11 = Cyc_src_count;
    _T22.f1 = (unsigned long)_T11;
    _T10 = _T22;
  }{ struct Cyc_Int_pa_PrintArg_struct _T22 = _T10;
    void * _T23[1];
    _T23[0] = &_T22;
    _T12 = _check_null(Cyc_foutput);
    _T13 = _tag_fat(" %d shift/reduce conflicts",sizeof(char),27U);
    _T14 = _tag_fat(_T23,sizeof(void *),1);
    Cyc_fprintf(_T12,_T13,_T14);
  }goto _TL79;
  _TL78: _TL79: _TL77: if (Cyc_src_count <= 0) { goto _TL7A;
  }
  if (Cyc_rrc_count <= 0) { goto _TL7A;
  }
  _T15 = _check_null(Cyc_foutput);
  _T16 = _tag_fat(" and",sizeof(char),5U);
  _T17 = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_T15,_T16,_T17);
  goto _TL7B;
  _TL7A: _TL7B: if (Cyc_rrc_count != 1) { goto _TL7C;
  }
  _T18 = _check_null(Cyc_foutput);
  _T19 = _tag_fat(" 1 reduce/reduce conflict",sizeof(char),26U);
  _T1A = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_T18,_T19,_T1A);
  goto _TL7D;
  _TL7C: if (Cyc_rrc_count <= 1) { goto _TL7E;
  }
  { struct Cyc_Int_pa_PrintArg_struct _T22;
    _T22.tag = 1;
    _T1C = Cyc_rrc_count;
    _T22.f1 = (unsigned long)_T1C;
    _T1B = _T22;
  }{ struct Cyc_Int_pa_PrintArg_struct _T22 = _T1B;
    void * _T23[1];
    _T23[0] = &_T22;
    _T1D = _check_null(Cyc_foutput);
    _T1E = _tag_fat(" %d reduce/reduce conflicts",sizeof(char),28U);
    _T1F = _tag_fat(_T23,sizeof(void *),1);
    Cyc_fprintf(_T1D,_T1E,_T1F);
  }goto _TL7F;
  _TL7E: _TL7F: _TL7D: _T20 = _check_null(Cyc_foutput);
  Cyc_putc(46,_T20);
  _T21 = _check_null(Cyc_foutput);
  Cyc_putc(10,_T21);
  goto _TL75;
  _TL74: _TL75: i = i + 1;
  goto _TL73;
  _TL72: Cyc_total_conflicts();
}
void Cyc_total_conflicts() {
  int _T0;
  struct Cyc___cycFILE * _T1;
  struct _fat_ptr _T2;
  struct _fat_ptr _T3;
  struct Cyc_Int_pa_PrintArg_struct _T4;
  int _T5;
  struct Cyc___cycFILE * _T6;
  struct _fat_ptr _T7;
  struct _fat_ptr _T8;
  struct Cyc___cycFILE * _T9;
  struct _fat_ptr _TA;
  struct _fat_ptr _TB;
  struct Cyc_Int_pa_PrintArg_struct _TC;
  int _TD;
  struct Cyc___cycFILE * _TE;
  struct _fat_ptr _TF;
  struct _fat_ptr _T10;
  struct Cyc_String_pa_PrintArg_struct _T11;
  struct Cyc___cycFILE * _T12;
  struct _fat_ptr _T13;
  struct _fat_ptr _T14;
  struct Cyc___cycFILE * _T15;
  struct _fat_ptr _T16;
  struct _fat_ptr _T17;
  struct Cyc_Int_pa_PrintArg_struct _T18;
  int _T19;
  struct Cyc___cycFILE * _T1A;
  struct _fat_ptr _T1B;
  struct _fat_ptr _T1C;
  struct Cyc___cycFILE * _T1D;
  struct _fat_ptr _T1E;
  struct _fat_ptr _T1F;
  struct Cyc___cycFILE * _T20;
  struct _fat_ptr _T21;
  struct _fat_ptr _T22;
  struct Cyc_Int_pa_PrintArg_struct _T23;
  int _T24;
  struct Cyc___cycFILE * _T25;
  struct _fat_ptr _T26;
  struct _fat_ptr _T27;
  if (Cyc_src_total != Cyc_expected_conflicts) { goto _TL80;
  }
  if (Cyc_rrc_total != Cyc_expected_rr_conflicts) { goto _TL80;
  }
  return;
  _TL80: _T0 = Cyc_fixed_outfiles;
  if (! _T0) { goto _TL82;
  }
  _T1 = Cyc_stderr;
  _T2 = _tag_fat("conflicts: ",sizeof(char),12U);
  _T3 = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_T1,_T2,_T3);
  if (Cyc_src_total <= 0) { goto _TL84;
  }
  { struct Cyc_Int_pa_PrintArg_struct _T28;
    _T28.tag = 1;
    _T5 = Cyc_src_total;
    _T28.f1 = (unsigned long)_T5;
    _T4 = _T28;
  }{ struct Cyc_Int_pa_PrintArg_struct _T28 = _T4;
    void * _T29[1];
    _T29[0] = &_T28;
    _T6 = Cyc_stderr;
    _T7 = _tag_fat(" %d shift/reduce",sizeof(char),17U);
    _T8 = _tag_fat(_T29,sizeof(void *),1);
    Cyc_fprintf(_T6,_T7,_T8);
  }goto _TL85;
  _TL84: _TL85: if (Cyc_src_total <= 0) { goto _TL86;
  }
  if (Cyc_rrc_total <= 0) { goto _TL86;
  }
  _T9 = Cyc_stderr;
  _TA = _tag_fat(",",sizeof(char),2U);
  _TB = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_T9,_TA,_TB);
  goto _TL87;
  _TL86: _TL87: if (Cyc_rrc_total <= 0) { goto _TL88;
  }
  { struct Cyc_Int_pa_PrintArg_struct _T28;
    _T28.tag = 1;
    _TD = Cyc_rrc_total;
    _T28.f1 = (unsigned long)_TD;
    _TC = _T28;
  }{ struct Cyc_Int_pa_PrintArg_struct _T28 = _TC;
    void * _T29[1];
    _T29[0] = &_T28;
    _TE = Cyc_stderr;
    _TF = _tag_fat(" %d reduce/reduce",sizeof(char),18U);
    _T10 = _tag_fat(_T29,sizeof(void *),1);
    Cyc_fprintf(_TE,_TF,_T10);
  }goto _TL89;
  _TL88: _TL89: Cyc_putc(10,Cyc_stderr);
  goto _TL83;
  _TL82: { struct Cyc_String_pa_PrintArg_struct _T28;
    _T28.tag = 0;
    _T28.f1 = Cyc_infile;
    _T11 = _T28;
  }{ struct Cyc_String_pa_PrintArg_struct _T28 = _T11;
    void * _T29[1];
    _T29[0] = &_T28;
    _T12 = Cyc_stderr;
    _T13 = _tag_fat("%s contains",sizeof(char),12U);
    _T14 = _tag_fat(_T29,sizeof(void *),1);
    Cyc_fprintf(_T12,_T13,_T14);
  }if (Cyc_src_total != 1) { goto _TL8A;
  }
  _T15 = Cyc_stderr;
  _T16 = _tag_fat(" 1 shift/reduce conflict",sizeof(char),25U);
  _T17 = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_T15,_T16,_T17);
  goto _TL8B;
  _TL8A: if (Cyc_src_total <= 1) { goto _TL8C;
  }
  { struct Cyc_Int_pa_PrintArg_struct _T28;
    _T28.tag = 1;
    _T19 = Cyc_src_total;
    _T28.f1 = (unsigned long)_T19;
    _T18 = _T28;
  }{ struct Cyc_Int_pa_PrintArg_struct _T28 = _T18;
    void * _T29[1];
    _T29[0] = &_T28;
    _T1A = Cyc_stderr;
    _T1B = _tag_fat(" %d shift/reduce conflicts",sizeof(char),27U);
    _T1C = _tag_fat(_T29,sizeof(void *),1);
    Cyc_fprintf(_T1A,_T1B,_T1C);
  }goto _TL8D;
  _TL8C: _TL8D: _TL8B: if (Cyc_src_total <= 0) { goto _TL8E;
  }
  if (Cyc_rrc_total <= 0) { goto _TL8E;
  }
  _T1D = Cyc_stderr;
  _T1E = _tag_fat(" and",sizeof(char),5U);
  _T1F = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_T1D,_T1E,_T1F);
  goto _TL8F;
  _TL8E: _TL8F: if (Cyc_rrc_total != 1) { goto _TL90;
  }
  _T20 = Cyc_stderr;
  _T21 = _tag_fat(" 1 reduce/reduce conflict",sizeof(char),26U);
  _T22 = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_T20,_T21,_T22);
  goto _TL91;
  _TL90: if (Cyc_rrc_total <= 1) { goto _TL92;
  }
  { struct Cyc_Int_pa_PrintArg_struct _T28;
    _T28.tag = 1;
    _T24 = Cyc_rrc_total;
    _T28.f1 = (unsigned long)_T24;
    _T23 = _T28;
  }{ struct Cyc_Int_pa_PrintArg_struct _T28 = _T23;
    void * _T29[1];
    _T29[0] = &_T28;
    _T25 = Cyc_stderr;
    _T26 = _tag_fat(" %d reduce/reduce conflicts",sizeof(char),28U);
    _T27 = _tag_fat(_T29,sizeof(void *),1);
    Cyc_fprintf(_T25,_T26,_T27);
  }goto _TL93;
  _TL92: _TL93: _TL91: Cyc_putc(46,Cyc_stderr);
  Cyc_putc(10,Cyc_stderr);
  _TL83: ;
}
void Cyc_count_sr_conflicts(int state) {
  struct _fat_ptr _T0;
  int _T1;
  unsigned char * _T2;
  struct Cyc_shifts_tag * * _T3;
  struct Cyc_shifts_tag * _T4;
  unsigned int _T5;
  struct _fat_ptr _T6;
  int _T7;
  unsigned char * _T8;
  unsigned int * _T9;
  struct _fat_ptr _TA;
  int _TB;
  unsigned char * _TC;
  unsigned int * _TD;
  struct Cyc_shifts_tag * _TE;
  short _TF;
  struct Cyc_shifts_tag * _T10;
  struct _fat_ptr _T11;
  int _T12;
  unsigned char * _T13;
  short * _T14;
  short _T15;
  int _T16;
  struct _fat_ptr _T17;
  struct Cyc_shifts_tag * _T18;
  struct _fat_ptr _T19;
  unsigned char * _T1A;
  short * _T1B;
  int _T1C;
  short _T1D;
  int _T1E;
  unsigned char * _T1F;
  short * _T20;
  short _T21;
  struct _fat_ptr _T22;
  int _T23;
  unsigned char * _T24;
  unsigned int * _T25;
  int _T26;
  unsigned int _T27;
  struct _fat_ptr _T28;
  int _T29;
  unsigned char * _T2A;
  short * _T2B;
  short _T2C;
  struct _fat_ptr _T2D;
  int _T2E;
  struct _fat_ptr _T2F;
  unsigned char * _T30;
  short * _T31;
  int _T32;
  short _T33;
  struct _fat_ptr _T34;
  int _T35;
  struct _fat_ptr _T36;
  unsigned char * _T37;
  unsigned int * _T38;
  struct _fat_ptr _T39;
  unsigned char * _T3A;
  unsigned int * _T3B;
  struct _fat_ptr * _T3C;
  struct _fat_ptr _T3D;
  unsigned char * _T3E;
  unsigned int * _T3F;
  struct _fat_ptr * _T40;
  struct _fat_ptr _T41;
  unsigned char * _T42;
  unsigned int * _T43;
  unsigned int _T44;
  struct _fat_ptr _T45;
  unsigned char * _T46;
  unsigned int * _T47;
  struct _fat_ptr _T48;
  unsigned char * _T49;
  unsigned int * _T4A;
  struct _fat_ptr * _T4B;
  struct _fat_ptr _T4C;
  unsigned char * _T4D;
  unsigned int * _T4E;
  struct _fat_ptr * _T4F;
  struct _fat_ptr _T50;
  unsigned char * _T51;
  unsigned int * _T52;
  unsigned int _T53;
  unsigned int _T54;
  struct _fat_ptr _T55;
  unsigned char * _T56;
  unsigned int * _T57;
  unsigned int _T58;
  unsigned int _T59;
  int _T5A;
  struct _fat_ptr * _T5B;
  register int i;
  register int k;
  register unsigned int mask;
  register struct Cyc_shifts_tag * shiftp;
  struct _fat_ptr fp1;
  struct _fat_ptr fp2;
  struct _fat_ptr fp3;
  register int symbol;
  Cyc_src_count = 0;
  _T0 = Cyc_shift_table;
  _T1 = state;
  _T2 = _check_fat_subscript(_T0,sizeof(struct Cyc_shifts_tag *),_T1);
  _T3 = (struct Cyc_shifts_tag * *)_T2;
  shiftp = *_T3;
  _T4 = shiftp;
  _T5 = (unsigned int)_T4;
  if (_T5) { goto _TL94;
  }else { goto _TL96;
  }
  _TL96: return;
  _TL94: i = 0;
  _TL9A: if (i < Cyc_tokensetsize) { goto _TL98;
  }else { goto _TL99;
  }
  _TL98: _T6 = Cyc_shiftset;
  _T7 = i;
  _T8 = _check_fat_subscript(_T6,sizeof(unsigned int),_T7);
  _T9 = (unsigned int *)_T8;
  *_T9 = 0U;
  _TA = Cyc_lookaheadset;
  _TB = i;
  _TC = _check_fat_subscript(_TA,sizeof(unsigned int),_TB);
  _TD = (unsigned int *)_TC;
  *_TD = 0U;
  i = i + 1;
  goto _TL9A;
  _TL99: _TE = shiftp;
  _TF = _TE->nshifts;
  k = (int)_TF;
  i = 0;
  _TL9E: if (i < k) { goto _TL9C;
  }else { goto _TL9D;
  }
  _TL9C: _T10 = shiftp;
  _T11 = _T10->shifts;
  _T12 = i;
  _T13 = _check_fat_subscript(_T11,sizeof(short),_T12);
  _T14 = (short *)_T13;
  _T15 = *_T14;
  _T16 = (int)_T15;
  if (_T16) { goto _TL9F;
  }else { goto _TLA1;
  }
  _TLA1: goto _TL9B;
  _TL9F: _T17 = Cyc_accessing_symbol;
  _T18 = shiftp;
  _T19 = _T18->shifts;
  _T1A = _T19.curr;
  _T1B = (short *)_T1A;
  _T1C = i;
  _T1D = _T1B[_T1C];
  _T1E = (int)_T1D;
  _T1F = _check_fat_subscript(_T17,sizeof(short),_T1E);
  _T20 = (short *)_T1F;
  _T21 = *_T20;
  symbol = (int)_T21;
  if (symbol < Cyc_ntokens) { goto _TLA2;
  }
  goto _TL9D;
  _TLA2: _T22 = Cyc_shiftset;
  _T23 = symbol / 32;
  _T24 = _check_fat_subscript(_T22,sizeof(unsigned int),_T23);
  _T25 = (unsigned int *)_T24;
  _T26 = symbol % 32;
  _T27 = 1U << _T26;
  *_T25 = *_T25 | _T27;
  _TL9B: i = i + 1;
  goto _TL9E;
  _TL9D: _T28 = Cyc_lookaheads;
  _T29 = state + 1;
  _T2A = _check_fat_subscript(_T28,sizeof(short),_T29);
  _T2B = (short *)_T2A;
  _T2C = *_T2B;
  k = (int)_T2C;
  _T2D = Cyc_lookaheadset;
  _T2E = Cyc_tokensetsize;
  fp3 = _fat_ptr_plus(_T2D,sizeof(unsigned int),_T2E);
  _T2F = Cyc_lookaheads;
  _T30 = _T2F.curr;
  _T31 = (short *)_T30;
  _T32 = state;
  _T33 = _T31[_T32];
  i = (int)_T33;
  _TLA7: if (i < k) { goto _TLA5;
  }else { goto _TLA6;
  }
  _TLA5: _T34 = Cyc_LA;
  _T35 = i * Cyc_tokensetsize;
  fp1 = _fat_ptr_plus(_T34,sizeof(unsigned int),_T35);
  fp2 = Cyc_lookaheadset;
  _TLA8: _T36 = fp2;
  _T37 = _T36.curr;
  _T38 = (unsigned int *)_T37;
  _T39 = fp3;
  _T3A = _T39.curr;
  _T3B = (unsigned int *)_T3A;
  if (_T38 < _T3B) { goto _TLA9;
  }else { goto _TLAA;
  }
  _TLA9: _T3C = &fp2;
  _T3D = _fat_ptr_inplace_plus_post(_T3C,sizeof(unsigned int),1);
  _T3E = _check_fat_subscript(_T3D,sizeof(unsigned int),0U);
  _T3F = (unsigned int *)_T3E;
  _T40 = &fp1;
  _T41 = _fat_ptr_inplace_plus_post(_T40,sizeof(unsigned int),1);
  _T42 = _check_fat_subscript(_T41,sizeof(unsigned int),0U);
  _T43 = (unsigned int *)_T42;
  _T44 = *_T43;
  *_T3F = *_T3F | _T44;
  goto _TLA8;
  _TLAA: i = i + 1;
  goto _TLA7;
  _TLA6: fp1 = Cyc_shiftset;
  fp2 = Cyc_lookaheadset;
  _TLAB: _T45 = fp2;
  _T46 = _T45.curr;
  _T47 = (unsigned int *)_T46;
  _T48 = fp3;
  _T49 = _T48.curr;
  _T4A = (unsigned int *)_T49;
  if (_T47 < _T4A) { goto _TLAC;
  }else { goto _TLAD;
  }
  _TLAC: _T4B = &fp2;
  _T4C = _fat_ptr_inplace_plus_post(_T4B,sizeof(unsigned int),1);
  _T4D = _check_fat_subscript(_T4C,sizeof(unsigned int),0U);
  _T4E = (unsigned int *)_T4D;
  _T4F = &fp1;
  _T50 = _fat_ptr_inplace_plus_post(_T4F,sizeof(unsigned int),1);
  _T51 = _check_fat_subscript(_T50,sizeof(unsigned int),0U);
  _T52 = (unsigned int *)_T51;
  _T53 = *_T52;
  *_T4E = *_T4E & _T53;
  goto _TLAB;
  _TLAD: mask = 1U;
  fp2 = Cyc_lookaheadset;
  i = 0;
  _TLB1: if (i < Cyc_ntokens) { goto _TLAF;
  }else { goto _TLB0;
  }
  _TLAF: _T54 = mask;
  _T55 = fp2;
  _T56 = _check_fat_subscript(_T55,sizeof(unsigned int),0U);
  _T57 = (unsigned int *)_T56;
  _T58 = *_T57;
  _T59 = _T54 & _T58;
  _T5A = (int)_T59;
  if (! _T5A) { goto _TLB2;
  }
  Cyc_src_count = Cyc_src_count + 1;
  goto _TLB3;
  _TLB2: _TLB3: mask = mask << 1U;
  if (mask != 0U) { goto _TLB4;
  }
  mask = 1U;
  _T5B = &fp2;
  _fat_ptr_inplace_plus(_T5B,sizeof(unsigned int),1);
  goto _TLB5;
  _TLB4: _TLB5: i = i + 1;
  goto _TLB1;
  _TLB0: ;
}
void Cyc_count_rr_conflicts(int state) {
  struct _fat_ptr _T0;
  int _T1;
  unsigned char * _T2;
  short * _T3;
  short _T4;
  struct _fat_ptr _T5;
  int _T6;
  unsigned char * _T7;
  short * _T8;
  short _T9;
  int _TA;
  struct _fat_ptr _TB;
  int _TC;
  unsigned int _TD;
  struct _fat_ptr _TE;
  unsigned char * _TF;
  unsigned int * _T10;
  unsigned int _T11;
  unsigned int _T12;
  int _T13;
  struct _fat_ptr * _T14;
  int _T15;
  struct _fat_ptr * _T16;
  register int i;
  register int j;
  register int count;
  register unsigned int mask;
  struct _fat_ptr baseword;
  struct _fat_ptr wordp;
  register int m;
  register int n;
  Cyc_rrc_count = 0;
  _T0 = Cyc_lookaheads;
  _T1 = state;
  _T2 = _check_fat_subscript(_T0,sizeof(short),_T1);
  _T3 = (short *)_T2;
  _T4 = *_T3;
  m = (int)_T4;
  _T5 = Cyc_lookaheads;
  _T6 = state + 1;
  _T7 = _check_fat_subscript(_T5,sizeof(short),_T6);
  _T8 = (short *)_T7;
  _T9 = *_T8;
  n = (int)_T9;
  _TA = n - m;
  if (_TA >= 2) { goto _TLB6;
  }
  return;
  _TLB6: mask = 1U;
  _TB = Cyc_LA;
  _TC = m * Cyc_tokensetsize;
  baseword = _fat_ptr_plus(_TB,sizeof(unsigned int),_TC);
  i = 0;
  _TLBB: if (i < Cyc_ntokens) { goto _TLB9;
  }else { goto _TLBA;
  }
  _TLB9: wordp = baseword;
  count = 0;
  j = m;
  _TLBF: if (j < n) { goto _TLBD;
  }else { goto _TLBE;
  }
  _TLBD: _TD = mask;
  _TE = wordp;
  _TF = _check_fat_subscript(_TE,sizeof(unsigned int),0U);
  _T10 = (unsigned int *)_TF;
  _T11 = *_T10;
  _T12 = _TD & _T11;
  _T13 = (int)_T12;
  if (! _T13) { goto _TLC0;
  }
  count = count + 1;
  goto _TLC1;
  _TLC0: _TLC1: _T14 = &wordp;
  _T15 = Cyc_tokensetsize;
  _fat_ptr_inplace_plus(_T14,sizeof(unsigned int),_T15);
  j = j + 1;
  goto _TLBF;
  _TLBE: if (count < 2) { goto _TLC2;
  }
  Cyc_rrc_count = Cyc_rrc_count + 1;
  goto _TLC3;
  _TLC2: _TLC3: mask = mask << 1U;
  if (mask != 0U) { goto _TLC4;
  }
  mask = 1U;
  _T16 = &baseword;
  _fat_ptr_inplace_plus(_T16,sizeof(unsigned int),1);
  goto _TLC5;
  _TLC4: _TLC5: i = i + 1;
  goto _TLBB;
  _TLBA: ;
}
void Cyc_print_reductions(int state) {
  struct _fat_ptr _T0;
  int _T1;
  unsigned char * _T2;
  unsigned int * _T3;
  struct _fat_ptr _T4;
  int _T5;
  unsigned char * _T6;
  struct Cyc_shifts_tag * * _T7;
  struct Cyc_shifts_tag * _T8;
  unsigned int _T9;
  struct Cyc_shifts_tag * _TA;
  short _TB;
  struct Cyc_shifts_tag * _TC;
  struct _fat_ptr _TD;
  int _TE;
  unsigned char * _TF;
  short * _T10;
  short _T11;
  int _T12;
  struct _fat_ptr _T13;
  struct Cyc_shifts_tag * _T14;
  struct _fat_ptr _T15;
  unsigned char * _T16;
  short * _T17;
  int _T18;
  short _T19;
  int _T1A;
  unsigned char * _T1B;
  short * _T1C;
  short _T1D;
  struct _fat_ptr _T1E;
  int _T1F;
  unsigned char * _T20;
  unsigned int * _T21;
  int _T22;
  unsigned int _T23;
  struct _fat_ptr _T24;
  int _T25;
  unsigned char * _T26;
  struct Cyc_errs_tag * * _T27;
  struct Cyc_errs_tag * _T28;
  unsigned int _T29;
  struct Cyc_errs_tag * _T2A;
  short _T2B;
  struct Cyc_errs_tag * _T2C;
  struct _fat_ptr _T2D;
  int _T2E;
  unsigned char * _T2F;
  short * _T30;
  short _T31;
  int _T32;
  struct Cyc_errs_tag * _T33;
  struct _fat_ptr _T34;
  unsigned char * _T35;
  short * _T36;
  int _T37;
  short _T38;
  struct _fat_ptr _T39;
  int _T3A;
  unsigned char * _T3B;
  unsigned int * _T3C;
  int _T3D;
  unsigned int _T3E;
  struct _fat_ptr _T3F;
  int _T40;
  unsigned char * _T41;
  short * _T42;
  short _T43;
  struct _fat_ptr _T44;
  int _T45;
  unsigned char * _T46;
  short * _T47;
  short _T48;
  int _T49;
  int _T4A;
  struct _fat_ptr _T4B;
  int _T4C;
  unsigned char * _T4D;
  short * _T4E;
  short _T4F;
  struct _fat_ptr _T50;
  int _T51;
  struct _fat_ptr _T52;
  int _T53;
  struct _fat_ptr _T54;
  unsigned char * _T55;
  unsigned int * _T56;
  struct _fat_ptr _T57;
  unsigned char * _T58;
  unsigned int * _T59;
  struct _fat_ptr * _T5A;
  struct _fat_ptr _T5B;
  unsigned char * _T5C;
  unsigned int * _T5D;
  struct _fat_ptr * _T5E;
  struct _fat_ptr _T5F;
  unsigned char * _T60;
  unsigned int * _T61;
  unsigned int _T62;
  struct _fat_ptr * _T63;
  struct _fat_ptr _T64;
  unsigned char * _T65;
  unsigned int * _T66;
  unsigned int _T67;
  unsigned int _T68;
  struct _fat_ptr _T69;
  unsigned char * _T6A;
  unsigned int * _T6B;
  unsigned int _T6C;
  unsigned int _T6D;
  int _T6E;
  struct Cyc_String_pa_PrintArg_struct _T6F;
  struct _fat_ptr _T70;
  int _T71;
  unsigned char * _T72;
  struct _fat_ptr * _T73;
  struct _fat_ptr _T74;
  struct Cyc_Int_pa_PrintArg_struct _T75;
  int _T76;
  struct Cyc_String_pa_PrintArg_struct _T77;
  struct _fat_ptr _T78;
  struct _fat_ptr _T79;
  int _T7A;
  unsigned char * _T7B;
  short * _T7C;
  short _T7D;
  int _T7E;
  unsigned char * _T7F;
  struct _fat_ptr * _T80;
  struct _fat_ptr _T81;
  struct Cyc___cycFILE * _T82;
  struct _fat_ptr _T83;
  struct _fat_ptr _T84;
  struct _fat_ptr * _T85;
  struct Cyc_Int_pa_PrintArg_struct _T86;
  int _T87;
  struct Cyc_String_pa_PrintArg_struct _T88;
  struct _fat_ptr _T89;
  struct _fat_ptr _T8A;
  int _T8B;
  unsigned char * _T8C;
  short * _T8D;
  short _T8E;
  int _T8F;
  unsigned char * _T90;
  struct _fat_ptr * _T91;
  struct _fat_ptr _T92;
  struct Cyc___cycFILE * _T93;
  struct _fat_ptr _T94;
  struct _fat_ptr _T95;
  int _T96;
  struct _fat_ptr _T97;
  int _T98;
  int _T99;
  struct _fat_ptr _T9A;
  int _T9B;
  struct _fat_ptr _T9C;
  unsigned char * _T9D;
  unsigned int * _T9E;
  struct _fat_ptr _T9F;
  unsigned char * _TA0;
  unsigned int * _TA1;
  struct _fat_ptr * _TA2;
  struct _fat_ptr _TA3;
  unsigned char * _TA4;
  unsigned int * _TA5;
  struct _fat_ptr * _TA6;
  struct _fat_ptr _TA7;
  unsigned char * _TA8;
  unsigned int * _TA9;
  unsigned int _TAA;
  struct _fat_ptr * _TAB;
  struct _fat_ptr _TAC;
  unsigned char * _TAD;
  unsigned int * _TAE;
  unsigned int _TAF;
  unsigned int _TB0;
  unsigned int _TB1;
  struct _fat_ptr _TB2;
  unsigned char * _TB3;
  unsigned int * _TB4;
  unsigned int _TB5;
  unsigned int _TB6;
  int _TB7;
  struct _fat_ptr * _TB8;
  struct _fat_ptr _TB9;
  unsigned char * _TBA;
  short * _TBB;
  int _TBC;
  short _TBD;
  struct _fat_ptr _TBE;
  unsigned char * _TBF;
  unsigned int * _TC0;
  struct _fat_ptr _TC1;
  unsigned char * _TC2;
  unsigned int * _TC3;
  struct _fat_ptr * _TC4;
  struct _fat_ptr _TC5;
  unsigned char * _TC6;
  unsigned int * _TC7;
  struct _fat_ptr * _TC8;
  struct _fat_ptr _TC9;
  unsigned char * _TCA;
  unsigned int * _TCB;
  unsigned int _TCC;
  struct _fat_ptr _TCD;
  int _TCE;
  unsigned char * _TCF;
  unsigned int * _TD0;
  struct Cyc_shifts_tag * _TD1;
  unsigned int _TD2;
  struct Cyc_shifts_tag * _TD3;
  short _TD4;
  struct Cyc_shifts_tag * _TD5;
  struct _fat_ptr _TD6;
  int _TD7;
  unsigned char * _TD8;
  short * _TD9;
  short _TDA;
  int _TDB;
  struct _fat_ptr _TDC;
  struct Cyc_shifts_tag * _TDD;
  struct _fat_ptr _TDE;
  unsigned char * _TDF;
  short * _TE0;
  int _TE1;
  short _TE2;
  int _TE3;
  unsigned char * _TE4;
  short * _TE5;
  short _TE6;
  struct _fat_ptr _TE7;
  int _TE8;
  unsigned char * _TE9;
  unsigned int * _TEA;
  int _TEB;
  unsigned int _TEC;
  struct _fat_ptr _TED;
  int _TEE;
  unsigned int _TEF;
  struct _fat_ptr _TF0;
  unsigned char * _TF1;
  unsigned int * _TF2;
  unsigned int _TF3;
  unsigned int _TF4;
  int _TF5;
  unsigned int _TF6;
  struct _fat_ptr _TF7;
  unsigned char * _TF8;
  unsigned int * _TF9;
  unsigned int _TFA;
  unsigned int _TFB;
  int _TFC;
  struct _fat_ptr _TFD;
  int _TFE;
  unsigned char * _TFF;
  short * _T100;
  short _T101;
  struct Cyc_String_pa_PrintArg_struct _T102;
  struct _fat_ptr _T103;
  int _T104;
  unsigned char * _T105;
  struct _fat_ptr * _T106;
  struct _fat_ptr _T107;
  struct Cyc_Int_pa_PrintArg_struct _T108;
  int _T109;
  struct Cyc_String_pa_PrintArg_struct _T10A;
  struct _fat_ptr _T10B;
  struct _fat_ptr _T10C;
  int _T10D;
  unsigned char * _T10E;
  short * _T10F;
  short _T110;
  int _T111;
  unsigned char * _T112;
  struct _fat_ptr * _T113;
  struct _fat_ptr _T114;
  struct Cyc___cycFILE * _T115;
  struct _fat_ptr _T116;
  struct _fat_ptr _T117;
  int _T118;
  struct _fat_ptr _T119;
  unsigned char * _T11A;
  short * _T11B;
  int _T11C;
  short _T11D;
  struct Cyc_String_pa_PrintArg_struct _T11E;
  struct _fat_ptr _T11F;
  unsigned char * _T120;
  struct _fat_ptr * _T121;
  int _T122;
  struct _fat_ptr _T123;
  struct Cyc_Int_pa_PrintArg_struct _T124;
  int _T125;
  struct Cyc_String_pa_PrintArg_struct _T126;
  struct _fat_ptr _T127;
  unsigned char * _T128;
  struct _fat_ptr * _T129;
  struct _fat_ptr _T12A;
  unsigned char * _T12B;
  short * _T12C;
  int _T12D;
  short _T12E;
  int _T12F;
  struct _fat_ptr _T130;
  struct Cyc___cycFILE * _T131;
  struct _fat_ptr _T132;
  struct _fat_ptr _T133;
  struct _fat_ptr _T134;
  unsigned char * _T135;
  short * _T136;
  int _T137;
  short _T138;
  struct Cyc_String_pa_PrintArg_struct _T139;
  struct _fat_ptr _T13A;
  unsigned char * _T13B;
  struct _fat_ptr * _T13C;
  int _T13D;
  struct _fat_ptr _T13E;
  struct Cyc_Int_pa_PrintArg_struct _T13F;
  int _T140;
  struct Cyc_String_pa_PrintArg_struct _T141;
  struct _fat_ptr _T142;
  unsigned char * _T143;
  struct _fat_ptr * _T144;
  struct _fat_ptr _T145;
  unsigned char * _T146;
  short * _T147;
  int _T148;
  short _T149;
  int _T14A;
  struct _fat_ptr _T14B;
  struct Cyc___cycFILE * _T14C;
  struct _fat_ptr _T14D;
  struct _fat_ptr _T14E;
  struct _fat_ptr * _T14F;
  int _T150;
  struct _fat_ptr * _T151;
  struct _fat_ptr * _T152;
  struct Cyc_Int_pa_PrintArg_struct _T153;
  int _T154;
  struct Cyc_String_pa_PrintArg_struct _T155;
  struct _fat_ptr _T156;
  struct _fat_ptr _T157;
  int _T158;
  unsigned char * _T159;
  short * _T15A;
  short _T15B;
  int _T15C;
  unsigned char * _T15D;
  struct _fat_ptr * _T15E;
  struct _fat_ptr _T15F;
  struct Cyc___cycFILE * _T160;
  struct _fat_ptr _T161;
  struct _fat_ptr _T162;
  struct Cyc___cycFILE * _T163;
  register int i;
  register int j;
  register int k;
  struct _fat_ptr fp1;
  struct _fat_ptr fp2;
  struct _fat_ptr fp3;
  struct _fat_ptr fp4;
  register int rule;
  register int symbol;
  register unsigned int mask;
  register int m;
  register int n;
  register int default_LA;
  register int default_rule = 0;
  register int cmax;
  register int count;
  register struct Cyc_shifts_tag * shiftp;
  register struct Cyc_errs_tag * errp;
  int nodefault = 0;
  i = 0;
  _TLC9: if (i < Cyc_tokensetsize) { goto _TLC7;
  }else { goto _TLC8;
  }
  _TLC7: _T0 = Cyc_shiftset;
  _T1 = i;
  _T2 = _check_fat_subscript(_T0,sizeof(unsigned int),_T1);
  _T3 = (unsigned int *)_T2;
  *_T3 = 0U;
  i = i + 1;
  goto _TLC9;
  _TLC8: _T4 = Cyc_shift_table;
  _T5 = state;
  _T6 = _check_fat_subscript(_T4,sizeof(struct Cyc_shifts_tag *),_T5);
  _T7 = (struct Cyc_shifts_tag * *)_T6;
  shiftp = *_T7;
  _T8 = shiftp;
  _T9 = (unsigned int)_T8;
  if (! _T9) { goto _TLCA;
  }
  _TA = shiftp;
  _TB = _TA->nshifts;
  k = (int)_TB;
  i = 0;
  _TLCF: if (i < k) { goto _TLCD;
  }else { goto _TLCE;
  }
  _TLCD: _TC = shiftp;
  _TD = _TC->shifts;
  _TE = i;
  _TF = _check_fat_subscript(_TD,sizeof(short),_TE);
  _T10 = (short *)_TF;
  _T11 = *_T10;
  _T12 = (int)_T11;
  if (_T12) { goto _TLD0;
  }else { goto _TLD2;
  }
  _TLD2: goto _TLCC;
  _TLD0: _T13 = Cyc_accessing_symbol;
  _T14 = shiftp;
  _T15 = _T14->shifts;
  _T16 = _T15.curr;
  _T17 = (short *)_T16;
  _T18 = i;
  _T19 = _T17[_T18];
  _T1A = (int)_T19;
  _T1B = _check_fat_subscript(_T13,sizeof(short),_T1A);
  _T1C = (short *)_T1B;
  _T1D = *_T1C;
  symbol = (int)_T1D;
  if (symbol < Cyc_ntokens) { goto _TLD3;
  }
  goto _TLCE;
  _TLD3: if (symbol != Cyc_error_token_number) { goto _TLD5;
  }
  nodefault = 1;
  goto _TLD6;
  _TLD5: _TLD6: _T1E = Cyc_shiftset;
  _T1F = symbol / 32;
  _T20 = _check_fat_subscript(_T1E,sizeof(unsigned int),_T1F);
  _T21 = (unsigned int *)_T20;
  _T22 = symbol % 32;
  _T23 = 1U << _T22;
  *_T21 = *_T21 | _T23;
  _TLCC: i = i + 1;
  goto _TLCF;
  _TLCE: goto _TLCB;
  _TLCA: _TLCB: _T24 = Cyc_err_table;
  _T25 = state;
  _T26 = _check_fat_subscript(_T24,sizeof(struct Cyc_errs_tag *),_T25);
  _T27 = (struct Cyc_errs_tag * *)_T26;
  errp = *_T27;
  _T28 = errp;
  _T29 = (unsigned int)_T28;
  if (! _T29) { goto _TLD7;
  }
  _T2A = errp;
  _T2B = _T2A->nerrs;
  k = (int)_T2B;
  i = 0;
  _TLDC: if (i < k) { goto _TLDA;
  }else { goto _TLDB;
  }
  _TLDA: _T2C = errp;
  _T2D = _T2C->errs;
  _T2E = i;
  _T2F = _check_fat_subscript(_T2D,sizeof(short),_T2E);
  _T30 = (short *)_T2F;
  _T31 = *_T30;
  _T32 = (int)_T31;
  if (_T32) { goto _TLDD;
  }else { goto _TLDF;
  }
  _TLDF: goto _TLD9;
  _TLDD: _T33 = errp;
  _T34 = _T33->errs;
  _T35 = _T34.curr;
  _T36 = (short *)_T35;
  _T37 = i;
  _T38 = _T36[_T37];
  symbol = (int)_T38;
  _T39 = Cyc_shiftset;
  _T3A = symbol / 32;
  _T3B = _check_fat_subscript(_T39,sizeof(unsigned int),_T3A);
  _T3C = (unsigned int *)_T3B;
  _T3D = symbol % 32;
  _T3E = 1U << _T3D;
  *_T3C = *_T3C | _T3E;
  _TLD9: i = i + 1;
  goto _TLDC;
  _TLDB: goto _TLD8;
  _TLD7: _TLD8: _T3F = Cyc_lookaheads;
  _T40 = state;
  _T41 = _check_fat_subscript(_T3F,sizeof(short),_T40);
  _T42 = (short *)_T41;
  _T43 = *_T42;
  m = (int)_T43;
  _T44 = Cyc_lookaheads;
  _T45 = state + 1;
  _T46 = _check_fat_subscript(_T44,sizeof(short),_T45);
  _T47 = (short *)_T46;
  _T48 = *_T47;
  n = (int)_T48;
  _T49 = n - m;
  if (_T49 != 1) { goto _TLE0;
  }
  _T4A = nodefault;
  if (_T4A) { goto _TLE0;
  }else { goto _TLE2;
  }
  _TLE2: _T4B = Cyc_LAruleno;
  _T4C = m;
  _T4D = _check_fat_subscript(_T4B,sizeof(short),_T4C);
  _T4E = (short *)_T4D;
  _T4F = *_T4E;
  default_rule = (int)_T4F;
  _T50 = Cyc_LA;
  _T51 = m * Cyc_tokensetsize;
  fp1 = _fat_ptr_plus(_T50,sizeof(unsigned int),_T51);
  fp2 = Cyc_shiftset;
  fp3 = Cyc_lookaheadset;
  _T52 = Cyc_lookaheadset;
  _T53 = Cyc_tokensetsize;
  fp4 = _fat_ptr_plus(_T52,sizeof(unsigned int),_T53);
  _TLE3: _T54 = fp3;
  _T55 = _T54.curr;
  _T56 = (unsigned int *)_T55;
  _T57 = fp4;
  _T58 = _T57.curr;
  _T59 = (unsigned int *)_T58;
  if (_T56 < _T59) { goto _TLE4;
  }else { goto _TLE5;
  }
  _TLE4: _T5A = &fp3;
  _T5B = _fat_ptr_inplace_plus_post(_T5A,sizeof(unsigned int),1);
  _T5C = _check_fat_subscript(_T5B,sizeof(unsigned int),0U);
  _T5D = (unsigned int *)_T5C;
  _T5E = &fp1;
  _T5F = _fat_ptr_inplace_plus_post(_T5E,sizeof(unsigned int),1);
  _T60 = _check_fat_subscript(_T5F,sizeof(unsigned int),0U);
  _T61 = (unsigned int *)_T60;
  _T62 = *_T61;
  _T63 = &fp2;
  _T64 = _fat_ptr_inplace_plus_post(_T63,sizeof(unsigned int),1);
  _T65 = _check_fat_subscript(_T64,sizeof(unsigned int),0U);
  _T66 = (unsigned int *)_T65;
  _T67 = *_T66;
  *_T5D = _T62 & _T67;
  goto _TLE3;
  _TLE5: mask = 1U;
  fp3 = Cyc_lookaheadset;
  i = 0;
  _TLE9: if (i < Cyc_ntokens) { goto _TLE7;
  }else { goto _TLE8;
  }
  _TLE7: _T68 = mask;
  _T69 = fp3;
  _T6A = _check_fat_subscript(_T69,sizeof(unsigned int),0U);
  _T6B = (unsigned int *)_T6A;
  _T6C = *_T6B;
  _T6D = _T68 & _T6C;
  _T6E = (int)_T6D;
  if (! _T6E) { goto _TLEA;
  }
  { struct Cyc_String_pa_PrintArg_struct _T164;
    _T164.tag = 0;
    _T70 = Cyc_tags;
    _T71 = i;
    _T72 = _check_fat_subscript(_T70,sizeof(struct _fat_ptr),_T71);
    _T73 = (struct _fat_ptr *)_T72;
    _T74 = *_T73;
    _T164.f1 = _T74;
    _T6F = _T164;
  }{ struct Cyc_String_pa_PrintArg_struct _T164 = _T6F;
    { struct Cyc_Int_pa_PrintArg_struct _T165;
      _T165.tag = 1;
      _T76 = default_rule;
      _T165.f1 = (unsigned long)_T76;
      _T75 = _T165;
    }{ struct Cyc_Int_pa_PrintArg_struct _T165 = _T75;
      { struct Cyc_String_pa_PrintArg_struct _T166;
	_T166.tag = 0;
	_T78 = Cyc_tags;
	_T79 = Cyc_rlhs;
	_T7A = default_rule;
	_T7B = _check_fat_subscript(_T79,sizeof(short),_T7A);
	_T7C = (short *)_T7B;
	_T7D = *_T7C;
	_T7E = (int)_T7D;
	_T7F = _check_fat_subscript(_T78,sizeof(struct _fat_ptr),_T7E);
	_T80 = (struct _fat_ptr *)_T7F;
	_T81 = *_T80;
	_T166.f1 = _T81;
	_T77 = _T166;
      }{ struct Cyc_String_pa_PrintArg_struct _T166 = _T77;
	void * _T167[3];
	_T167[0] = &_T164;
	_T167[1] = &_T165;
	_T167[2] = &_T166;
	_T82 = _check_null(Cyc_foutput);
	_T83 = _tag_fat("    %s\t[reduce using rule %d (%s)]\n",sizeof(char),
			36U);
	_T84 = _tag_fat(_T167,sizeof(void *),3);
	Cyc_fprintf(_T82,_T83,_T84);
      }
    }
  }goto _TLEB;
  _TLEA: _TLEB: mask = mask << 1U;
  if (mask != 0U) { goto _TLEC;
  }
  mask = 1U;
  _T85 = &fp3;
  _fat_ptr_inplace_plus(_T85,sizeof(unsigned int),1);
  goto _TLED;
  _TLEC: _TLED: i = i + 1;
  goto _TLE9;
  _TLE8: { struct Cyc_Int_pa_PrintArg_struct _T164;
    _T164.tag = 1;
    _T87 = default_rule;
    _T164.f1 = (unsigned long)_T87;
    _T86 = _T164;
  }{ struct Cyc_Int_pa_PrintArg_struct _T164 = _T86;
    { struct Cyc_String_pa_PrintArg_struct _T165;
      _T165.tag = 0;
      _T89 = Cyc_tags;
      _T8A = Cyc_rlhs;
      _T8B = default_rule;
      _T8C = _check_fat_subscript(_T8A,sizeof(short),_T8B);
      _T8D = (short *)_T8C;
      _T8E = *_T8D;
      _T8F = (int)_T8E;
      _T90 = _check_fat_subscript(_T89,sizeof(struct _fat_ptr),_T8F);
      _T91 = (struct _fat_ptr *)_T90;
      _T92 = *_T91;
      _T165.f1 = _T92;
      _T88 = _T165;
    }{ struct Cyc_String_pa_PrintArg_struct _T165 = _T88;
      void * _T166[2];
      _T166[0] = &_T164;
      _T166[1] = &_T165;
      _T93 = _check_null(Cyc_foutput);
      _T94 = _tag_fat("    $default\treduce using rule %d (%s)\n\n",sizeof(char),
		      41U);
      _T95 = _tag_fat(_T166,sizeof(void *),2);
      Cyc_fprintf(_T93,_T94,_T95);
    }
  }goto _TLE1;
  _TLE0: _T96 = n - m;
  if (_T96 < 1) { goto _TLEE;
  }
  cmax = 0;
  default_LA = - 1;
  _T97 = Cyc_lookaheadset;
  _T98 = Cyc_tokensetsize;
  fp4 = _fat_ptr_plus(_T97,sizeof(unsigned int),_T98);
  _T99 = nodefault;
  if (_T99) { goto _TLF0;
  }else { goto _TLF2;
  }
  _TLF2: i = m;
  _TLF6: if (i < n) { goto _TLF4;
  }else { goto _TLF5;
  }
  _TLF4: _T9A = Cyc_LA;
  _T9B = i * Cyc_tokensetsize;
  fp1 = _fat_ptr_plus(_T9A,sizeof(unsigned int),_T9B);
  fp2 = Cyc_shiftset;
  fp3 = Cyc_lookaheadset;
  _TLF7: _T9C = fp3;
  _T9D = _T9C.curr;
  _T9E = (unsigned int *)_T9D;
  _T9F = fp4;
  _TA0 = _T9F.curr;
  _TA1 = (unsigned int *)_TA0;
  if (_T9E < _TA1) { goto _TLF8;
  }else { goto _TLF9;
  }
  _TLF8: _TA2 = &fp3;
  _TA3 = _fat_ptr_inplace_plus_post(_TA2,sizeof(unsigned int),1);
  _TA4 = _check_fat_subscript(_TA3,sizeof(unsigned int),0U);
  _TA5 = (unsigned int *)_TA4;
  _TA6 = &fp1;
  _TA7 = _fat_ptr_inplace_plus_post(_TA6,sizeof(unsigned int),1);
  _TA8 = _check_fat_subscript(_TA7,sizeof(unsigned int),0U);
  _TA9 = (unsigned int *)_TA8;
  _TAA = *_TA9;
  _TAB = &fp2;
  _TAC = _fat_ptr_inplace_plus_post(_TAB,sizeof(unsigned int),1);
  _TAD = _check_fat_subscript(_TAC,sizeof(unsigned int),0U);
  _TAE = (unsigned int *)_TAD;
  _TAF = *_TAE;
  _TB0 = ~ _TAF;
  *_TA5 = _TAA & _TB0;
  goto _TLF7;
  _TLF9: count = 0;
  mask = 1U;
  fp3 = Cyc_lookaheadset;
  j = 0;
  _TLFD: if (j < Cyc_ntokens) { goto _TLFB;
  }else { goto _TLFC;
  }
  _TLFB: _TB1 = mask;
  _TB2 = fp3;
  _TB3 = _check_fat_subscript(_TB2,sizeof(unsigned int),0U);
  _TB4 = (unsigned int *)_TB3;
  _TB5 = *_TB4;
  _TB6 = _TB1 & _TB5;
  _TB7 = (int)_TB6;
  if (! _TB7) { goto _TLFE;
  }
  count = count + 1;
  goto _TLFF;
  _TLFE: _TLFF: mask = mask << 1U;
  if (mask != 0U) { goto _TL100;
  }
  mask = 1U;
  _TB8 = &fp3;
  _fat_ptr_inplace_plus(_TB8,sizeof(unsigned int),1);
  goto _TL101;
  _TL100: _TL101: j = j + 1;
  goto _TLFD;
  _TLFC: if (count <= cmax) { goto _TL102;
  }
  cmax = count;
  default_LA = i;
  _TB9 = Cyc_LAruleno;
  _TBA = _TB9.curr;
  _TBB = (short *)_TBA;
  _TBC = i;
  _TBD = _TBB[_TBC];
  default_rule = (int)_TBD;
  goto _TL103;
  _TL102: _TL103: fp2 = Cyc_shiftset;
  fp3 = Cyc_lookaheadset;
  _TL104: _TBE = fp3;
  _TBF = _TBE.curr;
  _TC0 = (unsigned int *)_TBF;
  _TC1 = fp4;
  _TC2 = _TC1.curr;
  _TC3 = (unsigned int *)_TC2;
  if (_TC0 < _TC3) { goto _TL105;
  }else { goto _TL106;
  }
  _TL105: _TC4 = &fp2;
  _TC5 = _fat_ptr_inplace_plus_post(_TC4,sizeof(unsigned int),1);
  _TC6 = _check_fat_subscript(_TC5,sizeof(unsigned int),0U);
  _TC7 = (unsigned int *)_TC6;
  _TC8 = &fp3;
  _TC9 = _fat_ptr_inplace_plus_post(_TC8,sizeof(unsigned int),1);
  _TCA = _check_fat_subscript(_TC9,sizeof(unsigned int),0U);
  _TCB = (unsigned int *)_TCA;
  _TCC = *_TCB;
  *_TC7 = *_TC7 | _TCC;
  goto _TL104;
  _TL106: i = i + 1;
  goto _TLF6;
  _TLF5: goto _TLF1;
  _TLF0: _TLF1: i = 0;
  _TL10A: if (i < Cyc_tokensetsize) { goto _TL108;
  }else { goto _TL109;
  }
  _TL108: _TCD = Cyc_shiftset;
  _TCE = i;
  _TCF = _check_fat_subscript(_TCD,sizeof(unsigned int),_TCE);
  _TD0 = (unsigned int *)_TCF;
  *_TD0 = 0U;
  i = i + 1;
  goto _TL10A;
  _TL109: _TD1 = shiftp;
  _TD2 = (unsigned int)_TD1;
  if (! _TD2) { goto _TL10B;
  }
  _TD3 = shiftp;
  _TD4 = _TD3->nshifts;
  k = (int)_TD4;
  i = 0;
  _TL110: if (i < k) { goto _TL10E;
  }else { goto _TL10F;
  }
  _TL10E: _TD5 = shiftp;
  _TD6 = _TD5->shifts;
  _TD7 = i;
  _TD8 = _check_fat_subscript(_TD6,sizeof(short),_TD7);
  _TD9 = (short *)_TD8;
  _TDA = *_TD9;
  _TDB = (int)_TDA;
  if (_TDB) { goto _TL111;
  }else { goto _TL113;
  }
  _TL113: goto _TL10D;
  _TL111: _TDC = Cyc_accessing_symbol;
  _TDD = shiftp;
  _TDE = _TDD->shifts;
  _TDF = _TDE.curr;
  _TE0 = (short *)_TDF;
  _TE1 = i;
  _TE2 = _TE0[_TE1];
  _TE3 = (int)_TE2;
  _TE4 = _check_fat_subscript(_TDC,sizeof(short),_TE3);
  _TE5 = (short *)_TE4;
  _TE6 = *_TE5;
  symbol = (int)_TE6;
  if (symbol < Cyc_ntokens) { goto _TL114;
  }
  goto _TL10F;
  _TL114: _TE7 = Cyc_shiftset;
  _TE8 = symbol / 32;
  _TE9 = _check_fat_subscript(_TE7,sizeof(unsigned int),_TE8);
  _TEA = (unsigned int *)_TE9;
  _TEB = symbol % 32;
  _TEC = 1U << _TEB;
  *_TEA = *_TEA | _TEC;
  _TL10D: i = i + 1;
  goto _TL110;
  _TL10F: goto _TL10C;
  _TL10B: _TL10C: mask = 1U;
  _TED = Cyc_LA;
  _TEE = m * Cyc_tokensetsize;
  fp1 = _fat_ptr_plus(_TED,sizeof(unsigned int),_TEE);
  fp2 = Cyc_shiftset;
  i = 0;
  _TL119: if (i < Cyc_ntokens) { goto _TL117;
  }else { goto _TL118;
  }
  _TL117: { int defaulted = 0;
    _TEF = mask;
    _TF0 = fp2;
    _TF1 = _check_fat_subscript(_TF0,sizeof(unsigned int),0U);
    _TF2 = (unsigned int *)_TF1;
    _TF3 = *_TF2;
    _TF4 = _TEF & _TF3;
    _TF5 = (int)_TF4;
    if (! _TF5) { goto _TL11A;
    }
    count = 1;
    goto _TL11B;
    _TL11A: count = 0;
    _TL11B: fp3 = fp1;
    j = m;
    _TL11F: if (j < n) { goto _TL11D;
    }else { goto _TL11E;
    }
    _TL11D: _TF6 = mask;
    _TF7 = fp3;
    _TF8 = _check_fat_subscript(_TF7,sizeof(unsigned int),0U);
    _TF9 = (unsigned int *)_TF8;
    _TFA = *_TF9;
    _TFB = _TF6 & _TFA;
    _TFC = (int)_TFB;
    if (! _TFC) { goto _TL120;
    }
    if (count != 0) { goto _TL122;
    }
    if (j == default_LA) { goto _TL124;
    }
    _TFD = Cyc_LAruleno;
    _TFE = j;
    _TFF = _check_fat_subscript(_TFD,sizeof(short),_TFE);
    _T100 = (short *)_TFF;
    _T101 = *_T100;
    rule = (int)_T101;
    { struct Cyc_String_pa_PrintArg_struct _T164;
      _T164.tag = 0;
      _T103 = Cyc_tags;
      _T104 = i;
      _T105 = _check_fat_subscript(_T103,sizeof(struct _fat_ptr),_T104);
      _T106 = (struct _fat_ptr *)_T105;
      _T107 = *_T106;
      _T164.f1 = _T107;
      _T102 = _T164;
    }{ struct Cyc_String_pa_PrintArg_struct _T164 = _T102;
      { struct Cyc_Int_pa_PrintArg_struct _T165;
	_T165.tag = 1;
	_T109 = rule;
	_T165.f1 = (unsigned long)_T109;
	_T108 = _T165;
      }{ struct Cyc_Int_pa_PrintArg_struct _T165 = _T108;
	{ struct Cyc_String_pa_PrintArg_struct _T166;
	  _T166.tag = 0;
	  _T10B = Cyc_tags;
	  _T10C = Cyc_rlhs;
	  _T10D = rule;
	  _T10E = _check_fat_subscript(_T10C,sizeof(short),_T10D);
	  _T10F = (short *)_T10E;
	  _T110 = *_T10F;
	  _T111 = (int)_T110;
	  _T112 = _check_fat_subscript(_T10B,sizeof(struct _fat_ptr),_T111);
	  _T113 = (struct _fat_ptr *)_T112;
	  _T114 = *_T113;
	  _T166.f1 = _T114;
	  _T10A = _T166;
	}{ struct Cyc_String_pa_PrintArg_struct _T166 = _T10A;
	  void * _T167[3];
	  _T167[0] = &_T164;
	  _T167[1] = &_T165;
	  _T167[2] = &_T166;
	  _T115 = _check_null(Cyc_foutput);
	  _T116 = _tag_fat("    %s\treduce using rule %d (%s)\n",sizeof(char),
			   34U);
	  _T117 = _tag_fat(_T167,sizeof(void *),3);
	  Cyc_fprintf(_T115,_T116,_T117);
	}
      }
    }goto _TL125;
    _TL124: defaulted = 1;
    _TL125: count = count + 1;
    goto _TL123;
    _TL122: _T118 = defaulted;
    if (! _T118) { goto _TL126;
    }
    _T119 = Cyc_LAruleno;
    _T11A = _T119.curr;
    _T11B = (short *)_T11A;
    _T11C = default_LA;
    _T11D = _T11B[_T11C];
    rule = (int)_T11D;
    { struct Cyc_String_pa_PrintArg_struct _T164;
      _T164.tag = 0;
      _T11F = Cyc_tags;
      _T120 = _T11F.curr;
      _T121 = (struct _fat_ptr *)_T120;
      _T122 = i;
      _T123 = _T121[_T122];
      _T164.f1 = _T123;
      _T11E = _T164;
    }{ struct Cyc_String_pa_PrintArg_struct _T164 = _T11E;
      { struct Cyc_Int_pa_PrintArg_struct _T165;
	_T165.tag = 1;
	_T125 = rule;
	_T165.f1 = (unsigned long)_T125;
	_T124 = _T165;
      }{ struct Cyc_Int_pa_PrintArg_struct _T165 = _T124;
	{ struct Cyc_String_pa_PrintArg_struct _T166;
	  _T166.tag = 0;
	  _T127 = Cyc_tags;
	  _T128 = _T127.curr;
	  _T129 = (struct _fat_ptr *)_T128;
	  _T12A = Cyc_rlhs;
	  _T12B = _T12A.curr;
	  _T12C = (short *)_T12B;
	  _T12D = rule;
	  _T12E = _T12C[_T12D];
	  _T12F = (int)_T12E;
	  _T130 = _T129[_T12F];
	  _T166.f1 = _T130;
	  _T126 = _T166;
	}{ struct Cyc_String_pa_PrintArg_struct _T166 = _T126;
	  void * _T167[3];
	  _T167[0] = &_T164;
	  _T167[1] = &_T165;
	  _T167[2] = &_T166;
	  _T131 = Cyc_foutput;
	  _T132 = _tag_fat("    %s\treduce using rule %d (%s)\n",sizeof(char),
			   34U);
	  _T133 = _tag_fat(_T167,sizeof(void *),3);
	  Cyc_fprintf(_T131,_T132,_T133);
	}
      }
    }defaulted = 0;
    goto _TL127;
    _TL126: _TL127: _T134 = Cyc_LAruleno;
    _T135 = _T134.curr;
    _T136 = (short *)_T135;
    _T137 = j;
    _T138 = _T136[_T137];
    rule = (int)_T138;
    { struct Cyc_String_pa_PrintArg_struct _T164;
      _T164.tag = 0;
      _T13A = Cyc_tags;
      _T13B = _T13A.curr;
      _T13C = (struct _fat_ptr *)_T13B;
      _T13D = i;
      _T13E = _T13C[_T13D];
      _T164.f1 = _T13E;
      _T139 = _T164;
    }{ struct Cyc_String_pa_PrintArg_struct _T164 = _T139;
      { struct Cyc_Int_pa_PrintArg_struct _T165;
	_T165.tag = 1;
	_T140 = rule;
	_T165.f1 = (unsigned long)_T140;
	_T13F = _T165;
      }{ struct Cyc_Int_pa_PrintArg_struct _T165 = _T13F;
	{ struct Cyc_String_pa_PrintArg_struct _T166;
	  _T166.tag = 0;
	  _T142 = Cyc_tags;
	  _T143 = _T142.curr;
	  _T144 = (struct _fat_ptr *)_T143;
	  _T145 = Cyc_rlhs;
	  _T146 = _T145.curr;
	  _T147 = (short *)_T146;
	  _T148 = rule;
	  _T149 = _T147[_T148];
	  _T14A = (int)_T149;
	  _T14B = _T144[_T14A];
	  _T166.f1 = _T14B;
	  _T141 = _T166;
	}{ struct Cyc_String_pa_PrintArg_struct _T166 = _T141;
	  void * _T167[3];
	  _T167[0] = &_T164;
	  _T167[1] = &_T165;
	  _T167[2] = &_T166;
	  _T14C = Cyc_foutput;
	  _T14D = _tag_fat("    %s\t[reduce using rule %d (%s)]\n",sizeof(char),
			   36U);
	  _T14E = _tag_fat(_T167,sizeof(void *),3);
	  Cyc_fprintf(_T14C,_T14D,_T14E);
	}
      }
    }_TL123: goto _TL121;
    _TL120: _TL121: _T14F = &fp3;
    _T150 = Cyc_tokensetsize;
    _fat_ptr_inplace_plus(_T14F,sizeof(unsigned int),_T150);
    j = j + 1;
    goto _TL11F;
    _TL11E: mask = mask << 1U;
    if (mask != 0U) { goto _TL128;
    }
    mask = 1U;
    _T151 = &fp1;
    _fat_ptr_inplace_plus(_T151,sizeof(unsigned int),1);
    _T152 = &fp2;
    _fat_ptr_inplace_plus(_T152,sizeof(unsigned int),1);
    goto _TL129;
    _TL128: _TL129: ;
  }i = i + 1;
  goto _TL119;
  _TL118: if (default_LA < 0) { goto _TL12A;
  }
  { struct Cyc_Int_pa_PrintArg_struct _T164;
    _T164.tag = 1;
    _T154 = default_rule;
    _T164.f1 = (unsigned long)_T154;
    _T153 = _T164;
  }{ struct Cyc_Int_pa_PrintArg_struct _T164 = _T153;
    { struct Cyc_String_pa_PrintArg_struct _T165;
      _T165.tag = 0;
      _T156 = Cyc_tags;
      _T157 = Cyc_rlhs;
      _T158 = default_rule;
      _T159 = _check_fat_subscript(_T157,sizeof(short),_T158);
      _T15A = (short *)_T159;
      _T15B = *_T15A;
      _T15C = (int)_T15B;
      _T15D = _check_fat_subscript(_T156,sizeof(struct _fat_ptr),_T15C);
      _T15E = (struct _fat_ptr *)_T15D;
      _T15F = *_T15E;
      _T165.f1 = _T15F;
      _T155 = _T165;
    }{ struct Cyc_String_pa_PrintArg_struct _T165 = _T155;
      void * _T166[2];
      _T166[0] = &_T164;
      _T166[1] = &_T165;
      _T160 = _check_null(Cyc_foutput);
      _T161 = _tag_fat("    $default\treduce using rule %d (%s)\n",sizeof(char),
		       40U);
      _T162 = _tag_fat(_T166,sizeof(void *),2);
      Cyc_fprintf(_T160,_T161,_T162);
    }
  }goto _TL12B;
  _TL12A: _TL12B: _T163 = _check_null(Cyc_foutput);
  Cyc_putc(10,_T163);
  goto _TLEF;
  _TLEE: _TLEF: _TLE1: ;
}
void Cyc_finalize_conflicts() {
  Cyc_conflicts = _tag_fat(0,0,0);
  Cyc_shiftset = _tag_fat(0,0,0);
  Cyc_lookaheadset = _tag_fat(0,0,0);
}
