#include <cyc_include.h>
struct Cyc___cycFILE;
extern struct Cyc___cycFILE * Cyc_stderr;
 struct Cyc_String_pa_PrintArg_struct {
  int tag;
  struct _fat_ptr f1;
};
 struct Cyc_Int_pa_PrintArg_struct {
  int tag;
  unsigned long f1;
};
extern int Cyc_fflush(struct Cyc___cycFILE *);
extern int Cyc_fprintf(struct Cyc___cycFILE *,struct _fat_ptr,struct _fat_ptr);
struct Cyc___cycFILE;
extern struct Cyc___cycFILE * Cyc_stderr;
extern int Cyc_fflush(struct Cyc___cycFILE *);
extern int Cyc_fprintf(struct Cyc___cycFILE *,struct _fat_ptr,struct _fat_ptr);
extern struct Cyc___cycFILE * Cyc_foutput;
extern struct _fat_ptr Cyc_infile;
extern int Cyc_nitems;
extern int Cyc_nrules;
extern int Cyc_nsyms;
extern int Cyc_ntokens;
extern int Cyc_nvars;
extern struct _fat_ptr Cyc_ritem;
extern struct _fat_ptr Cyc_rlhs;
extern struct _fat_ptr Cyc_rrhs;
extern struct _fat_ptr Cyc_rprec;
extern struct _fat_ptr Cyc_rprecsym;
extern struct _fat_ptr Cyc_sprec;
extern struct _fat_ptr Cyc_rassoc;
extern struct _fat_ptr Cyc_sassoc;
extern int Cyc_start_symbol;
extern struct _fat_ptr Cyc_tags;
extern int Cyc_verboseflag;
static int Cyc_statisticsflag;
static struct _fat_ptr Cyc_N;
static struct _fat_ptr Cyc_P;
static struct _fat_ptr Cyc_V;
static struct _fat_ptr Cyc_V1;
static int Cyc_nuseful_productions;
static int Cyc_nuseless_productions;
static int Cyc_nuseful_nonterminals;
static int Cyc_nuseless_nonterminals;
static void Cyc_useless_nonterminals();
static void Cyc_inaccessable_symbols();
static void Cyc_reduce_grammar_tables();
static void Cyc_print_results();
static void Cyc_print_notices();
extern void Cyc_fatals(struct _fat_ptr,struct _fat_ptr);
extern int Cyc_fixed_outfiles;
long Cyc_bits_equal(struct _fat_ptr L,struct _fat_ptr R,int n) {
  struct _fat_ptr _T0;
  int _T1;
  unsigned char * _T2;
  unsigned int * _T3;
  unsigned int _T4;
  struct _fat_ptr _T5;
  int _T6;
  unsigned char * _T7;
  unsigned int * _T8;
  unsigned int _T9;
  int i;
  i = n - 1;
  _TL3: if (i >= 0) { goto _TL1;
  }else { goto _TL2;
  }
  _TL1: _T0 = L;
  _T1 = i;
  _T2 = _check_fat_subscript(_T0,sizeof(unsigned int),_T1);
  _T3 = (unsigned int *)_T2;
  _T4 = *_T3;
  _T5 = R;
  _T6 = i;
  _T7 = _check_fat_subscript(_T5,sizeof(unsigned int),_T6);
  _T8 = (unsigned int *)_T7;
  _T9 = *_T8;
  if (_T4 == _T9) { goto _TL4;
  }
  return 0;
  _TL4: i = i + -1;
  goto _TL3;
  _TL2: return 1;
}
int Cyc_nbits(unsigned int i) {
  unsigned int _T0;
  unsigned int _T1;
  unsigned int _T2;
  int _T3;
  int count = 0;
  _TL6: if (i != 0U) { goto _TL7;
  }else { goto _TL8;
  }
  _TL7: _T0 = i;
  _T1 = - i;
  _T2 = _T0 & _T1;
  i = i ^ _T2;
  count = count + 1;
  goto _TL6;
  _TL8: _T3 = count;
  return _T3;
}
int Cyc_bits_size(struct _fat_ptr S,int n) {
  struct _fat_ptr _T0;
  int _T1;
  unsigned char * _T2;
  unsigned int * _T3;
  unsigned int _T4;
  int _T5;
  int _T6;
  int i;
  int count = 0;
  i = n - 1;
  _TLC: if (i >= 0) { goto _TLA;
  }else { goto _TLB;
  }
  _TLA: _T0 = S;
  _T1 = i;
  _T2 = _check_fat_subscript(_T0,sizeof(unsigned int),_T1);
  _T3 = (unsigned int *)_T2;
  _T4 = *_T3;
  _T5 = Cyc_nbits(_T4);
  count = count + _T5;
  i = i + -1;
  goto _TLC;
  _TLB: _T6 = count;
  return _T6;
}
void Cyc_reduce_grammar() {
  struct _fat_ptr _T0;
  int _T1;
  int _T2;
  int _T3;
  unsigned int * _T4;
  unsigned int _T5;
  unsigned int _T6;
  struct _fat_ptr _T7;
  int _T8;
  int _T9;
  int _TA;
  int _TB;
  unsigned int * _TC;
  unsigned int _TD;
  unsigned int _TE;
  struct _fat_ptr _TF;
  int _T10;
  int _T11;
  int _T12;
  unsigned int * _T13;
  unsigned int _T14;
  unsigned int _T15;
  struct _fat_ptr _T16;
  int _T17;
  int _T18;
  int _T19;
  unsigned int * _T1A;
  unsigned int _T1B;
  unsigned int _T1C;
  int _T1D;
  int _T1E;
  struct _fat_ptr _T1F;
  unsigned char * _T20;
  unsigned int * _T21;
  int _T22;
  int _T23;
  unsigned int _T24;
  int _T25;
  int _T26;
  unsigned int _T27;
  unsigned int _T28;
  struct _fat_ptr _T29;
  struct _fat_ptr _T2A;
  unsigned char * _T2B;
  struct _fat_ptr * _T2C;
  int _T2D;
  struct _fat_ptr _T2E;
  struct _fat_ptr _T2F;
  struct Cyc_String_pa_PrintArg_struct _T30;
  struct Cyc_Int_pa_PrintArg_struct _T31;
  int _T32;
  struct Cyc_String_pa_PrintArg_struct _T33;
  struct Cyc_Int_pa_PrintArg_struct _T34;
  int _T35;
  struct Cyc_String_pa_PrintArg_struct _T36;
  struct Cyc_Int_pa_PrintArg_struct _T37;
  int _T38;
  struct Cyc_String_pa_PrintArg_struct _T39;
  struct Cyc___cycFILE * _T3A;
  struct _fat_ptr _T3B;
  struct _fat_ptr _T3C;
  long reduced;
  _T1 = Cyc_nvars + 32;
  _T2 = _T1 - 1;
  _T3 = _T2 / 32;
  { unsigned int _T3D = (unsigned int)_T3;
    _T5 = _check_times(_T3D,sizeof(unsigned int));
    { unsigned int * _T3E = _cycalloc_atomic(_T5);
      { unsigned int _T3F = _T3D;
	unsigned int _new2_cyclone;
	_new2_cyclone = 0;
	_TL10: if (_new2_cyclone < _T3F) { goto _TLE;
	}else { goto _TLF;
	}
	_TLE: _T6 = _new2_cyclone;
	_T3E[_T6] = 0U;
	_new2_cyclone = _new2_cyclone + 1;
	goto _TL10;
	_TLF: ;
      }_T4 = (unsigned int *)_T3E;
    }_T0 = _tag_fat(_T4,sizeof(unsigned int),_T3D);
  }Cyc_N = _T0;
  _T8 = Cyc_nrules + 1;
  _T9 = _T8 + 32;
  _TA = _T9 - 1;
  _TB = _TA / 32;
  { unsigned int _T3D = (unsigned int)_TB;
    _TD = _check_times(_T3D,sizeof(unsigned int));
    { unsigned int * _T3E = _cycalloc_atomic(_TD);
      { unsigned int _T3F = _T3D;
	unsigned int _new2_cyclone;
	_new2_cyclone = 0;
	_TL14: if (_new2_cyclone < _T3F) { goto _TL12;
	}else { goto _TL13;
	}
	_TL12: _TE = _new2_cyclone;
	_T3E[_TE] = 0U;
	_new2_cyclone = _new2_cyclone + 1;
	goto _TL14;
	_TL13: ;
      }_TC = (unsigned int *)_T3E;
    }_T7 = _tag_fat(_TC,sizeof(unsigned int),_T3D);
  }Cyc_P = _T7;
  _T10 = Cyc_nsyms + 32;
  _T11 = _T10 - 1;
  _T12 = _T11 / 32;
  { unsigned int _T3D = (unsigned int)_T12;
    _T14 = _check_times(_T3D,sizeof(unsigned int));
    { unsigned int * _T3E = _cycalloc_atomic(_T14);
      { unsigned int _T3F = _T3D;
	unsigned int _new2_cyclone;
	_new2_cyclone = 0;
	_TL18: if (_new2_cyclone < _T3F) { goto _TL16;
	}else { goto _TL17;
	}
	_TL16: _T15 = _new2_cyclone;
	_T3E[_T15] = 0U;
	_new2_cyclone = _new2_cyclone + 1;
	goto _TL18;
	_TL17: ;
      }_T13 = (unsigned int *)_T3E;
    }_TF = _tag_fat(_T13,sizeof(unsigned int),_T3D);
  }Cyc_V = _TF;
  _T17 = Cyc_nsyms + 32;
  _T18 = _T17 - 1;
  _T19 = _T18 / 32;
  { unsigned int _T3D = (unsigned int)_T19;
    _T1B = _check_times(_T3D,sizeof(unsigned int));
    { unsigned int * _T3E = _cycalloc_atomic(_T1B);
      { unsigned int _T3F = _T3D;
	unsigned int _new2_cyclone;
	_new2_cyclone = 0;
	_TL1C: if (_new2_cyclone < _T3F) { goto _TL1A;
	}else { goto _TL1B;
	}
	_TL1A: _T1C = _new2_cyclone;
	_T3E[_T1C] = 0U;
	_new2_cyclone = _new2_cyclone + 1;
	goto _TL1C;
	_TL1B: ;
      }_T1A = (unsigned int *)_T3E;
    }_T16 = _tag_fat(_T1A,sizeof(unsigned int),_T3D);
  }Cyc_V1 = _T16;
  Cyc_useless_nonterminals();
  Cyc_inaccessable_symbols();
  _T1D = Cyc_nuseless_nonterminals + Cyc_nuseless_productions;
  reduced = _T1D > 0;
  _T1E = Cyc_verboseflag;
  if (! _T1E) { goto _TL1D;
  }
  Cyc_print_results();
  goto _TL1E;
  _TL1D: _TL1E: if (reduced != 0) { goto _TL1F;
  }
  goto done_reducing;
  _TL1F: Cyc_print_notices();
  _T1F = Cyc_N;
  _T20 = _T1F.curr;
  _T21 = (unsigned int *)_T20;
  _T22 = Cyc_start_symbol - Cyc_ntokens;
  _T23 = _T22 / 32;
  _T24 = _T21[_T23];
  _T25 = Cyc_start_symbol - Cyc_ntokens;
  _T26 = _T25 % 32;
  _T27 = 1U << _T26;
  _T28 = _T24 & _T27;
  if (_T28 != 0U) { goto _TL21;
  }else { goto _TL23;
  }
  _TL23: _T29 = _tag_fat("Start symbol %s does not derive any sentence",sizeof(char),
			 45U);
  _T2A = Cyc_tags;
  _T2B = _T2A.curr;
  _T2C = (struct _fat_ptr *)_T2B;
  _T2D = Cyc_start_symbol;
  _T2E = _T2C[_T2D];
  _T2F = _T2E;
  Cyc_fatals(_T29,_T2F);
  goto _TL22;
  _TL21: _TL22: Cyc_reduce_grammar_tables();
  Cyc_statisticsflag = 0;
  if (Cyc_statisticsflag != 1) { goto _TL24;
  }
  { struct Cyc_String_pa_PrintArg_struct _T3D;
    _T3D.tag = 0;
    _T3D.f1 = Cyc_infile;
    _T30 = _T3D;
  }{ struct Cyc_String_pa_PrintArg_struct _T3D = _T30;
    { struct Cyc_Int_pa_PrintArg_struct _T3E;
      _T3E.tag = 1;
      _T32 = Cyc_ntokens;
      _T3E.f1 = (unsigned long)_T32;
      _T31 = _T3E;
    }{ struct Cyc_Int_pa_PrintArg_struct _T3E = _T31;
      { struct Cyc_String_pa_PrintArg_struct _T3F;
	_T3F.tag = 0;
	if (Cyc_ntokens != 1) { goto _TL26;
	}
	_T3F.f1 = _tag_fat("",sizeof(char),1U);
	goto _TL27;
	_TL26: _T3F.f1 = _tag_fat("s",sizeof(char),2U);
	_TL27: _T33 = _T3F;
      }{ struct Cyc_String_pa_PrintArg_struct _T3F = _T33;
	{ struct Cyc_Int_pa_PrintArg_struct _T40;
	  _T40.tag = 1;
	  _T35 = Cyc_nvars;
	  _T40.f1 = (unsigned long)_T35;
	  _T34 = _T40;
	}{ struct Cyc_Int_pa_PrintArg_struct _T40 = _T34;
	  { struct Cyc_String_pa_PrintArg_struct _T41;
	    _T41.tag = 0;
	    if (Cyc_nvars != 1) { goto _TL28;
	    }
	    _T41.f1 = _tag_fat("",sizeof(char),1U);
	    goto _TL29;
	    _TL28: _T41.f1 = _tag_fat("s",sizeof(char),2U);
	    _TL29: _T36 = _T41;
	  }{ struct Cyc_String_pa_PrintArg_struct _T41 = _T36;
	    { struct Cyc_Int_pa_PrintArg_struct _T42;
	      _T42.tag = 1;
	      _T38 = Cyc_nrules;
	      _T42.f1 = (unsigned long)_T38;
	      _T37 = _T42;
	    }{ struct Cyc_Int_pa_PrintArg_struct _T42 = _T37;
	      { struct Cyc_String_pa_PrintArg_struct _T43;
		_T43.tag = 0;
		if (Cyc_nrules != 1) { goto _TL2A;
		}
		_T43.f1 = _tag_fat("",sizeof(char),1U);
		goto _TL2B;
		_TL2A: _T43.f1 = _tag_fat("s",sizeof(char),2U);
		_TL2B: _T39 = _T43;
	      }{ struct Cyc_String_pa_PrintArg_struct _T43 = _T39;
		void * _T44[7];
		_T44[0] = &_T3D;
		_T44[1] = &_T3E;
		_T44[2] = &_T3F;
		_T44[3] = &_T40;
		_T44[4] = &_T41;
		_T44[5] = &_T42;
		_T44[6] = &_T43;
		_T3A = Cyc_stderr;
		_T3B = _tag_fat("reduced %s defines %d terminal%s, %d nonterminal%s, and %d production%s.\n",
				sizeof(char),74U);
		_T3C = _tag_fat(_T44,sizeof(void *),7);
		Cyc_fprintf(_T3A,_T3B,_T3C);
	      }
	    }
	  }
	}
      }
    }
  }goto _TL25;
  _TL24: _TL25: done_reducing: Cyc_N = _tag_fat(0,0,0);
  Cyc_V = _tag_fat(0,0,0);
  Cyc_P = _tag_fat(0,0,0);
}
static long Cyc_useful_production(int i,struct _fat_ptr N) {
  struct _fat_ptr _T0;
  struct _fat_ptr _T1;
  int _T2;
  unsigned char * _T3;
  short * _T4;
  short _T5;
  int _T6;
  struct _fat_ptr _T7;
  unsigned char * _T8;
  short * _T9;
  short _TA;
  int _TB;
  struct _fat_ptr _TC;
  unsigned char * _TD;
  short * _TE;
  short _TF;
  int _T10;
  int _T11;
  struct _fat_ptr _T12;
  short _T13;
  int _T14;
  int _T15;
  int _T16;
  int _T17;
  unsigned char * _T18;
  unsigned int * _T19;
  unsigned int _T1A;
  short _T1B;
  int _T1C;
  int _T1D;
  int _T1E;
  int _T1F;
  unsigned int _T20;
  unsigned int _T21;
  struct _fat_ptr * _T22;
  struct _fat_ptr r;
  short n;
  _T0 = Cyc_ritem;
  _T1 = Cyc_rrhs;
  _T2 = i;
  _T3 = _check_fat_subscript(_T1,sizeof(short),_T2);
  _T4 = (short *)_T3;
  _T5 = *_T4;
  _T6 = (int)_T5;
  r = _fat_ptr_plus(_T0,sizeof(short),_T6);
  _TL2F: _T7 = r;
  _T8 = _check_fat_subscript(_T7,sizeof(short),0U);
  _T9 = (short *)_T8;
  _TA = *_T9;
  _TB = (int)_TA;
  if (_TB > 0) { goto _TL2D;
  }else { goto _TL2E;
  }
  _TL2D: _TC = r;
  _TD = _TC.curr;
  _TE = (short *)_TD;
  n = *_TE;
  _TF = n;
  _T10 = (int)_TF;
  _T11 = Cyc_ntokens;
  if (_T10 < _T11) { goto _TL30;
  }
  _T12 = N;
  _T13 = n;
  _T14 = (int)_T13;
  _T15 = Cyc_ntokens;
  _T16 = _T14 - _T15;
  _T17 = _T16 / 32;
  _T18 = _check_fat_subscript(_T12,sizeof(unsigned int),_T17);
  _T19 = (unsigned int *)_T18;
  _T1A = *_T19;
  _T1B = n;
  _T1C = (int)_T1B;
  _T1D = Cyc_ntokens;
  _T1E = _T1C - _T1D;
  _T1F = _T1E % 32;
  _T20 = 1U << _T1F;
  _T21 = _T1A & _T20;
  if (_T21 != 0U) { goto _TL32;
  }else { goto _TL34;
  }
  _TL34: return 0;
  _TL32: goto _TL31;
  _TL30: _TL31: _T22 = &r;
  _fat_ptr_inplace_plus(_T22,sizeof(short),1);
  goto _TL2F;
  _TL2E: return 1;
}
static void Cyc_useless_nonterminals() {
  struct _fat_ptr _T0;
  int _T1;
  int _T2;
  int _T3;
  unsigned int * _T4;
  unsigned int _T5;
  unsigned int _T6;
  int _T7;
  int _T8;
  int _T9;
  struct _fat_ptr _TA;
  int _TB;
  unsigned char * _TC;
  unsigned int * _TD;
  struct _fat_ptr _TE;
  int _TF;
  unsigned char * _T10;
  unsigned int * _T11;
  struct _fat_ptr _T12;
  int _T13;
  unsigned char * _T14;
  unsigned int * _T15;
  unsigned int _T16;
  int _T17;
  unsigned int _T18;
  unsigned int _T19;
  long _T1A;
  struct _fat_ptr _T1B;
  unsigned char * _T1C;
  unsigned int * _T1D;
  struct _fat_ptr _T1E;
  unsigned char * _T1F;
  short * _T20;
  int _T21;
  short _T22;
  int _T23;
  int _T24;
  int _T25;
  int _T26;
  struct _fat_ptr _T27;
  unsigned char * _T28;
  short * _T29;
  int _T2A;
  short _T2B;
  int _T2C;
  int _T2D;
  int _T2E;
  int _T2F;
  unsigned int _T30;
  struct _fat_ptr _T31;
  unsigned char * _T32;
  unsigned int * _T33;
  int _T34;
  int _T35;
  unsigned int _T36;
  struct _fat_ptr _T37;
  struct _fat_ptr _T38;
  int _T39;
  int _T3A;
  int _T3B;
  long _T3C;
  struct _fat_ptr Np;
  struct _fat_ptr Ns;
  int i;
  int n;
  _T1 = Cyc_nvars + 32;
  _T2 = _T1 - 1;
  _T3 = _T2 / 32;
  { unsigned int _T3D = (unsigned int)_T3;
    _T5 = _check_times(_T3D,sizeof(unsigned int));
    { unsigned int * _T3E = _cycalloc_atomic(_T5);
      { unsigned int _T3F = _T3D;
	unsigned int _new2_cyclone;
	_new2_cyclone = 0;
	_TL38: if (_new2_cyclone < _T3F) { goto _TL36;
	}else { goto _TL37;
	}
	_TL36: _T6 = _new2_cyclone;
	_T3E[_T6] = 0U;
	_new2_cyclone = _new2_cyclone + 1;
	goto _TL38;
	_TL37: ;
      }_T4 = (unsigned int *)_T3E;
    }_T0 = _tag_fat(_T4,sizeof(unsigned int),_T3D);
  }Np = _T0;
  n = 0;
  _TL39: if (1) { goto _TL3A;
  }else { goto _TL3B;
  }
  _TL3A: _T7 = Cyc_nvars + 32;
  _T8 = _T7 - 1;
  _T9 = _T8 / 32;
  i = _T9 - 1;
  _TL3F: if (i >= 0) { goto _TL3D;
  }else { goto _TL3E;
  }
  _TL3D: _TA = Np;
  _TB = i;
  _TC = _check_fat_subscript(_TA,sizeof(unsigned int),_TB);
  _TD = (unsigned int *)_TC;
  _TE = Cyc_N;
  _TF = i;
  _T10 = _check_fat_subscript(_TE,sizeof(unsigned int),_TF);
  _T11 = (unsigned int *)_T10;
  *_TD = *_T11;
  i = i + -1;
  goto _TL3F;
  _TL3E: i = 1;
  _TL43: if (i <= Cyc_nrules) { goto _TL41;
  }else { goto _TL42;
  }
  _TL41: _T12 = Cyc_P;
  _T13 = i / 32;
  _T14 = _check_fat_subscript(_T12,sizeof(unsigned int),_T13);
  _T15 = (unsigned int *)_T14;
  _T16 = *_T15;
  _T17 = i % 32;
  _T18 = 1U << _T17;
  _T19 = _T16 & _T18;
  if (_T19 != 0U) { goto _TL44;
  }else { goto _TL46;
  }
  _TL46: _T1A = Cyc_useful_production(i,Cyc_N);
  if (! _T1A) { goto _TL47;
  }
  _T1B = Np;
  _T1C = _T1B.curr;
  _T1D = (unsigned int *)_T1C;
  _T1E = Cyc_rlhs;
  _T1F = _T1E.curr;
  _T20 = (short *)_T1F;
  _T21 = i;
  _T22 = _T20[_T21];
  _T23 = (int)_T22;
  _T24 = Cyc_ntokens;
  _T25 = _T23 - _T24;
  _T26 = _T25 / 32;
  _T27 = Cyc_rlhs;
  _T28 = _T27.curr;
  _T29 = (short *)_T28;
  _T2A = i;
  _T2B = _T29[_T2A];
  _T2C = (int)_T2B;
  _T2D = Cyc_ntokens;
  _T2E = _T2C - _T2D;
  _T2F = _T2E % 32;
  _T30 = 1U << _T2F;
  _T1D[_T26] = _T1D[_T26] | _T30;
  _T31 = Cyc_P;
  _T32 = _T31.curr;
  _T33 = (unsigned int *)_T32;
  _T34 = i / 32;
  _T35 = i % 32;
  _T36 = 1U << _T35;
  _T33[_T34] = _T33[_T34] | _T36;
  goto _TL48;
  _TL47: _TL48: goto _TL45;
  _TL44: _TL45: i = i + 1;
  goto _TL43;
  _TL42: _T37 = Cyc_N;
  _T38 = Np;
  _T39 = Cyc_nvars + 32;
  _T3A = _T39 - 1;
  _T3B = _T3A / 32;
  _T3C = Cyc_bits_equal(_T37,_T38,_T3B);
  if (! _T3C) { goto _TL49;
  }
  goto _TL3B;
  _TL49: Ns = Np;
  Np = Cyc_N;
  Cyc_N = Ns;
  goto _TL39;
  _TL3B: Cyc_N = _tag_fat(0,0,0);
  Cyc_N = Np;
}
static void Cyc_inaccessable_symbols() {
  struct _fat_ptr _T0;
  int _T1;
  int _T2;
  int _T3;
  unsigned int * _T4;
  unsigned int _T5;
  unsigned int _T6;
  struct _fat_ptr _T7;
  int _T8;
  int _T9;
  int _TA;
  int _TB;
  unsigned int * _TC;
  unsigned int _TD;
  unsigned int _TE;
  struct _fat_ptr _TF;
  int _T10;
  int _T11;
  unsigned char * _T12;
  unsigned int * _T13;
  unsigned int _T14;
  int _T15;
  int _T16;
  unsigned int _T17;
  unsigned int _T18;
  struct _fat_ptr _T19;
  int _T1A;
  unsigned char * _T1B;
  unsigned int * _T1C;
  int _T1D;
  unsigned int _T1E;
  int _T1F;
  int _T20;
  int _T21;
  struct _fat_ptr _T22;
  int _T23;
  unsigned char * _T24;
  unsigned int * _T25;
  struct _fat_ptr _T26;
  int _T27;
  unsigned char * _T28;
  unsigned int * _T29;
  struct _fat_ptr _T2A;
  int _T2B;
  unsigned char * _T2C;
  unsigned int * _T2D;
  unsigned int _T2E;
  int _T2F;
  unsigned int _T30;
  unsigned int _T31;
  struct _fat_ptr _T32;
  int _T33;
  unsigned char * _T34;
  unsigned int * _T35;
  unsigned int _T36;
  int _T37;
  unsigned int _T38;
  unsigned int _T39;
  struct _fat_ptr _T3A;
  struct _fat_ptr _T3B;
  int _T3C;
  unsigned char * _T3D;
  short * _T3E;
  short _T3F;
  int _T40;
  int _T41;
  unsigned char * _T42;
  unsigned int * _T43;
  unsigned int _T44;
  struct _fat_ptr _T45;
  unsigned char * _T46;
  short * _T47;
  int _T48;
  short _T49;
  int _T4A;
  int _T4B;
  unsigned int _T4C;
  unsigned int _T4D;
  struct _fat_ptr _T4E;
  struct _fat_ptr _T4F;
  int _T50;
  unsigned char * _T51;
  short * _T52;
  short _T53;
  int _T54;
  struct _fat_ptr _T55;
  unsigned char * _T56;
  short * _T57;
  short _T58;
  int _T59;
  struct _fat_ptr _T5A;
  unsigned char * _T5B;
  short * _T5C;
  short _T5D;
  int _T5E;
  int _T5F;
  struct _fat_ptr _T60;
  short _T61;
  int _T62;
  int _T63;
  int _T64;
  int _T65;
  unsigned char * _T66;
  unsigned int * _T67;
  unsigned int _T68;
  short _T69;
  int _T6A;
  int _T6B;
  int _T6C;
  int _T6D;
  unsigned int _T6E;
  unsigned int _T6F;
  struct _fat_ptr _T70;
  short _T71;
  int _T72;
  int _T73;
  unsigned char * _T74;
  unsigned int * _T75;
  short _T76;
  int _T77;
  int _T78;
  unsigned int _T79;
  struct _fat_ptr * _T7A;
  struct _fat_ptr _T7B;
  unsigned char * _T7C;
  unsigned int * _T7D;
  int _T7E;
  int _T7F;
  unsigned int _T80;
  struct _fat_ptr _T81;
  struct _fat_ptr _T82;
  int _T83;
  int _T84;
  int _T85;
  long _T86;
  struct _fat_ptr _T87;
  unsigned char * _T88;
  unsigned int * _T89;
  int _T8A;
  unsigned int _T8B;
  struct _fat_ptr _T8C;
  unsigned char * _T8D;
  unsigned int * _T8E;
  int _T8F;
  unsigned int _T90;
  struct _fat_ptr _T91;
  unsigned char * _T92;
  unsigned int * _T93;
  int _T94;
  unsigned int _T95;
  struct _fat_ptr _T96;
  int _T97;
  int _T98;
  int _T99;
  int _T9A;
  struct _fat_ptr _T9B;
  int _T9C;
  unsigned char * _T9D;
  unsigned int * _T9E;
  unsigned int _T9F;
  int _TA0;
  unsigned int _TA1;
  unsigned int _TA2;
  struct _fat_ptr _TA3;
  int _TA4;
  unsigned char * _TA5;
  short * _TA6;
  short _TA7;
  int _TA8;
  struct _fat_ptr _TA9;
  struct _fat_ptr _TAA;
  unsigned char * _TAB;
  short * _TAC;
  int _TAD;
  short _TAE;
  int _TAF;
  int _TB0;
  unsigned char * _TB1;
  unsigned int * _TB2;
  struct _fat_ptr _TB3;
  unsigned char * _TB4;
  short * _TB5;
  int _TB6;
  short _TB7;
  int _TB8;
  int _TB9;
  unsigned int _TBA;
  struct _fat_ptr Vp;
  struct _fat_ptr Vs;
  struct _fat_ptr Pp;
  int i;
  int n;
  short t;
  struct _fat_ptr r;
  _T1 = Cyc_nsyms + 32;
  _T2 = _T1 - 1;
  _T3 = _T2 / 32;
  { unsigned int _TBB = (unsigned int)_T3;
    _T5 = _check_times(_TBB,sizeof(unsigned int));
    { unsigned int * _TBC = _cycalloc_atomic(_T5);
      { unsigned int _TBD = _TBB;
	unsigned int _new2_cyclone;
	_new2_cyclone = 0;
	_TL4E: if (_new2_cyclone < _TBD) { goto _TL4C;
	}else { goto _TL4D;
	}
	_TL4C: _T6 = _new2_cyclone;
	_TBC[_T6] = 0U;
	_new2_cyclone = _new2_cyclone + 1;
	goto _TL4E;
	_TL4D: ;
      }_T4 = (unsigned int *)_TBC;
    }_T0 = _tag_fat(_T4,sizeof(unsigned int),_TBB);
  }Vp = _T0;
  _T8 = Cyc_nrules + 1;
  _T9 = _T8 + 32;
  _TA = _T9 - 1;
  _TB = _TA / 32;
  { unsigned int _TBB = (unsigned int)_TB;
    _TD = _check_times(_TBB,sizeof(unsigned int));
    { unsigned int * _TBC = _cycalloc_atomic(_TD);
      { unsigned int _TBD = _TBB;
	unsigned int _new2_cyclone;
	_new2_cyclone = 0;
	_TL52: if (_new2_cyclone < _TBD) { goto _TL50;
	}else { goto _TL51;
	}
	_TL50: _TE = _new2_cyclone;
	_TBC[_TE] = 0U;
	_new2_cyclone = _new2_cyclone + 1;
	goto _TL52;
	_TL51: ;
      }_TC = (unsigned int *)_TBC;
    }_T7 = _tag_fat(_TC,sizeof(unsigned int),_TBB);
  }Pp = _T7;
  _TF = Cyc_N;
  _T10 = Cyc_start_symbol - Cyc_ntokens;
  _T11 = _T10 / 32;
  _T12 = _check_fat_subscript(_TF,sizeof(unsigned int),_T11);
  _T13 = (unsigned int *)_T12;
  _T14 = *_T13;
  _T15 = Cyc_start_symbol - Cyc_ntokens;
  _T16 = _T15 % 32;
  _T17 = 1U << _T16;
  _T18 = _T14 & _T17;
  if (_T18 != 0U) { goto _TL53;
  }else { goto _TL55;
  }
  _TL55: goto end_iteration;
  _TL53: _T19 = Cyc_V;
  _T1A = Cyc_start_symbol / 32;
  _T1B = _check_fat_subscript(_T19,sizeof(unsigned int),_T1A);
  _T1C = (unsigned int *)_T1B;
  _T1D = Cyc_start_symbol % 32;
  _T1E = 1U << _T1D;
  *_T1C = *_T1C | _T1E;
  n = 0;
  _TL56: if (1) { goto _TL57;
  }else { goto _TL58;
  }
  _TL57: _T1F = Cyc_nsyms + 32;
  _T20 = _T1F - 1;
  _T21 = _T20 / 32;
  i = _T21 - 1;
  _TL5C: if (i >= 0) { goto _TL5A;
  }else { goto _TL5B;
  }
  _TL5A: _T22 = Vp;
  _T23 = i;
  _T24 = _check_fat_subscript(_T22,sizeof(unsigned int),_T23);
  _T25 = (unsigned int *)_T24;
  _T26 = Cyc_V;
  _T27 = i;
  _T28 = _check_fat_subscript(_T26,sizeof(unsigned int),_T27);
  _T29 = (unsigned int *)_T28;
  *_T25 = *_T29;
  i = i + -1;
  goto _TL5C;
  _TL5B: i = 1;
  _TL60: if (i <= Cyc_nrules) { goto _TL5E;
  }else { goto _TL5F;
  }
  _TL5E: _T2A = Pp;
  _T2B = i / 32;
  _T2C = _check_fat_subscript(_T2A,sizeof(unsigned int),_T2B);
  _T2D = (unsigned int *)_T2C;
  _T2E = *_T2D;
  _T2F = i % 32;
  _T30 = 1U << _T2F;
  _T31 = _T2E & _T30;
  if (_T31 != 0U) { goto _TL61;
  }else { goto _TL63;
  }
  _TL63: _T32 = Cyc_P;
  _T33 = i / 32;
  _T34 = _check_fat_subscript(_T32,sizeof(unsigned int),_T33);
  _T35 = (unsigned int *)_T34;
  _T36 = *_T35;
  _T37 = i % 32;
  _T38 = 1U << _T37;
  _T39 = _T36 & _T38;
  if (_T39 == 0U) { goto _TL61;
  }
  _T3A = Cyc_V;
  _T3B = Cyc_rlhs;
  _T3C = i;
  _T3D = _check_fat_subscript(_T3B,sizeof(short),_T3C);
  _T3E = (short *)_T3D;
  _T3F = *_T3E;
  _T40 = (int)_T3F;
  _T41 = _T40 / 32;
  _T42 = _check_fat_subscript(_T3A,sizeof(unsigned int),_T41);
  _T43 = (unsigned int *)_T42;
  _T44 = *_T43;
  _T45 = Cyc_rlhs;
  _T46 = _T45.curr;
  _T47 = (short *)_T46;
  _T48 = i;
  _T49 = _T47[_T48];
  _T4A = (int)_T49;
  _T4B = _T4A % 32;
  _T4C = 1U << _T4B;
  _T4D = _T44 & _T4C;
  if (_T4D == 0U) { goto _TL61;
  }
  _T4E = Cyc_ritem;
  _T4F = Cyc_rrhs;
  _T50 = i;
  _T51 = _check_fat_subscript(_T4F,sizeof(short),_T50);
  _T52 = (short *)_T51;
  _T53 = *_T52;
  _T54 = (int)_T53;
  r = _fat_ptr_plus(_T4E,sizeof(short),_T54);
  _TL67: _T55 = r;
  _T56 = _check_fat_subscript(_T55,sizeof(short),0U);
  _T57 = (short *)_T56;
  _T58 = *_T57;
  _T59 = (int)_T58;
  if (_T59 >= 0) { goto _TL65;
  }else { goto _TL66;
  }
  _TL65: _T5A = r;
  _T5B = _T5A.curr;
  _T5C = (short *)_T5B;
  t = *_T5C;
  _T5D = t;
  _T5E = (int)_T5D;
  _T5F = Cyc_ntokens;
  if (_T5E < _T5F) { goto _TL6A;
  }else { goto _TL6B;
  }
  _TL6B: _T60 = Cyc_N;
  _T61 = t;
  _T62 = (int)_T61;
  _T63 = Cyc_ntokens;
  _T64 = _T62 - _T63;
  _T65 = _T64 / 32;
  _T66 = _check_fat_subscript(_T60,sizeof(unsigned int),_T65);
  _T67 = (unsigned int *)_T66;
  _T68 = *_T67;
  _T69 = t;
  _T6A = (int)_T69;
  _T6B = Cyc_ntokens;
  _T6C = _T6A - _T6B;
  _T6D = _T6C % 32;
  _T6E = 1U << _T6D;
  _T6F = _T68 & _T6E;
  if (_T6F != 0U) { goto _TL6A;
  }else { goto _TL68;
  }
  _TL6A: _T70 = Vp;
  _T71 = t;
  _T72 = (int)_T71;
  _T73 = _T72 / 32;
  _T74 = _check_fat_subscript(_T70,sizeof(unsigned int),_T73);
  _T75 = (unsigned int *)_T74;
  _T76 = t;
  _T77 = (int)_T76;
  _T78 = _T77 % 32;
  _T79 = 1U << _T78;
  *_T75 = *_T75 | _T79;
  goto _TL69;
  _TL68: _TL69: _T7A = &r;
  _fat_ptr_inplace_plus(_T7A,sizeof(short),1);
  goto _TL67;
  _TL66: _T7B = Pp;
  _T7C = _T7B.curr;
  _T7D = (unsigned int *)_T7C;
  _T7E = i / 32;
  _T7F = i % 32;
  _T80 = 1U << _T7F;
  _T7D[_T7E] = _T7D[_T7E] | _T80;
  goto _TL62;
  _TL61: _TL62: i = i + 1;
  goto _TL60;
  _TL5F: _T81 = Cyc_V;
  _T82 = Vp;
  _T83 = Cyc_nsyms + 32;
  _T84 = _T83 - 1;
  _T85 = _T84 / 32;
  _T86 = Cyc_bits_equal(_T81,_T82,_T85);
  if (! _T86) { goto _TL6C;
  }
  goto _TL58;
  _TL6C: Vs = Vp;
  Vp = Cyc_V;
  Cyc_V = Vs;
  goto _TL56;
  _TL58: end_iteration: Cyc_V = _tag_fat(0,0,0);
  Cyc_V = Vp;
  _T87 = Cyc_V;
  _T88 = _check_fat_subscript(_T87,sizeof(unsigned int),0);
  _T89 = (unsigned int *)_T88;
  _T8A = 0 % 32;
  _T8B = 1U << _T8A;
  *_T89 = *_T89 | _T8B;
  _T8C = Cyc_V;
  _T8D = _T8C.curr;
  _T8E = (unsigned int *)_T8D;
  _T8F = 1 % 32;
  _T90 = 1U << _T8F;
  _T8E[0] = _T8E[0] | _T90;
  _T91 = Cyc_V;
  _T92 = _T91.curr;
  _T93 = (unsigned int *)_T92;
  _T94 = 2 % 32;
  _T95 = 1U << _T94;
  _T93[0] = _T93[0] | _T95;
  Cyc_P = _tag_fat(0,0,0);
  Cyc_P = Pp;
  _T96 = Cyc_P;
  _T97 = Cyc_nrules + 1;
  _T98 = _T97 + 32;
  _T99 = _T98 - 1;
  _T9A = _T99 / 32;
  Cyc_nuseful_productions = Cyc_bits_size(_T96,_T9A);
  Cyc_nuseless_productions = Cyc_nrules - Cyc_nuseful_productions;
  Cyc_nuseful_nonterminals = 0;
  i = Cyc_ntokens;
  _TL71: if (i < Cyc_nsyms) { goto _TL6F;
  }else { goto _TL70;
  }
  _TL6F: _T9B = Cyc_V;
  _T9C = i / 32;
  _T9D = _check_fat_subscript(_T9B,sizeof(unsigned int),_T9C);
  _T9E = (unsigned int *)_T9D;
  _T9F = *_T9E;
  _TA0 = i % 32;
  _TA1 = 1U << _TA0;
  _TA2 = _T9F & _TA1;
  if (_TA2 == 0U) { goto _TL72;
  }
  Cyc_nuseful_nonterminals = Cyc_nuseful_nonterminals + 1;
  goto _TL73;
  _TL72: _TL73: i = i + 1;
  goto _TL71;
  _TL70: Cyc_nuseless_nonterminals = Cyc_nvars - Cyc_nuseful_nonterminals;
  i = 1;
  _TL77: if (i < Cyc_nrules) { goto _TL75;
  }else { goto _TL76;
  }
  _TL75: _TA3 = Cyc_rprecsym;
  _TA4 = i;
  _TA5 = _check_fat_subscript(_TA3,sizeof(short),_TA4);
  _TA6 = (short *)_TA5;
  _TA7 = *_TA6;
  _TA8 = (int)_TA7;
  if (_TA8 == 0) { goto _TL78;
  }
  _TA9 = Cyc_V1;
  _TAA = Cyc_rprecsym;
  _TAB = _TAA.curr;
  _TAC = (short *)_TAB;
  _TAD = i;
  _TAE = _TAC[_TAD];
  _TAF = (int)_TAE;
  _TB0 = _TAF / 32;
  _TB1 = _check_fat_subscript(_TA9,sizeof(unsigned int),_TB0);
  _TB2 = (unsigned int *)_TB1;
  _TB3 = Cyc_rprecsym;
  _TB4 = _TB3.curr;
  _TB5 = (short *)_TB4;
  _TB6 = i;
  _TB7 = _TB5[_TB6];
  _TB8 = (int)_TB7;
  _TB9 = _TB8 % 32;
  _TBA = 1U << _TB9;
  *_TB2 = *_TB2 | _TBA;
  goto _TL79;
  _TL78: _TL79: i = i + 1;
  goto _TL77;
  _TL76: ;
}
static void Cyc_reduce_grammar_tables() {
  struct _fat_ptr _T0;
  int _T1;
  unsigned char * _T2;
  unsigned int * _T3;
  unsigned int _T4;
  int _T5;
  unsigned int _T6;
  unsigned int _T7;
  struct _fat_ptr _T8;
  int _T9;
  unsigned char * _TA;
  short * _TB;
  struct _fat_ptr _TC;
  int _TD;
  short * _TE;
  unsigned int _TF;
  unsigned int _T10;
  struct _fat_ptr _T11;
  int _T12;
  struct _fat_ptr _T13;
  int _T14;
  unsigned char * _T15;
  short * _T16;
  struct _fat_ptr _T17;
  int _T18;
  unsigned char * _T19;
  unsigned int * _T1A;
  unsigned int _T1B;
  int _T1C;
  unsigned int _T1D;
  unsigned int _T1E;
  struct _fat_ptr _T1F;
  int _T20;
  unsigned char * _T21;
  short * _T22;
  int _T23;
  int _T24;
  struct _fat_ptr _T25;
  int _T26;
  unsigned char * _T27;
  short * _T28;
  short _T29;
  struct _fat_ptr _T2A;
  int _T2B;
  unsigned char * _T2C;
  short * _T2D;
  struct _fat_ptr _T2E;
  int _T2F;
  unsigned char * _T30;
  short * _T31;
  struct _fat_ptr _T32;
  int _T33;
  unsigned char * _T34;
  short * _T35;
  struct _fat_ptr _T36;
  int _T37;
  unsigned char * _T38;
  short * _T39;
  struct _fat_ptr _T3A;
  int _T3B;
  unsigned char * _T3C;
  struct _fat_ptr * _T3D;
  struct _fat_ptr _T3E;
  int _T3F;
  unsigned char * _T40;
  struct _fat_ptr * _T41;
  struct _fat_ptr _T42;
  int _T43;
  unsigned char * _T44;
  struct _fat_ptr * _T45;
  struct _fat_ptr _T46;
  int _T47;
  unsigned char * _T48;
  short * _T49;
  short _T4A;
  int _T4B;
  struct _fat_ptr _T4C;
  unsigned char * _T4D;
  short * _T4E;
  int _T4F;
  struct _fat_ptr _T50;
  struct _fat_ptr _T51;
  unsigned char * _T52;
  short * _T53;
  int _T54;
  short _T55;
  int _T56;
  unsigned char * _T57;
  short * _T58;
  struct _fat_ptr _T59;
  int _T5A;
  unsigned char * _T5B;
  short * _T5C;
  short _T5D;
  int _T5E;
  int _T5F;
  struct _fat_ptr _T60;
  unsigned char * _T61;
  short * _T62;
  int _T63;
  struct _fat_ptr _T64;
  struct _fat_ptr _T65;
  unsigned char * _T66;
  short * _T67;
  int _T68;
  short _T69;
  int _T6A;
  unsigned char * _T6B;
  short * _T6C;
  struct _fat_ptr _T6D;
  unsigned char * _T6E;
  short * _T6F;
  short _T70;
  int _T71;
  struct _fat_ptr _T72;
  unsigned char * _T73;
  short * _T74;
  short _T75;
  int _T76;
  int _T77;
  struct _fat_ptr _T78;
  unsigned char * _T79;
  short * _T7A;
  struct _fat_ptr _T7B;
  struct _fat_ptr _T7C;
  unsigned char * _T7D;
  short * _T7E;
  short _T7F;
  int _T80;
  unsigned char * _T81;
  short * _T82;
  struct _fat_ptr * _T83;
  struct _fat_ptr _T84;
  int _T85;
  unsigned char * _T86;
  short * _T87;
  short _T88;
  int _T89;
  int _T8A;
  if (Cyc_nuseless_productions <= 0) { goto _TL7A;
  }
  { int pn;
    pn = 1;
    _TL7F: if (pn <= Cyc_nrules) { goto _TL7D;
    }else { goto _TL7E;
    }
    _TL7D: _T0 = Cyc_P;
    _T1 = pn / 32;
    _T2 = _check_fat_subscript(_T0,sizeof(unsigned int),_T1);
    _T3 = (unsigned int *)_T2;
    _T4 = *_T3;
    _T5 = pn % 32;
    _T6 = 1U << _T5;
    _T7 = _T4 & _T6;
    if (_T7 != 0U) { goto _TL80;
    }else { goto _TL82;
    }
    _TL82: _T8 = Cyc_rlhs;
    _T9 = pn;
    _TA = _check_fat_subscript(_T8,sizeof(short),_T9);
    _TB = (short *)_TA;
    *_TB = - 1;
    goto _TL81;
    _TL80: _TL81: pn = pn + 1;
    goto _TL7F;
    _TL7E: ;
  }goto _TL7B;
  _TL7A: _TL7B: if (Cyc_nuseless_nonterminals <= 0) { goto _TL83;
  }
  { int i;
    int n;
    struct _fat_ptr nontermmap;
    struct _fat_ptr r;
    _TD = Cyc_nvars;
    { unsigned int _T8B = (unsigned int)_TD;
      _TF = _check_times(_T8B,sizeof(short));
      { short * _T8C = _cycalloc_atomic(_TF);
	{ unsigned int _T8D = _T8B;
	  unsigned int _new2_cyclone;
	  _new2_cyclone = 0;
	  _TL88: if (_new2_cyclone < _T8D) { goto _TL86;
	  }else { goto _TL87;
	  }
	  _TL86: _T10 = _new2_cyclone;
	  _T8C[_T10] = 0;
	  _new2_cyclone = _new2_cyclone + 1;
	  goto _TL88;
	  _TL87: ;
	}_TE = (short *)_T8C;
      }_TC = _tag_fat(_TE,sizeof(short),_T8B);
    }_T11 = _TC;
    _T12 = - Cyc_ntokens;
    nontermmap = _fat_ptr_plus(_T11,sizeof(short),_T12);
    i = Cyc_ntokens;
    _TL8C: if (i < Cyc_nsyms) { goto _TL8A;
    }else { goto _TL8B;
    }
    _TL8A: _T13 = nontermmap;
    _T14 = i;
    _T15 = _check_fat_subscript(_T13,sizeof(short),_T14);
    _T16 = (short *)_T15;
    *_T16 = - 1;
    i = i + 1;
    goto _TL8C;
    _TL8B: n = Cyc_ntokens;
    i = Cyc_ntokens;
    _TL90: if (i < Cyc_nsyms) { goto _TL8E;
    }else { goto _TL8F;
    }
    _TL8E: _T17 = Cyc_V;
    _T18 = i / 32;
    _T19 = _check_fat_subscript(_T17,sizeof(unsigned int),_T18);
    _T1A = (unsigned int *)_T19;
    _T1B = *_T1A;
    _T1C = i % 32;
    _T1D = 1U << _T1C;
    _T1E = _T1B & _T1D;
    if (_T1E == 0U) { goto _TL91;
    }
    _T1F = nontermmap;
    _T20 = i;
    _T21 = _check_fat_subscript(_T1F,sizeof(short),_T20);
    _T22 = (short *)_T21;
    _T23 = n;
    n = _T23 + 1;
    _T24 = _T23;
    *_T22 = (short)_T24;
    goto _TL92;
    _TL91: _TL92: i = i + 1;
    goto _TL90;
    _TL8F: i = Cyc_ntokens;
    _TL96: if (i < Cyc_nsyms) { goto _TL94;
    }else { goto _TL95;
    }
    _TL94: _T25 = nontermmap;
    _T26 = i;
    _T27 = _check_fat_subscript(_T25,sizeof(short),_T26);
    _T28 = (short *)_T27;
    _T29 = *_T28;
    n = (int)_T29;
    if (n < 0) { goto _TL97;
    }
    _T2A = Cyc_sassoc;
    _T2B = n;
    _T2C = _check_fat_subscript(_T2A,sizeof(short),_T2B);
    _T2D = (short *)_T2C;
    _T2E = Cyc_sassoc;
    _T2F = i;
    _T30 = _check_fat_subscript(_T2E,sizeof(short),_T2F);
    _T31 = (short *)_T30;
    *_T2D = *_T31;
    _T32 = Cyc_sprec;
    _T33 = n;
    _T34 = _check_fat_subscript(_T32,sizeof(short),_T33);
    _T35 = (short *)_T34;
    _T36 = Cyc_sprec;
    _T37 = i;
    _T38 = _check_fat_subscript(_T36,sizeof(short),_T37);
    _T39 = (short *)_T38;
    *_T35 = *_T39;
    _T3A = Cyc_tags;
    _T3B = n;
    _T3C = _check_fat_subscript(_T3A,sizeof(struct _fat_ptr),_T3B);
    _T3D = (struct _fat_ptr *)_T3C;
    _T3E = Cyc_tags;
    _T3F = i;
    _T40 = _check_fat_subscript(_T3E,sizeof(struct _fat_ptr),_T3F);
    _T41 = (struct _fat_ptr *)_T40;
    *_T3D = *_T41;
    goto _TL98;
    _TL97: _T42 = Cyc_tags;
    _T43 = i;
    _T44 = _check_fat_subscript(_T42,sizeof(struct _fat_ptr),_T43);
    _T45 = (struct _fat_ptr *)_T44;
    *_T45 = _tag_fat(0,0,0);
    _TL98: i = i + 1;
    goto _TL96;
    _TL95: i = 1;
    _TL9C: if (i <= Cyc_nrules) { goto _TL9A;
    }else { goto _TL9B;
    }
    _TL9A: _T46 = Cyc_rlhs;
    _T47 = i;
    _T48 = _check_fat_subscript(_T46,sizeof(short),_T47);
    _T49 = (short *)_T48;
    _T4A = *_T49;
    _T4B = (int)_T4A;
    if (_T4B < 0) { goto _TL9D;
    }
    _T4C = Cyc_rlhs;
    _T4D = _T4C.curr;
    _T4E = (short *)_T4D;
    _T4F = i;
    _T50 = nontermmap;
    _T51 = Cyc_rlhs;
    _T52 = _T51.curr;
    _T53 = (short *)_T52;
    _T54 = i;
    _T55 = _T53[_T54];
    _T56 = (int)_T55;
    _T57 = _check_fat_subscript(_T50,sizeof(short),_T56);
    _T58 = (short *)_T57;
    _T4E[_T4F] = *_T58;
    goto _TL9E;
    _TL9D: _TL9E: _T59 = Cyc_rprecsym;
    _T5A = i;
    _T5B = _check_fat_subscript(_T59,sizeof(short),_T5A);
    _T5C = (short *)_T5B;
    _T5D = *_T5C;
    _T5E = (int)_T5D;
    _T5F = Cyc_ntokens;
    if (_T5E < _T5F) { goto _TL9F;
    }
    _T60 = Cyc_rprecsym;
    _T61 = _T60.curr;
    _T62 = (short *)_T61;
    _T63 = i;
    _T64 = nontermmap;
    _T65 = Cyc_rprecsym;
    _T66 = _T65.curr;
    _T67 = (short *)_T66;
    _T68 = i;
    _T69 = _T67[_T68];
    _T6A = (int)_T69;
    _T6B = _check_fat_subscript(_T64,sizeof(short),_T6A);
    _T6C = (short *)_T6B;
    _T62[_T63] = *_T6C;
    goto _TLA0;
    _TL9F: _TLA0: i = i + 1;
    goto _TL9C;
    _TL9B: r = Cyc_ritem;
    _TLA4: _T6D = r;
    _T6E = _check_fat_subscript(_T6D,sizeof(short),0U);
    _T6F = (short *)_T6E;
    _T70 = *_T6F;
    _T71 = (int)_T70;
    if (_T71) { goto _TLA2;
    }else { goto _TLA3;
    }
    _TLA2: _T72 = r;
    _T73 = _T72.curr;
    _T74 = (short *)_T73;
    _T75 = *_T74;
    _T76 = (int)_T75;
    _T77 = Cyc_ntokens;
    if (_T76 < _T77) { goto _TLA5;
    }
    _T78 = r;
    _T79 = _T78.curr;
    _T7A = (short *)_T79;
    _T7B = nontermmap;
    _T7C = r;
    _T7D = _T7C.curr;
    _T7E = (short *)_T7D;
    _T7F = *_T7E;
    _T80 = (int)_T7F;
    _T81 = _check_fat_subscript(_T7B,sizeof(short),_T80);
    _T82 = (short *)_T81;
    *_T7A = *_T82;
    goto _TLA6;
    _TLA5: _TLA6: _T83 = &r;
    _fat_ptr_inplace_plus(_T83,sizeof(short),1);
    goto _TLA4;
    _TLA3: _T84 = nontermmap;
    _T85 = Cyc_start_symbol;
    _T86 = _check_fat_subscript(_T84,sizeof(short),_T85);
    _T87 = (short *)_T86;
    _T88 = *_T87;
    Cyc_start_symbol = (int)_T88;
    _T89 = Cyc_nuseless_nonterminals;
    Cyc_nsyms = Cyc_nsyms - _T89;
    _T8A = Cyc_nuseless_nonterminals;
    Cyc_nvars = Cyc_nvars - _T8A;
  }goto _TL84;
  _TL83: _TL84: ;
}
static void Cyc_print_results() {
  struct Cyc___cycFILE * _T0;
  struct _fat_ptr _T1;
  struct _fat_ptr _T2;
  struct _fat_ptr _T3;
  int _T4;
  unsigned char * _T5;
  unsigned int * _T6;
  unsigned int _T7;
  int _T8;
  unsigned int _T9;
  unsigned int _TA;
  struct Cyc_String_pa_PrintArg_struct _TB;
  struct _fat_ptr _TC;
  int _TD;
  unsigned char * _TE;
  struct _fat_ptr * _TF;
  struct _fat_ptr _T10;
  struct Cyc___cycFILE * _T11;
  struct _fat_ptr _T12;
  struct _fat_ptr _T13;
  struct _fat_ptr _T14;
  int _T15;
  unsigned char * _T16;
  unsigned int * _T17;
  unsigned int _T18;
  int _T19;
  unsigned int _T1A;
  unsigned int _T1B;
  struct _fat_ptr _T1C;
  int _T1D;
  unsigned char * _T1E;
  unsigned int * _T1F;
  unsigned int _T20;
  int _T21;
  unsigned int _T22;
  unsigned int _T23;
  long _T24;
  struct Cyc___cycFILE * _T25;
  struct _fat_ptr _T26;
  struct _fat_ptr _T27;
  struct Cyc_String_pa_PrintArg_struct _T28;
  struct _fat_ptr _T29;
  int _T2A;
  unsigned char * _T2B;
  struct _fat_ptr * _T2C;
  struct _fat_ptr _T2D;
  struct Cyc___cycFILE * _T2E;
  struct _fat_ptr _T2F;
  struct _fat_ptr _T30;
  struct Cyc___cycFILE * _T31;
  struct _fat_ptr _T32;
  struct _fat_ptr _T33;
  struct _fat_ptr _T34;
  int _T35;
  unsigned char * _T36;
  unsigned int * _T37;
  unsigned int _T38;
  int _T39;
  unsigned int _T3A;
  unsigned int _T3B;
  struct Cyc_Int_pa_PrintArg_struct _T3C;
  int _T3D;
  struct Cyc___cycFILE * _T3E;
  struct _fat_ptr _T3F;
  struct _fat_ptr _T40;
  struct Cyc_String_pa_PrintArg_struct _T41;
  struct _fat_ptr _T42;
  struct _fat_ptr _T43;
  int _T44;
  unsigned char * _T45;
  short * _T46;
  short _T47;
  int _T48;
  unsigned char * _T49;
  struct _fat_ptr * _T4A;
  struct _fat_ptr _T4B;
  struct Cyc___cycFILE * _T4C;
  struct _fat_ptr _T4D;
  struct _fat_ptr _T4E;
  struct _fat_ptr _T4F;
  struct _fat_ptr _T50;
  int _T51;
  unsigned char * _T52;
  short * _T53;
  short _T54;
  int _T55;
  struct _fat_ptr _T56;
  unsigned char * _T57;
  short * _T58;
  short _T59;
  int _T5A;
  struct Cyc_String_pa_PrintArg_struct _T5B;
  struct _fat_ptr _T5C;
  struct _fat_ptr _T5D;
  unsigned char * _T5E;
  short * _T5F;
  short _T60;
  int _T61;
  unsigned char * _T62;
  struct _fat_ptr * _T63;
  struct _fat_ptr _T64;
  struct Cyc___cycFILE * _T65;
  struct _fat_ptr _T66;
  struct _fat_ptr _T67;
  struct _fat_ptr * _T68;
  struct Cyc___cycFILE * _T69;
  struct _fat_ptr _T6A;
  struct _fat_ptr _T6B;
  long _T6C;
  struct Cyc___cycFILE * _T6D;
  struct _fat_ptr _T6E;
  struct _fat_ptr _T6F;
  int i;
  struct _fat_ptr r;
  long b;
  if (Cyc_nuseless_nonterminals <= 0) { goto _TLA7;
  }
  _T0 = _check_null(Cyc_foutput);
  _T1 = _tag_fat("Useless nonterminals:\n\n",sizeof(char),24U);
  _T2 = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_T0,_T1,_T2);
  i = Cyc_ntokens;
  _TLAC: if (i < Cyc_nsyms) { goto _TLAA;
  }else { goto _TLAB;
  }
  _TLAA: _T3 = Cyc_V;
  _T4 = i / 32;
  _T5 = _check_fat_subscript(_T3,sizeof(unsigned int),_T4);
  _T6 = (unsigned int *)_T5;
  _T7 = *_T6;
  _T8 = i % 32;
  _T9 = 1U << _T8;
  _TA = _T7 & _T9;
  if (_TA != 0U) { goto _TLAD;
  }else { goto _TLAF;
  }
  _TLAF: { struct Cyc_String_pa_PrintArg_struct _T70;
    _T70.tag = 0;
    _TC = Cyc_tags;
    _TD = i;
    _TE = _check_fat_subscript(_TC,sizeof(struct _fat_ptr),_TD);
    _TF = (struct _fat_ptr *)_TE;
    _T10 = *_TF;
    _T70.f1 = _T10;
    _TB = _T70;
  }{ struct Cyc_String_pa_PrintArg_struct _T70 = _TB;
    void * _T71[1];
    _T71[0] = &_T70;
    _T11 = _check_null(Cyc_foutput);
    _T12 = _tag_fat("   %s\n",sizeof(char),7U);
    _T13 = _tag_fat(_T71,sizeof(void *),1);
    Cyc_fprintf(_T11,_T12,_T13);
  }goto _TLAE;
  _TLAD: _TLAE: i = i + 1;
  goto _TLAC;
  _TLAB: goto _TLA8;
  _TLA7: _TLA8: b = 0;
  i = 0;
  _TLB3: if (i < Cyc_ntokens) { goto _TLB1;
  }else { goto _TLB2;
  }
  _TLB1: _T14 = Cyc_V;
  _T15 = i / 32;
  _T16 = _check_fat_subscript(_T14,sizeof(unsigned int),_T15);
  _T17 = (unsigned int *)_T16;
  _T18 = *_T17;
  _T19 = i % 32;
  _T1A = 1U << _T19;
  _T1B = _T18 & _T1A;
  if (_T1B != 0U) { goto _TLB4;
  }else { goto _TLB6;
  }
  _TLB6: _T1C = Cyc_V1;
  _T1D = i / 32;
  _T1E = _check_fat_subscript(_T1C,sizeof(unsigned int),_T1D);
  _T1F = (unsigned int *)_T1E;
  _T20 = *_T1F;
  _T21 = i % 32;
  _T22 = 1U << _T21;
  _T23 = _T20 & _T22;
  if (_T23 != 0U) { goto _TLB4;
  }else { goto _TLB7;
  }
  _TLB7: _T24 = b;
  if (_T24) { goto _TLB8;
  }else { goto _TLBA;
  }
  _TLBA: _T25 = _check_null(Cyc_foutput);
  _T26 = _tag_fat("\n\nTerminals which are not used:\n\n",sizeof(char),34U);
  _T27 = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_T25,_T26,_T27);
  b = 1;
  goto _TLB9;
  _TLB8: _TLB9: { struct Cyc_String_pa_PrintArg_struct _T70;
    _T70.tag = 0;
    _T29 = Cyc_tags;
    _T2A = i;
    _T2B = _check_fat_subscript(_T29,sizeof(struct _fat_ptr),_T2A);
    _T2C = (struct _fat_ptr *)_T2B;
    _T2D = *_T2C;
    _T70.f1 = _T2D;
    _T28 = _T70;
  }{ struct Cyc_String_pa_PrintArg_struct _T70 = _T28;
    void * _T71[1];
    _T71[0] = &_T70;
    _T2E = _check_null(Cyc_foutput);
    _T2F = _tag_fat("   %s\n",sizeof(char),7U);
    _T30 = _tag_fat(_T71,sizeof(void *),1);
    Cyc_fprintf(_T2E,_T2F,_T30);
  }goto _TLB5;
  _TLB4: _TLB5: i = i + 1;
  goto _TLB3;
  _TLB2: if (Cyc_nuseless_productions <= 0) { goto _TLBB;
  }
  _T31 = _check_null(Cyc_foutput);
  _T32 = _tag_fat("\n\nUseless rules:\n\n",sizeof(char),19U);
  _T33 = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_T31,_T32,_T33);
  i = 1;
  _TLC0: if (i <= Cyc_nrules) { goto _TLBE;
  }else { goto _TLBF;
  }
  _TLBE: _T34 = Cyc_P;
  _T35 = i / 32;
  _T36 = _check_fat_subscript(_T34,sizeof(unsigned int),_T35);
  _T37 = (unsigned int *)_T36;
  _T38 = *_T37;
  _T39 = i % 32;
  _T3A = 1U << _T39;
  _T3B = _T38 & _T3A;
  if (_T3B != 0U) { goto _TLC1;
  }else { goto _TLC3;
  }
  _TLC3: { struct Cyc_Int_pa_PrintArg_struct _T70;
    _T70.tag = 1;
    _T3D = i;
    _T70.f1 = (unsigned long)_T3D;
    _T3C = _T70;
  }{ struct Cyc_Int_pa_PrintArg_struct _T70 = _T3C;
    void * _T71[1];
    _T71[0] = &_T70;
    _T3E = _check_null(Cyc_foutput);
    _T3F = _tag_fat("#%-4d  ",sizeof(char),8U);
    _T40 = _tag_fat(_T71,sizeof(void *),1);
    Cyc_fprintf(_T3E,_T3F,_T40);
  }{ struct Cyc_String_pa_PrintArg_struct _T70;
    _T70.tag = 0;
    _T42 = Cyc_tags;
    _T43 = Cyc_rlhs;
    _T44 = i;
    _T45 = _check_fat_subscript(_T43,sizeof(short),_T44);
    _T46 = (short *)_T45;
    _T47 = *_T46;
    _T48 = (int)_T47;
    _T49 = _check_fat_subscript(_T42,sizeof(struct _fat_ptr),_T48);
    _T4A = (struct _fat_ptr *)_T49;
    _T4B = *_T4A;
    _T70.f1 = _T4B;
    _T41 = _T70;
  }{ struct Cyc_String_pa_PrintArg_struct _T70 = _T41;
    void * _T71[1];
    _T71[0] = &_T70;
    _T4C = _check_null(Cyc_foutput);
    _T4D = _tag_fat("%s :\t",sizeof(char),6U);
    _T4E = _tag_fat(_T71,sizeof(void *),1);
    Cyc_fprintf(_T4C,_T4D,_T4E);
  }_T4F = Cyc_ritem;
  _T50 = Cyc_rrhs;
  _T51 = i;
  _T52 = _check_fat_subscript(_T50,sizeof(short),_T51);
  _T53 = (short *)_T52;
  _T54 = *_T53;
  _T55 = (int)_T54;
  r = _fat_ptr_plus(_T4F,sizeof(short),_T55);
  _TLC7: _T56 = r;
  _T57 = _check_fat_subscript(_T56,sizeof(short),0U);
  _T58 = (short *)_T57;
  _T59 = *_T58;
  _T5A = (int)_T59;
  if (_T5A >= 0) { goto _TLC5;
  }else { goto _TLC6;
  }
  _TLC5: { struct Cyc_String_pa_PrintArg_struct _T70;
    _T70.tag = 0;
    _T5C = Cyc_tags;
    _T5D = r;
    _T5E = _T5D.curr;
    _T5F = (short *)_T5E;
    _T60 = *_T5F;
    _T61 = (int)_T60;
    _T62 = _check_fat_subscript(_T5C,sizeof(struct _fat_ptr),_T61);
    _T63 = (struct _fat_ptr *)_T62;
    _T64 = *_T63;
    _T70.f1 = _T64;
    _T5B = _T70;
  }{ struct Cyc_String_pa_PrintArg_struct _T70 = _T5B;
    void * _T71[1];
    _T71[0] = &_T70;
    _T65 = _check_null(Cyc_foutput);
    _T66 = _tag_fat(" %s",sizeof(char),4U);
    _T67 = _tag_fat(_T71,sizeof(void *),1);
    Cyc_fprintf(_T65,_T66,_T67);
  }_T68 = &r;
  _fat_ptr_inplace_plus(_T68,sizeof(short),1);
  goto _TLC7;
  _TLC6: _T69 = _check_null(Cyc_foutput);
  _T6A = _tag_fat(";\n",sizeof(char),3U);
  _T6B = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_T69,_T6A,_T6B);
  goto _TLC2;
  _TLC1: _TLC2: i = i + 1;
  goto _TLC0;
  _TLBF: goto _TLBC;
  _TLBB: _TLBC: if (Cyc_nuseless_nonterminals > 0) { goto _TLCA;
  }else { goto _TLCC;
  }
  _TLCC: if (Cyc_nuseless_productions > 0) { goto _TLCA;
  }else { goto _TLCB;
  }
  _TLCB: _T6C = b;
  if (_T6C) { goto _TLCA;
  }else { goto _TLC8;
  }
  _TLCA: _T6D = _check_null(Cyc_foutput);
  _T6E = _tag_fat("\n\n",sizeof(char),3U);
  _T6F = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_T6D,_T6E,_T6F);
  goto _TLC9;
  _TLC8: _TLC9: ;
}
void Cyc_dump_grammar() {
  struct Cyc_Int_pa_PrintArg_struct _T0;
  int _T1;
  struct Cyc_Int_pa_PrintArg_struct _T2;
  int _T3;
  struct Cyc_Int_pa_PrintArg_struct _T4;
  int _T5;
  struct Cyc_Int_pa_PrintArg_struct _T6;
  int _T7;
  struct Cyc_Int_pa_PrintArg_struct _T8;
  int _T9;
  struct Cyc___cycFILE * _TA;
  struct _fat_ptr _TB;
  struct _fat_ptr _TC;
  struct Cyc___cycFILE * _TD;
  struct _fat_ptr _TE;
  struct _fat_ptr _TF;
  struct Cyc___cycFILE * _T10;
  struct _fat_ptr _T11;
  struct _fat_ptr _T12;
  struct Cyc_Int_pa_PrintArg_struct _T13;
  int _T14;
  struct Cyc_Int_pa_PrintArg_struct _T15;
  struct _fat_ptr _T16;
  int _T17;
  unsigned char * _T18;
  short * _T19;
  short _T1A;
  int _T1B;
  struct Cyc_Int_pa_PrintArg_struct _T1C;
  struct _fat_ptr _T1D;
  int _T1E;
  unsigned char * _T1F;
  short * _T20;
  short _T21;
  int _T22;
  struct Cyc_String_pa_PrintArg_struct _T23;
  struct _fat_ptr _T24;
  int _T25;
  unsigned char * _T26;
  struct _fat_ptr * _T27;
  struct _fat_ptr _T28;
  struct Cyc___cycFILE * _T29;
  struct _fat_ptr _T2A;
  struct _fat_ptr _T2B;
  struct Cyc___cycFILE * _T2C;
  struct _fat_ptr _T2D;
  struct _fat_ptr _T2E;
  struct Cyc___cycFILE * _T2F;
  struct _fat_ptr _T30;
  struct _fat_ptr _T31;
  struct Cyc_Int_pa_PrintArg_struct _T32;
  int _T33;
  struct Cyc_Int_pa_PrintArg_struct _T34;
  struct _fat_ptr _T35;
  int _T36;
  unsigned char * _T37;
  short * _T38;
  short _T39;
  int _T3A;
  struct Cyc_Int_pa_PrintArg_struct _T3B;
  struct _fat_ptr _T3C;
  int _T3D;
  unsigned char * _T3E;
  short * _T3F;
  short _T40;
  int _T41;
  struct Cyc_Int_pa_PrintArg_struct _T42;
  struct _fat_ptr _T43;
  int _T44;
  unsigned char * _T45;
  short * _T46;
  short _T47;
  int _T48;
  struct Cyc_Int_pa_PrintArg_struct _T49;
  struct _fat_ptr _T4A;
  int _T4B;
  unsigned char * _T4C;
  short * _T4D;
  short _T4E;
  int _T4F;
  struct Cyc___cycFILE * _T50;
  struct _fat_ptr _T51;
  struct _fat_ptr _T52;
  struct _fat_ptr _T53;
  struct _fat_ptr _T54;
  int _T55;
  unsigned char * _T56;
  short * _T57;
  short _T58;
  int _T59;
  struct _fat_ptr _T5A;
  unsigned char * _T5B;
  short * _T5C;
  short _T5D;
  int _T5E;
  struct Cyc_Int_pa_PrintArg_struct _T5F;
  struct _fat_ptr _T60;
  unsigned char * _T61;
  short * _T62;
  short _T63;
  int _T64;
  struct Cyc___cycFILE * _T65;
  struct _fat_ptr _T66;
  struct _fat_ptr _T67;
  struct _fat_ptr * _T68;
  struct Cyc_Int_pa_PrintArg_struct _T69;
  struct _fat_ptr _T6A;
  unsigned char * _T6B;
  short * _T6C;
  short _T6D;
  short _T6E;
  int _T6F;
  struct Cyc___cycFILE * _T70;
  struct _fat_ptr _T71;
  struct _fat_ptr _T72;
  struct Cyc___cycFILE * _T73;
  struct _fat_ptr _T74;
  struct _fat_ptr _T75;
  struct Cyc___cycFILE * _T76;
  struct _fat_ptr _T77;
  struct _fat_ptr _T78;
  struct Cyc_Int_pa_PrintArg_struct _T79;
  int _T7A;
  struct Cyc_String_pa_PrintArg_struct _T7B;
  struct _fat_ptr _T7C;
  struct _fat_ptr _T7D;
  int _T7E;
  unsigned char * _T7F;
  short * _T80;
  short _T81;
  int _T82;
  unsigned char * _T83;
  struct _fat_ptr * _T84;
  struct _fat_ptr _T85;
  struct Cyc___cycFILE * _T86;
  struct _fat_ptr _T87;
  struct _fat_ptr _T88;
  struct _fat_ptr _T89;
  struct _fat_ptr _T8A;
  int _T8B;
  unsigned char * _T8C;
  short * _T8D;
  short _T8E;
  int _T8F;
  struct _fat_ptr _T90;
  unsigned char * _T91;
  short * _T92;
  short _T93;
  int _T94;
  struct Cyc_String_pa_PrintArg_struct _T95;
  struct _fat_ptr _T96;
  struct _fat_ptr _T97;
  unsigned char * _T98;
  short * _T99;
  short _T9A;
  int _T9B;
  unsigned char * _T9C;
  struct _fat_ptr * _T9D;
  struct _fat_ptr _T9E;
  struct Cyc___cycFILE * _T9F;
  struct _fat_ptr _TA0;
  struct _fat_ptr _TA1;
  struct _fat_ptr * _TA2;
  struct Cyc___cycFILE * _TA3;
  struct _fat_ptr _TA4;
  struct _fat_ptr _TA5;
  struct Cyc___cycFILE * _TA6;
  struct _fat_ptr _TA7;
  struct _fat_ptr _TA8;
  int i;
  struct _fat_ptr r;
  { struct Cyc_Int_pa_PrintArg_struct _TA9;
    _TA9.tag = 1;
    _T1 = Cyc_ntokens;
    _TA9.f1 = (unsigned long)_T1;
    _T0 = _TA9;
  }{ struct Cyc_Int_pa_PrintArg_struct _TA9 = _T0;
    { struct Cyc_Int_pa_PrintArg_struct _TAA;
      _TAA.tag = 1;
      _T3 = Cyc_nvars;
      _TAA.f1 = (unsigned long)_T3;
      _T2 = _TAA;
    }{ struct Cyc_Int_pa_PrintArg_struct _TAA = _T2;
      { struct Cyc_Int_pa_PrintArg_struct _TAB;
	_TAB.tag = 1;
	_T5 = Cyc_nsyms;
	_TAB.f1 = (unsigned long)_T5;
	_T4 = _TAB;
      }{ struct Cyc_Int_pa_PrintArg_struct _TAB = _T4;
	{ struct Cyc_Int_pa_PrintArg_struct _TAC;
	  _TAC.tag = 1;
	  _T7 = Cyc_nrules;
	  _TAC.f1 = (unsigned long)_T7;
	  _T6 = _TAC;
	}{ struct Cyc_Int_pa_PrintArg_struct _TAC = _T6;
	  { struct Cyc_Int_pa_PrintArg_struct _TAD;
	    _TAD.tag = 1;
	    _T9 = Cyc_nitems;
	    _TAD.f1 = (unsigned long)_T9;
	    _T8 = _TAD;
	  }{ struct Cyc_Int_pa_PrintArg_struct _TAD = _T8;
	    void * _TAE[5];
	    _TAE[0] = &_TA9;
	    _TAE[1] = &_TAA;
	    _TAE[2] = &_TAB;
	    _TAE[3] = &_TAC;
	    _TAE[4] = &_TAD;
	    _TA = _check_null(Cyc_foutput);
	    _TB = _tag_fat("ntokens = %d, nvars = %d, nsyms = %d, nrules = %d, nitems = %d\n\n",
			   sizeof(char),65U);
	    _TC = _tag_fat(_TAE,sizeof(void *),5);
	    Cyc_fprintf(_TA,_TB,_TC);
	  }
	}
      }
    }
  }_TD = _check_null(Cyc_foutput);
  _TE = _tag_fat("Variables\n---------\n\n",sizeof(char),22U);
  _TF = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_TD,_TE,_TF);
  _T10 = _check_null(Cyc_foutput);
  _T11 = _tag_fat("Value  Sprec    Sassoc    Tag\n",sizeof(char),31U);
  _T12 = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_T10,_T11,_T12);
  i = Cyc_ntokens;
  _TLD0: if (i < Cyc_nsyms) { goto _TLCE;
  }else { goto _TLCF;
  }
  _TLCE: { struct Cyc_Int_pa_PrintArg_struct _TA9;
    _TA9.tag = 1;
    _T14 = i;
    _TA9.f1 = (unsigned long)_T14;
    _T13 = _TA9;
  }{ struct Cyc_Int_pa_PrintArg_struct _TA9 = _T13;
    { struct Cyc_Int_pa_PrintArg_struct _TAA;
      _TAA.tag = 1;
      _T16 = Cyc_sprec;
      _T17 = i;
      _T18 = _check_fat_subscript(_T16,sizeof(short),_T17);
      _T19 = (short *)_T18;
      _T1A = *_T19;
      _T1B = (int)_T1A;
      _TAA.f1 = (unsigned long)_T1B;
      _T15 = _TAA;
    }{ struct Cyc_Int_pa_PrintArg_struct _TAA = _T15;
      { struct Cyc_Int_pa_PrintArg_struct _TAB;
	_TAB.tag = 1;
	_T1D = Cyc_sassoc;
	_T1E = i;
	_T1F = _check_fat_subscript(_T1D,sizeof(short),_T1E);
	_T20 = (short *)_T1F;
	_T21 = *_T20;
	_T22 = (int)_T21;
	_TAB.f1 = (unsigned long)_T22;
	_T1C = _TAB;
      }{ struct Cyc_Int_pa_PrintArg_struct _TAB = _T1C;
	{ struct Cyc_String_pa_PrintArg_struct _TAC;
	  _TAC.tag = 0;
	  _T24 = Cyc_tags;
	  _T25 = i;
	  _T26 = _check_fat_subscript(_T24,sizeof(struct _fat_ptr),_T25);
	  _T27 = (struct _fat_ptr *)_T26;
	  _T28 = *_T27;
	  _TAC.f1 = _T28;
	  _T23 = _TAC;
	}{ struct Cyc_String_pa_PrintArg_struct _TAC = _T23;
	  void * _TAD[4];
	  _TAD[0] = &_TA9;
	  _TAD[1] = &_TAA;
	  _TAD[2] = &_TAB;
	  _TAD[3] = &_TAC;
	  _T29 = _check_null(Cyc_foutput);
	  _T2A = _tag_fat("%5d  %5d  %5d  %s\n",sizeof(char),19U);
	  _T2B = _tag_fat(_TAD,sizeof(void *),4);
	  Cyc_fprintf(_T29,_T2A,_T2B);
	}
      }
    }
  }i = i + 1;
  goto _TLD0;
  _TLCF: _T2C = _check_null(Cyc_foutput);
  _T2D = _tag_fat("\n\n",sizeof(char),3U);
  _T2E = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_T2C,_T2D,_T2E);
  _T2F = _check_null(Cyc_foutput);
  _T30 = _tag_fat("Rules\n-----\n\n",sizeof(char),14U);
  _T31 = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_T2F,_T30,_T31);
  i = 1;
  _TLD4: if (i <= Cyc_nrules) { goto _TLD2;
  }else { goto _TLD3;
  }
  _TLD2: { struct Cyc_Int_pa_PrintArg_struct _TA9;
    _TA9.tag = 1;
    _T33 = i;
    _TA9.f1 = (unsigned long)_T33;
    _T32 = _TA9;
  }{ struct Cyc_Int_pa_PrintArg_struct _TA9 = _T32;
    { struct Cyc_Int_pa_PrintArg_struct _TAA;
      _TAA.tag = 1;
      _T35 = Cyc_rprec;
      _T36 = i;
      _T37 = _check_fat_subscript(_T35,sizeof(short),_T36);
      _T38 = (short *)_T37;
      _T39 = *_T38;
      _T3A = (int)_T39;
      _TAA.f1 = (unsigned long)_T3A;
      _T34 = _TAA;
    }{ struct Cyc_Int_pa_PrintArg_struct _TAA = _T34;
      { struct Cyc_Int_pa_PrintArg_struct _TAB;
	_TAB.tag = 1;
	_T3C = Cyc_rassoc;
	_T3D = i;
	_T3E = _check_fat_subscript(_T3C,sizeof(short),_T3D);
	_T3F = (short *)_T3E;
	_T40 = *_T3F;
	_T41 = (int)_T40;
	_TAB.f1 = (unsigned long)_T41;
	_T3B = _TAB;
      }{ struct Cyc_Int_pa_PrintArg_struct _TAB = _T3B;
	{ struct Cyc_Int_pa_PrintArg_struct _TAC;
	  _TAC.tag = 1;
	  _T43 = Cyc_rlhs;
	  _T44 = i;
	  _T45 = _check_fat_subscript(_T43,sizeof(short),_T44);
	  _T46 = (short *)_T45;
	  _T47 = *_T46;
	  _T48 = (int)_T47;
	  _TAC.f1 = (unsigned long)_T48;
	  _T42 = _TAC;
	}{ struct Cyc_Int_pa_PrintArg_struct _TAC = _T42;
	  { struct Cyc_Int_pa_PrintArg_struct _TAD;
	    _TAD.tag = 1;
	    _T4A = Cyc_rrhs;
	    _T4B = i;
	    _T4C = _check_fat_subscript(_T4A,sizeof(short),_T4B);
	    _T4D = (short *)_T4C;
	    _T4E = *_T4D;
	    _T4F = (int)_T4E;
	    _TAD.f1 = (unsigned long)_T4F;
	    _T49 = _TAD;
	  }{ struct Cyc_Int_pa_PrintArg_struct _TAD = _T49;
	    void * _TAE[5];
	    _TAE[0] = &_TA9;
	    _TAE[1] = &_TAA;
	    _TAE[2] = &_TAB;
	    _TAE[3] = &_TAC;
	    _TAE[4] = &_TAD;
	    _T50 = _check_null(Cyc_foutput);
	    _T51 = _tag_fat("%-5d(%5d%5d)%5d : (@%-5d)",sizeof(char),26U);
	    _T52 = _tag_fat(_TAE,sizeof(void *),5);
	    Cyc_fprintf(_T50,_T51,_T52);
	  }
	}
      }
    }
  }_T53 = Cyc_ritem;
  _T54 = Cyc_rrhs;
  _T55 = i;
  _T56 = _check_fat_subscript(_T54,sizeof(short),_T55);
  _T57 = (short *)_T56;
  _T58 = *_T57;
  _T59 = (int)_T58;
  r = _fat_ptr_plus(_T53,sizeof(short),_T59);
  _TLD8: _T5A = r;
  _T5B = _check_fat_subscript(_T5A,sizeof(short),0U);
  _T5C = (short *)_T5B;
  _T5D = *_T5C;
  _T5E = (int)_T5D;
  if (_T5E > 0) { goto _TLD6;
  }else { goto _TLD7;
  }
  _TLD6: { struct Cyc_Int_pa_PrintArg_struct _TA9;
    _TA9.tag = 1;
    _T60 = r;
    _T61 = _T60.curr;
    _T62 = (short *)_T61;
    _T63 = *_T62;
    _T64 = (int)_T63;
    _TA9.f1 = (unsigned long)_T64;
    _T5F = _TA9;
  }{ struct Cyc_Int_pa_PrintArg_struct _TA9 = _T5F;
    void * _TAA[1];
    _TAA[0] = &_TA9;
    _T65 = _check_null(Cyc_foutput);
    _T66 = _tag_fat("%5d",sizeof(char),4U);
    _T67 = _tag_fat(_TAA,sizeof(void *),1);
    Cyc_fprintf(_T65,_T66,_T67);
  }_T68 = &r;
  _fat_ptr_inplace_plus(_T68,sizeof(short),1);
  goto _TLD8;
  _TLD7: { struct Cyc_Int_pa_PrintArg_struct _TA9;
    _TA9.tag = 1;
    _T6A = r;
    _T6B = _T6A.curr;
    _T6C = (short *)_T6B;
    _T6D = *_T6C;
    _T6E = - _T6D;
    _T6F = (int)_T6E;
    _TA9.f1 = (unsigned long)_T6F;
    _T69 = _TA9;
  }{ struct Cyc_Int_pa_PrintArg_struct _TA9 = _T69;
    void * _TAA[1];
    _TAA[0] = &_TA9;
    _T70 = _check_null(Cyc_foutput);
    _T71 = _tag_fat(" [%d]\n",sizeof(char),7U);
    _T72 = _tag_fat(_TAA,sizeof(void *),1);
    Cyc_fprintf(_T70,_T71,_T72);
  }i = i + 1;
  goto _TLD4;
  _TLD3: _T73 = _check_null(Cyc_foutput);
  _T74 = _tag_fat("\n\n",sizeof(char),3U);
  _T75 = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_T73,_T74,_T75);
  _T76 = _check_null(Cyc_foutput);
  _T77 = _tag_fat("Rules interpreted\n-----------------\n\n",sizeof(char),
		  38U);
  _T78 = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_T76,_T77,_T78);
  i = 1;
  _TLDC: if (i <= Cyc_nrules) { goto _TLDA;
  }else { goto _TLDB;
  }
  _TLDA: { struct Cyc_Int_pa_PrintArg_struct _TA9;
    _TA9.tag = 1;
    _T7A = i;
    _TA9.f1 = (unsigned long)_T7A;
    _T79 = _TA9;
  }{ struct Cyc_Int_pa_PrintArg_struct _TA9 = _T79;
    { struct Cyc_String_pa_PrintArg_struct _TAA;
      _TAA.tag = 0;
      _T7C = Cyc_tags;
      _T7D = Cyc_rlhs;
      _T7E = i;
      _T7F = _check_fat_subscript(_T7D,sizeof(short),_T7E);
      _T80 = (short *)_T7F;
      _T81 = *_T80;
      _T82 = (int)_T81;
      _T83 = _check_fat_subscript(_T7C,sizeof(struct _fat_ptr),_T82);
      _T84 = (struct _fat_ptr *)_T83;
      _T85 = *_T84;
      _TAA.f1 = _T85;
      _T7B = _TAA;
    }{ struct Cyc_String_pa_PrintArg_struct _TAA = _T7B;
      void * _TAB[2];
      _TAB[0] = &_TA9;
      _TAB[1] = &_TAA;
      _T86 = _check_null(Cyc_foutput);
      _T87 = _tag_fat("%-5d  %s :",sizeof(char),11U);
      _T88 = _tag_fat(_TAB,sizeof(void *),2);
      Cyc_fprintf(_T86,_T87,_T88);
    }
  }_T89 = Cyc_ritem;
  _T8A = Cyc_rrhs;
  _T8B = i;
  _T8C = _check_fat_subscript(_T8A,sizeof(short),_T8B);
  _T8D = (short *)_T8C;
  _T8E = *_T8D;
  _T8F = (int)_T8E;
  r = _fat_ptr_plus(_T89,sizeof(short),_T8F);
  _TLE0: _T90 = r;
  _T91 = _check_fat_subscript(_T90,sizeof(short),0U);
  _T92 = (short *)_T91;
  _T93 = *_T92;
  _T94 = (int)_T93;
  if (_T94 > 0) { goto _TLDE;
  }else { goto _TLDF;
  }
  _TLDE: { struct Cyc_String_pa_PrintArg_struct _TA9;
    _TA9.tag = 0;
    _T96 = Cyc_tags;
    _T97 = r;
    _T98 = _T97.curr;
    _T99 = (short *)_T98;
    _T9A = *_T99;
    _T9B = (int)_T9A;
    _T9C = _check_fat_subscript(_T96,sizeof(struct _fat_ptr),_T9B);
    _T9D = (struct _fat_ptr *)_T9C;
    _T9E = *_T9D;
    _TA9.f1 = _T9E;
    _T95 = _TA9;
  }{ struct Cyc_String_pa_PrintArg_struct _TA9 = _T95;
    void * _TAA[1];
    _TAA[0] = &_TA9;
    _T9F = _check_null(Cyc_foutput);
    _TA0 = _tag_fat(" %s",sizeof(char),4U);
    _TA1 = _tag_fat(_TAA,sizeof(void *),1);
    Cyc_fprintf(_T9F,_TA0,_TA1);
  }_TA2 = &r;
  _fat_ptr_inplace_plus(_TA2,sizeof(short),1);
  goto _TLE0;
  _TLDF: _TA3 = _check_null(Cyc_foutput);
  _TA4 = _tag_fat("\n",sizeof(char),2U);
  _TA5 = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_TA3,_TA4,_TA5);
  i = i + 1;
  goto _TLDC;
  _TLDB: _TA6 = _check_null(Cyc_foutput);
  _TA7 = _tag_fat("\n\n",sizeof(char),3U);
  _TA8 = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_TA6,_TA7,_TA8);
}
static void Cyc_print_notices() {
  int _T0;
  int _T1;
  struct Cyc_Int_pa_PrintArg_struct _T2;
  int _T3;
  struct Cyc___cycFILE * _T4;
  struct _fat_ptr _T5;
  struct _fat_ptr _T6;
  struct Cyc_String_pa_PrintArg_struct _T7;
  struct Cyc___cycFILE * _T8;
  struct _fat_ptr _T9;
  struct _fat_ptr _TA;
  struct Cyc_Int_pa_PrintArg_struct _TB;
  int _TC;
  struct Cyc_String_pa_PrintArg_struct _TD;
  struct Cyc___cycFILE * _TE;
  struct _fat_ptr _TF;
  struct _fat_ptr _T10;
  struct Cyc___cycFILE * _T11;
  struct _fat_ptr _T12;
  struct _fat_ptr _T13;
  struct Cyc_Int_pa_PrintArg_struct _T14;
  int _T15;
  struct Cyc_String_pa_PrintArg_struct _T16;
  struct Cyc___cycFILE * _T17;
  struct _fat_ptr _T18;
  struct _fat_ptr _T19;
  struct Cyc___cycFILE * _T1A;
  struct _fat_ptr _T1B;
  struct _fat_ptr _T1C;
  _T0 = Cyc_fixed_outfiles;
  if (! _T0) { goto _TLE1;
  }
  _T1 = Cyc_nuseless_productions;
  if (! _T1) { goto _TLE1;
  }
  { struct Cyc_Int_pa_PrintArg_struct _T1D;
    _T1D.tag = 1;
    _T3 = Cyc_nuseless_productions;
    _T1D.f1 = (unsigned long)_T3;
    _T2 = _T1D;
  }{ struct Cyc_Int_pa_PrintArg_struct _T1D = _T2;
    void * _T1E[1];
    _T1E[0] = &_T1D;
    _T4 = Cyc_stderr;
    _T5 = _tag_fat("%d rules never reduced\n",sizeof(char),24U);
    _T6 = _tag_fat(_T1E,sizeof(void *),1);
    Cyc_fprintf(_T4,_T5,_T6);
  }goto _TLE2;
  _TLE1: _TLE2: { struct Cyc_String_pa_PrintArg_struct _T1D;
    _T1D.tag = 0;
    _T1D.f1 = Cyc_infile;
    _T7 = _T1D;
  }{ struct Cyc_String_pa_PrintArg_struct _T1D = _T7;
    void * _T1E[1];
    _T1E[0] = &_T1D;
    _T8 = Cyc_stderr;
    _T9 = _tag_fat("%s contains ",sizeof(char),13U);
    _TA = _tag_fat(_T1E,sizeof(void *),1);
    Cyc_fprintf(_T8,_T9,_TA);
  }if (Cyc_nuseless_nonterminals <= 0) { goto _TLE3;
  }
  { struct Cyc_Int_pa_PrintArg_struct _T1D;
    _T1D.tag = 1;
    _TC = Cyc_nuseless_nonterminals;
    _T1D.f1 = (unsigned long)_TC;
    _TB = _T1D;
  }{ struct Cyc_Int_pa_PrintArg_struct _T1D = _TB;
    { struct Cyc_String_pa_PrintArg_struct _T1E;
      _T1E.tag = 0;
      if (Cyc_nuseless_nonterminals != 1) { goto _TLE5;
      }
      _T1E.f1 = _tag_fat("",sizeof(char),1U);
      goto _TLE6;
      _TLE5: _T1E.f1 = _tag_fat("s",sizeof(char),2U);
      _TLE6: _TD = _T1E;
    }{ struct Cyc_String_pa_PrintArg_struct _T1E = _TD;
      void * _T1F[2];
      _T1F[0] = &_T1D;
      _T1F[1] = &_T1E;
      _TE = Cyc_stderr;
      _TF = _tag_fat("%d useless nonterminal%s",sizeof(char),25U);
      _T10 = _tag_fat(_T1F,sizeof(void *),2);
      Cyc_fprintf(_TE,_TF,_T10);
    }
  }goto _TLE4;
  _TLE3: _TLE4: if (Cyc_nuseless_nonterminals <= 0) { goto _TLE7;
  }
  if (Cyc_nuseless_productions <= 0) { goto _TLE7;
  }
  _T11 = Cyc_stderr;
  _T12 = _tag_fat(" and ",sizeof(char),6U);
  _T13 = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_T11,_T12,_T13);
  goto _TLE8;
  _TLE7: _TLE8: if (Cyc_nuseless_productions <= 0) { goto _TLE9;
  }
  { struct Cyc_Int_pa_PrintArg_struct _T1D;
    _T1D.tag = 1;
    _T15 = Cyc_nuseless_productions;
    _T1D.f1 = (unsigned long)_T15;
    _T14 = _T1D;
  }{ struct Cyc_Int_pa_PrintArg_struct _T1D = _T14;
    { struct Cyc_String_pa_PrintArg_struct _T1E;
      _T1E.tag = 0;
      if (Cyc_nuseless_productions != 1) { goto _TLEB;
      }
      _T1E.f1 = _tag_fat("",sizeof(char),1U);
      goto _TLEC;
      _TLEB: _T1E.f1 = _tag_fat("s",sizeof(char),2U);
      _TLEC: _T16 = _T1E;
    }{ struct Cyc_String_pa_PrintArg_struct _T1E = _T16;
      void * _T1F[2];
      _T1F[0] = &_T1D;
      _T1F[1] = &_T1E;
      _T17 = Cyc_stderr;
      _T18 = _tag_fat("%d useless rule%s",sizeof(char),18U);
      _T19 = _tag_fat(_T1F,sizeof(void *),2);
      Cyc_fprintf(_T17,_T18,_T19);
    }
  }goto _TLEA;
  _TLE9: _TLEA: _T1A = Cyc_stderr;
  _T1B = _tag_fat("\n",sizeof(char),2U);
  _T1C = _tag_fat(0U,sizeof(void *),0);
  Cyc_fprintf(_T1A,_T1B,_T1C);
  Cyc_fflush(Cyc_stderr);
}
